#ifndef  ENTITY_SDAIUNCONSTRAINED_PAIR_VALUE_CC
#define  ENTITY_SDAIUNCONSTRAINED_PAIR_VALUE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiUnconstrained_pair_value.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2496Rpair_value_applies_to_pair = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2497actual_placement = 0;

SdaiUnconstrained_pair_value::SdaiUnconstrained_pair_value(): SdaiPair_value(), _pair_value_applies_to_pair( 0 ), _actual_placement( 0 ) {
        /*  parent: SdaiPair_value  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2496Rpair_value_applies_to_pair, ( SDAI_Application_instance_ptr * ) & _pair_value_applies_to_pair );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "applies_to_pair" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2497actual_placement, ( SDAI_Application_instance_ptr * ) & _actual_placement );
    a->set_null();
    attributes.push( a );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "applies_to_pair", "pair_value" );
}

SdaiUnconstrained_pair_value::SdaiUnconstrained_pair_value ( SdaiUnconstrained_pair_value & e ) : SdaiPair_value() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiUnconstrained_pair_value::~SdaiUnconstrained_pair_value() {
}

SdaiUnconstrained_pair_value::SdaiUnconstrained_pair_value( SDAI_Application_instance * se, bool addAttrs ) : SdaiPair_value( se, addAttrs ), _pair_value_applies_to_pair( 0 ), _actual_placement( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiPair_value */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2496Rpair_value_applies_to_pair, ( SDAI_Application_instance_ptr * ) &_pair_value_applies_to_pair );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "applies_to_pair" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2497actual_placement, ( SDAI_Application_instance_ptr * ) &_actual_placement );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "applies_to_pair", "pair_value" );
}


SdaiUnconstrained_pair_ptr SdaiUnconstrained_pair_value::pair_value_applies_to_pair_() {
    if( !_pair_value_applies_to_pair ) {
        _pair_value_applies_to_pair = new SdaiUnconstrained_pair;
    }
    return (SdaiUnconstrained_pair_ptr) _pair_value_applies_to_pair;
}

SdaiUnconstrained_pair_ptr_c SdaiUnconstrained_pair_value::pair_value_applies_to_pair_() const {
    return (SdaiUnconstrained_pair_ptr) _pair_value_applies_to_pair;
}

void SdaiUnconstrained_pair_value::pair_value_applies_to_pair_( const SdaiUnconstrained_pair_ptr x ) {
    _pair_value_applies_to_pair = x;
}

SdaiAxis2_placement_3d_ptr SdaiUnconstrained_pair_value::actual_placement_() {
    if( !_actual_placement ) {
        _actual_placement = new SdaiAxis2_placement_3d;
    }
    return (SdaiAxis2_placement_3d_ptr) _actual_placement;
}

SdaiAxis2_placement_3d_ptr_c SdaiUnconstrained_pair_value::actual_placement_() const {
    return (SdaiAxis2_placement_3d_ptr) _actual_placement;
}

void SdaiUnconstrained_pair_value::actual_placement_( const SdaiAxis2_placement_3d_ptr x ) {
    _actual_placement = x;
}

void init_SdaiUnconstrained_pair_value( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_pair_value);
    ap242_managed_model_based_3d_engineering_mim_lf::e_pair_value->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value);
    ap242_managed_model_based_3d_engineering_mim_lf::a_2496Rpair_value_applies_to_pair =
      new AttrDescriptor( "pair_value.applies_to_pair", ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair, LFalse,
       LFalse, AttrType_Redefining, *ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2496Rpair_value_applies_to_pair);
    ap242_managed_model_based_3d_engineering_mim_lf::a_2497actual_placement =
      new AttrDescriptor( "actual_placement", ap242_managed_model_based_3d_engineering_mim_lf::e_axis2_placement_3d, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2497actual_placement);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_unconstrained_pair_value );
}

#endif
