#ifndef  ENTITY_SDAIRISK_PERCEPTION_CONTEXT_H
#define  ENTITY_SDAIRISK_PERCEPTION_CONTEXT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRisk_perception_context : public SdaiProduct_definition_context {
     protected:
    public: 
        SdaiRisk_perception_context();
        SdaiRisk_perception_context( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRisk_perception_context( SdaiRisk_perception_context & e );
        ~SdaiRisk_perception_context();
        int opcode() {
            return 1732;
        }
};

inline SdaiRisk_perception_context * create_SdaiRisk_perception_context() {
    return new SdaiRisk_perception_context;
}

void init_SdaiRisk_perception_context(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_risk_perception_context;
}

#endif
