#ifndef  ENTITY_SDAIWEDGE_VOLUME_H
#define  ENTITY_SDAIWEDGE_VOLUME_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiWedge_volume : public SdaiVolume {
     protected:
        SDAI_Application_instance_ptr _position = NULL;
        SDAI_Real _x = 0.0;
        SDAI_Real _y = 0.0;
        SDAI_Real _z = 0.0;
        SDAI_Real _ltx = 0.0;
    public: 
        SdaiWedge_volume();
        SdaiWedge_volume( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiWedge_volume( SdaiWedge_volume & e );
        ~SdaiWedge_volume();
        int opcode() {
            return 575;
        }
        SdaiAxis2_placement_3d_ptr_c position_() const;
        SdaiAxis2_placement_3d_ptr   position_();
        void position_( const SdaiAxis2_placement_3d_ptr x );

        SdaiPositive_length_measure   x_() const;
        void x_( const SdaiPositive_length_measure x );

        SdaiPositive_length_measure   y_() const;
        void y_( const SdaiPositive_length_measure x );

        SdaiPositive_length_measure   z_() const;
        void z_( const SdaiPositive_length_measure x );

        SdaiLength_measure   ltx_() const;
        void ltx_( const SdaiLength_measure x );

};

inline SdaiWedge_volume * create_SdaiWedge_volume() {
    return new SdaiWedge_volume;
}

void init_SdaiWedge_volume(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_wedge_volume;
    extern AttrDescriptor *a_918position;
    extern AttrDescriptor *a_919x;
    extern AttrDescriptor *a_920y;
    extern AttrDescriptor *a_921z;
    extern AttrDescriptor *a_922ltx;
}

#endif
