#ifndef  ENTITY_SDAICURRENCY_H
#define  ENTITY_SDAICURRENCY_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCurrency : public SdaiContext_dependent_unit {
     protected:
    public: 
        SdaiCurrency();
        SdaiCurrency( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCurrency( SdaiCurrency & e );
        ~SdaiCurrency();
        int opcode() {
            return 139;
        }
};

inline SdaiCurrency * create_SdaiCurrency() {
    return new SdaiCurrency;
}

void init_SdaiCurrency(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_currency;
}

#endif
