#ifndef  ENTITY_SDAIDATUM_REFERENCE_MODIFIER_WITH_VALUE_CC
#define  ENTITY_SDAIDATUM_REFERENCE_MODIFIER_WITH_VALUE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiDatum_reference_modifier_with_value.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1902modifier_type = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1903modifier_value = 0;

SdaiDatum_reference_modifier_with_value::SdaiDatum_reference_modifier_with_value() : _modifier_value( 0 ) {
        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1902modifier_type, & _modifier_type );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1903modifier_value, ( SDAI_Application_instance_ptr * ) & _modifier_value );
    a->set_null();
    attributes.push( a );
}

SdaiDatum_reference_modifier_with_value::SdaiDatum_reference_modifier_with_value ( SdaiDatum_reference_modifier_with_value & e ) : SDAI_Application_instance() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiDatum_reference_modifier_with_value::~SdaiDatum_reference_modifier_with_value() {
}

SdaiDatum_reference_modifier_with_value::SdaiDatum_reference_modifier_with_value( SDAI_Application_instance * se, bool addAttrs ) : _modifier_value( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
    ( void ) addAttrs; /* quell potentially unused var */

        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1902modifier_type,  &_modifier_type );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1903modifier_value, ( SDAI_Application_instance_ptr * ) &_modifier_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiDatum_reference_modifier_type_var SdaiDatum_reference_modifier_with_value::modifier_type_() {
    return (Datum_reference_modifier_type) _modifier_type;
}

const SdaiDatum_reference_modifier_type_var SdaiDatum_reference_modifier_with_value::modifier_type_() const {
    return (const Datum_reference_modifier_type) _modifier_type;
}

void SdaiDatum_reference_modifier_with_value::modifier_type_( const SdaiDatum_reference_modifier_type_var x ) {
    _modifier_type.put( x );
}

SdaiLength_measure_with_unit_ptr SdaiDatum_reference_modifier_with_value::modifier_value_() {
    if( !_modifier_value ) {
        _modifier_value = new SdaiLength_measure_with_unit;
    }
    return (SdaiLength_measure_with_unit_ptr) _modifier_value;
}

SdaiLength_measure_with_unit_ptr_c SdaiDatum_reference_modifier_with_value::modifier_value_() const {
    return (SdaiLength_measure_with_unit_ptr) _modifier_value;
}

void SdaiDatum_reference_modifier_with_value::modifier_value_( const SdaiLength_measure_with_unit_ptr x ) {
    _modifier_value = x;
}

void init_SdaiDatum_reference_modifier_with_value( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "modifier_value\\measure_with_unit.value_component > 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value->_where_rules->Append( wr );
        ap242_managed_model_based_3d_engineering_mim_lf::a_1902modifier_type =
          new AttrDescriptor("modifier_type",ap242_managed_model_based_3d_engineering_mim_lf::t_datum_reference_modifier_type,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1902modifier_type);
    ap242_managed_model_based_3d_engineering_mim_lf::a_1903modifier_value =
      new AttrDescriptor( "modifier_value", ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1903modifier_value);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_datum_reference_modifier_with_value );
}

#endif
