#ifndef  ENTITY_SDAIGEOMETRIC_TOLERANCE_H
#define  ENTITY_SDAIGEOMETRIC_TOLERANCE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiGeometric_tolerance : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
        SDAI_String _description;    //  OPTIONAL
        SDAI_Application_instance_ptr _magnitude = NULL;    //  OPTIONAL
        SdaiGeometric_tolerance_target _toleranced_shape_aspect;
    public: 
        SdaiGeometric_tolerance();
        SdaiGeometric_tolerance( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiGeometric_tolerance( SdaiGeometric_tolerance & e );
        ~SdaiGeometric_tolerance();
        int opcode() {
            return 214;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

        SdaiLength_measure_with_unit_ptr_c magnitude_() const;
        SdaiLength_measure_with_unit_ptr   magnitude_();
        void magnitude_( const SdaiLength_measure_with_unit_ptr x );

        SdaiGeometric_tolerance_target_ptr_c toleranced_shape_aspect_() const;
        SdaiGeometric_tolerance_target_ptr   toleranced_shape_aspect_();
        void toleranced_shape_aspect_( const SdaiGeometric_tolerance_target_ptr x );

        EntityAggregate_ptr_c auxiliary_classification_() const;
        EntityAggregate_ptr   auxiliary_classification_();
        void auxiliary_classification_( const EntityAggregate_ptr x );

        EntityAggregate_ptr_c tolerance_relationship_() const;
        EntityAggregate_ptr   tolerance_relationship_();
        void tolerance_relationship_( const EntityAggregate_ptr x );

};

inline SdaiGeometric_tolerance * create_SdaiGeometric_tolerance() {
    return new SdaiGeometric_tolerance;
}

void init_SdaiGeometric_tolerance(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_geometric_tolerance;
    extern AttrDescriptor *a_352name;
    extern AttrDescriptor *a_353description;
    extern AttrDescriptor *a_354magnitude;
    extern AttrDescriptor *a_355toleranced_shape_aspect;
    extern Derived_attribute *a_356Dcontrolling_shape;
    extern Derived_attribute *a_357Did;
    extern Inverse_attribute *a_358Iauxiliary_classification;
    extern Inverse_attribute *a_359Itolerance_relationship;
}

#endif
