#ifndef  ENTITY_SDAIUNARY_GENERIC_EXPRESSION_H
#define  ENTITY_SDAIUNARY_GENERIC_EXPRESSION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiUnary_generic_expression : public SdaiGeneric_expression {
     protected:
        SDAI_Application_instance_ptr _operand = NULL;
    public: 
        SdaiUnary_generic_expression();
        SdaiUnary_generic_expression( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiUnary_generic_expression( SdaiUnary_generic_expression & e );
        ~SdaiUnary_generic_expression();
        int opcode() {
            return 69;
        }
        SdaiGeneric_expression_ptr_c operand_() const;
        SdaiGeneric_expression_ptr   operand_();
        void operand_( const SdaiGeneric_expression_ptr x );

};

inline SdaiUnary_generic_expression * create_SdaiUnary_generic_expression() {
    return new SdaiUnary_generic_expression;
}

void init_SdaiUnary_generic_expression(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_unary_generic_expression;
    extern AttrDescriptor *a_114operand;
}

#endif
