#ifndef  ENTITY_SDAIANALYSIS_ITEM_H
#define  ENTITY_SDAIANALYSIS_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAnalysis_item : public SdaiGroup_assignment {
     protected:
        SdaiAnalysed_item_agg_ptr _items = NULL;          //  of  analysed_item

        SDAI_Application_instance_ptr _group_assignment_assigned_group = NULL;
    public: 
        SdaiAnalysis_item();
        SdaiAnalysis_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAnalysis_item( SdaiAnalysis_item & e );
        ~SdaiAnalysis_item();
        int opcode() {
            return 1922;
        }
        SdaiAnalysed_item_agg_ptr_c items_() const;
        SdaiAnalysed_item_agg_ptr   items_();
        void items_( const SdaiAnalysed_item_agg_ptr x );

        SdaiAnalysis_assignment_ptr_c group_assignment_assigned_group_() const;
        SdaiAnalysis_assignment_ptr   group_assignment_assigned_group_();
        void group_assignment_assigned_group_( const SdaiAnalysis_assignment_ptr x );

};

inline SdaiAnalysis_item * create_SdaiAnalysis_item() {
    return new SdaiAnalysis_item;
}

void init_SdaiAnalysis_item(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_analysis_item;
    extern AttrDescriptor *a_2844items;
    extern AttrDescriptor *a_2845Rgroup_assignment_assigned_group;
}

#endif
