#ifndef  ENTITY_SDAIINTEGER_DEFINED_FUNCTION_H
#define  ENTITY_SDAIINTEGER_DEFINED_FUNCTION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiInteger_defined_function : public SdaiNumeric_defined_function {
     protected:
    public: 
        SdaiInteger_defined_function();
        SdaiInteger_defined_function( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiInteger_defined_function( SdaiInteger_defined_function & e );
        ~SdaiInteger_defined_function();
        int opcode() {
            return 1588;
        }
};

inline SdaiInteger_defined_function * create_SdaiInteger_defined_function() {
    return new SdaiInteger_defined_function;
}

void init_SdaiInteger_defined_function(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_integer_defined_function;
}

#endif
