#ifndef  ENTITY_SDAIDEPENDENT_VARIABLE_DEFINITION_CC
#define  ENTITY_SDAIDEPENDENT_VARIABLE_DEFINITION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiDependent_variable_definition.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2039name = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2040description = 0;

SdaiDependent_variable_definition::SdaiDependent_variable_definition(): SdaiUnary_generic_expression() {
        /*  parent: SdaiUnary_generic_expression  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2039name, & _name );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2040description, & _description );
    a->set_null();
    attributes.push( a );
}

SdaiDependent_variable_definition::SdaiDependent_variable_definition ( SdaiDependent_variable_definition & e ) : SdaiUnary_generic_expression() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiDependent_variable_definition::~SdaiDependent_variable_definition() {
}

SdaiDependent_variable_definition::SdaiDependent_variable_definition( SDAI_Application_instance * se, bool addAttrs ) : SdaiUnary_generic_expression( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiUnary_generic_expression */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2039name,  &_name );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2040description,  &_description );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiLabel SdaiDependent_variable_definition::name_() {
    return _name;
}

const SdaiLabel SdaiDependent_variable_definition::name_() const {
    return (const SdaiLabel) _name;
}

void SdaiDependent_variable_definition::name_( const SdaiLabel x ) {
    _name = x;
}

SdaiText SdaiDependent_variable_definition::description_() {
    return _description;
}

const SdaiText SdaiDependent_variable_definition::description_() const {
    return (const SdaiText) _description;
}

void SdaiDependent_variable_definition::description_( const SdaiText x ) {
    _description = x;
}

void init_SdaiDependent_variable_definition( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_unary_generic_expression);
    ap242_managed_model_based_3d_engineering_mim_lf::e_unary_generic_expression->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2039name =
          new AttrDescriptor("name",ap242_managed_model_based_3d_engineering_mim_lf::t_label,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition);
        ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2039name);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2040description =
          new AttrDescriptor("description",ap242_managed_model_based_3d_engineering_mim_lf::t_text,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition);
        ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2040description);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_dependent_variable_definition );
}

#endif
