#ifndef  ENTITY_SDAIAPPLIED_USAGE_RIGHT_H
#define  ENTITY_SDAIAPPLIED_USAGE_RIGHT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiApplied_usage_right : public SdaiAction_assignment {
     protected:
        SdaiIr_usage_item_agg_ptr _items = NULL;          //  of  ir_usage_item

    public: 
        SdaiApplied_usage_right();
        SdaiApplied_usage_right( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiApplied_usage_right( SdaiApplied_usage_right & e );
        ~SdaiApplied_usage_right();
        int opcode() {
            return 440;
        }
        SdaiIr_usage_item_agg_ptr_c items_() const;
        SdaiIr_usage_item_agg_ptr   items_();
        void items_( const SdaiIr_usage_item_agg_ptr x );

};

inline SdaiApplied_usage_right * create_SdaiApplied_usage_right() {
    return new SdaiApplied_usage_right;
}

void init_SdaiApplied_usage_right(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_applied_usage_right;
    extern AttrDescriptor *a_686items;
}

#endif
