#ifndef  ENTITY_SDAITESSELLATED_ITEM_H
#define  ENTITY_SDAITESSELLATED_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiTessellated_item : public SdaiGeometric_representation_item {
     protected:
    public: 
        SdaiTessellated_item();
        SdaiTessellated_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiTessellated_item( SdaiTessellated_item & e );
        ~SdaiTessellated_item();
        int opcode() {
            return 455;
        }
};

inline SdaiTessellated_item * create_SdaiTessellated_item() {
    return new SdaiTessellated_item;
}

void init_SdaiTessellated_item(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_tessellated_item;
}

#endif
