#ifndef  ENTITY_SDAISCANNED_DATA_ITEM_H
#define  ENTITY_SDAISCANNED_DATA_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiScanned_data_item : public SdaiGeometric_representation_item {
     protected:
    public: 
        SdaiScanned_data_item();
        SdaiScanned_data_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiScanned_data_item( SdaiScanned_data_item & e );
        ~SdaiScanned_data_item();
        int opcode() {
            return 125;
        }
};

inline SdaiScanned_data_item * create_SdaiScanned_data_item() {
    return new SdaiScanned_data_item;
}

void init_SdaiScanned_data_item(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_scanned_data_item;
}

#endif
