#ifndef  ENTITY_SDAIA3M_DATA_QUALITY_CRITERIA_REPRESENTATION_H
#define  ENTITY_SDAIA3M_DATA_QUALITY_CRITERIA_REPRESENTATION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiA3m_data_quality_criteria_representation : public SdaiData_quality_criteria_representation {
     protected:
    public: 
        SdaiA3m_data_quality_criteria_representation();
        SdaiA3m_data_quality_criteria_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiA3m_data_quality_criteria_representation( SdaiA3m_data_quality_criteria_representation & e );
        ~SdaiA3m_data_quality_criteria_representation();
        int opcode() {
            return 641;
        }
};

inline SdaiA3m_data_quality_criteria_representation * create_SdaiA3m_data_quality_criteria_representation() {
    return new SdaiA3m_data_quality_criteria_representation;
}

void init_SdaiA3m_data_quality_criteria_representation(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_a3m_data_quality_criteria_representation;
}

#endif
