#ifndef  ENTITY_SDAICUBIC_BEZIER_TESSELLATED_EDGE_CC
#define  ENTITY_SDAICUBIC_BEZIER_TESSELLATED_EDGE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiCubic_bezier_tessellated_edge.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1826Rtessellated_edge_line_strip = 0;

SdaiCubic_bezier_tessellated_edge::SdaiCubic_bezier_tessellated_edge(): SdaiTessellated_edge(), _tessellated_edge_line_strip( 0 ) {
        /*  parent: SdaiTessellated_edge  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge;
    _tessellated_edge_line_strip = new IntAggregate;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1826Rtessellated_edge_line_strip, _tessellated_edge_line_strip );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "line_strip" );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "line_strip", "tessellated_edge" );
}

SdaiCubic_bezier_tessellated_edge::SdaiCubic_bezier_tessellated_edge ( SdaiCubic_bezier_tessellated_edge & e ) : SdaiTessellated_edge() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiCubic_bezier_tessellated_edge::~SdaiCubic_bezier_tessellated_edge() {
    delete _tessellated_edge_line_strip;
}

SdaiCubic_bezier_tessellated_edge::SdaiCubic_bezier_tessellated_edge( SDAI_Application_instance * se, bool addAttrs ) : SdaiTessellated_edge( se, addAttrs ), _tessellated_edge_line_strip( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiTessellated_edge */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge;
    _tessellated_edge_line_strip = new IntAggregate;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1826Rtessellated_edge_line_strip,  _tessellated_edge_line_strip );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "line_strip" );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "line_strip", "tessellated_edge" );
}


IntAggregate_ptr SdaiCubic_bezier_tessellated_edge::tessellated_edge_line_strip_() {
    if( !_tessellated_edge_line_strip ) {
        _tessellated_edge_line_strip = new IntAggregate;
    }
    return ( IntAggregate_ptr ) _tessellated_edge_line_strip;
}

IntAggregate_ptr_c SdaiCubic_bezier_tessellated_edge::tessellated_edge_line_strip_() const {
    return ( IntAggregate_ptr ) _tessellated_edge_line_strip;
}

void SdaiCubic_bezier_tessellated_edge::tessellated_edge_line_strip_( const IntAggregate_ptr x ) {
    if( !_tessellated_edge_line_strip ) {
        _tessellated_edge_line_strip = new IntAggregate;
    }
    _tessellated_edge_line_strip->ShallowCopy( * x );
}

void init_SdaiCubic_bezier_tessellated_edge( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_tessellated_edge);
    ap242_managed_model_based_3d_engineering_mim_lf::e_tessellated_edge->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge);
        ListTypeDescriptor * t_428 = new ListTypeDescriptor;
        t_428->AssignAggrCreator((AggregateCreator) create_IntAggregate);        // Creator function
        t_428->SetBound1( 4 );
        t_428->SetBound2( 2147483647 );
        t_428->FundamentalType(LIST_TYPE);
        t_428->Description("LIST [4:?] OF INTEGER");
        t_428->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_428->ReferentType(t_sdaiINTEGER);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_428);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1826Rtessellated_edge_line_strip =
          new AttrDescriptor("tessellated_edge.line_strip",t_428,LFalse,LFalse, AttrType_Redefining,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge);
        ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1826Rtessellated_edge_line_strip);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_cubic_bezier_tessellated_edge );
}

#endif
