#ifndef  ENTITY_SDAIPRODUCT_GROUP_RELATIONSHIP_H
#define  ENTITY_SDAIPRODUCT_GROUP_RELATIONSHIP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiProduct_group_relationship : public SdaiGroup_relationship {
     protected:
    public: 
        SdaiProduct_group_relationship();
        SdaiProduct_group_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiProduct_group_relationship( SdaiProduct_group_relationship & e );
        ~SdaiProduct_group_relationship();
        int opcode() {
            return 1791;
        }
};

inline SdaiProduct_group_relationship * create_SdaiProduct_group_relationship() {
    return new SdaiProduct_group_relationship;
}

void init_SdaiProduct_group_relationship(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_product_group_relationship;
}

#endif
