#ifndef  ENTITY_SDAITIME_INTERVAL_ASSIGNMENT_CC
#define  ENTITY_SDAITIME_INTERVAL_ASSIGNMENT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiTime_interval_assignment.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_770assigned_time_interval = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_771role = 0;

SdaiTime_interval_assignment::SdaiTime_interval_assignment() : _assigned_time_interval( 0 ), _role( 0 ) {
        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_770assigned_time_interval, ( SDAI_Application_instance_ptr * ) & _assigned_time_interval );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_771role, ( SDAI_Application_instance_ptr * ) & _role );
    a->set_null();
    attributes.push( a );
}

SdaiTime_interval_assignment::SdaiTime_interval_assignment ( SdaiTime_interval_assignment & e ) : SDAI_Application_instance() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiTime_interval_assignment::~SdaiTime_interval_assignment() {
}

SdaiTime_interval_assignment::SdaiTime_interval_assignment( SDAI_Application_instance * se, bool addAttrs ) : _assigned_time_interval( 0 ), _role( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
    ( void ) addAttrs; /* quell potentially unused var */

        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_770assigned_time_interval, ( SDAI_Application_instance_ptr * ) &_assigned_time_interval );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_771role, ( SDAI_Application_instance_ptr * ) &_role );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiTime_interval_ptr SdaiTime_interval_assignment::assigned_time_interval_() {
    if( !_assigned_time_interval ) {
        _assigned_time_interval = new SdaiTime_interval;
    }
    return (SdaiTime_interval_ptr) _assigned_time_interval;
}

SdaiTime_interval_ptr_c SdaiTime_interval_assignment::assigned_time_interval_() const {
    return (SdaiTime_interval_ptr) _assigned_time_interval;
}

void SdaiTime_interval_assignment::assigned_time_interval_( const SdaiTime_interval_ptr x ) {
    _assigned_time_interval = x;
}

SdaiTime_interval_role_ptr SdaiTime_interval_assignment::role_() {
    if( !_role ) {
        _role = new SdaiTime_interval_role;
    }
    return (SdaiTime_interval_role_ptr) _role;
}

SdaiTime_interval_role_ptr_c SdaiTime_interval_assignment::role_() const {
    return (SdaiTime_interval_role_ptr) _role;
}

void SdaiTime_interval_assignment::role_( const SdaiTime_interval_role_ptr x ) {
    _role = x;
}

void init_SdaiTime_interval_assignment( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment->AddSupertype_Stmt( "ABSTRACT SUPERTYPE" );
    ap242_managed_model_based_3d_engineering_mim_lf::a_770assigned_time_interval =
      new AttrDescriptor( "assigned_time_interval", ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_770assigned_time_interval);
    ap242_managed_model_based_3d_engineering_mim_lf::a_771role =
      new AttrDescriptor( "role", ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_role, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_771role);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_time_interval_assignment );
}

#endif
