#ifndef  ENTITY_SDAIROW_VALUE_H
#define  ENTITY_SDAIROW_VALUE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRow_value : public SdaiCompound_representation_item {
     protected:
    public: 
        SdaiRow_value();
        SdaiRow_value( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRow_value( SdaiRow_value & e );
        ~SdaiRow_value();
        int opcode() {
            return 285;
        }
};

inline SdaiRow_value * create_SdaiRow_value() {
    return new SdaiRow_value;
}

void init_SdaiRow_value(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_row_value;
}

#endif
