#ifndef  ENTITY_SDAIENTITY_ASSERTION_H
#define  ENTITY_SDAIENTITY_ASSERTION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiEntity_assertion : public SdaiFact_type {
     protected:
    public: 
        SdaiEntity_assertion();
        SdaiEntity_assertion( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiEntity_assertion( SdaiEntity_assertion & e );
        ~SdaiEntity_assertion();
        int opcode() {
            return 1414;
        }
};

inline SdaiEntity_assertion * create_SdaiEntity_assertion() {
    return new SdaiEntity_assertion;
}

void init_SdaiEntity_assertion(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_entity_assertion;
}

#endif
