#ifndef  ENTITY_SDAILAMINATE_TABLE_CC
#define  ENTITY_SDAILAMINATE_TABLE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiLaminate_table.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table = 0;

SdaiLaminate_table::SdaiLaminate_table(): SdaiProduct_definition() {
        /*  parent: SdaiProduct_definition  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table;
    MakeDerived( "name", "product_definition" );
}

SdaiLaminate_table::SdaiLaminate_table ( SdaiLaminate_table & e ) : SdaiProduct_definition() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiLaminate_table::~SdaiLaminate_table() {
}

SdaiLaminate_table::SdaiLaminate_table( SDAI_Application_instance * se, bool addAttrs ) : SdaiProduct_definition( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiProduct_definition */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table;
    MakeDerived( "name", "product_definition" );
}


void init_SdaiLaminate_table( Registry& reg ) {
    std::string str;

    str.clear();
    str.append( "SUPERTYPE OF ( " );
    str.append( "ONEOF ( part_laminate_table, zone_structural_makeup )\n" );
    str.append( ")" );
    ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table->AddSupertype_Stmt( str );
    ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_product_definition);
    ap242_managed_model_based_3d_engineering_mim_lf::e_product_definition->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_laminate_table );
}

#endif
