#ifndef  ENTITY_SDAICAMERA_MODEL_D3_MULTI_CLIPPING_INTERSECTION_CC
#define  ENTITY_SDAICAMERA_MODEL_D3_MULTI_CLIPPING_INTERSECTION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiCamera_model_d3_multi_clipping_intersection.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2279shape_clipping = 0;

SdaiCamera_model_d3_multi_clipping_intersection::SdaiCamera_model_d3_multi_clipping_intersection(): SdaiGeometric_representation_item(), _shape_clipping( 0 ) {
        /*  parent: SdaiGeometric_representation_item  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection;
    _shape_clipping = new SdaiCamera_model_d3_multi_clipping_intersection_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2279shape_clipping, _shape_clipping );
    a->set_null();
    attributes.push( a );
    MakeDerived( "dim", "geometric_representation_item" );
}

SdaiCamera_model_d3_multi_clipping_intersection::SdaiCamera_model_d3_multi_clipping_intersection ( SdaiCamera_model_d3_multi_clipping_intersection & e ) : SdaiGeometric_representation_item() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiCamera_model_d3_multi_clipping_intersection::~SdaiCamera_model_d3_multi_clipping_intersection() {
    delete _shape_clipping;
}

SdaiCamera_model_d3_multi_clipping_intersection::SdaiCamera_model_d3_multi_clipping_intersection( SDAI_Application_instance * se, bool addAttrs ) : SdaiGeometric_representation_item( se, addAttrs ), _shape_clipping( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiGeometric_representation_item */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection;
    _shape_clipping = new SdaiCamera_model_d3_multi_clipping_intersection_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2279shape_clipping,  _shape_clipping );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "dim", "geometric_representation_item" );
}


SdaiCamera_model_d3_multi_clipping_intersection_select_agg_ptr SdaiCamera_model_d3_multi_clipping_intersection::shape_clipping_() {
    if( !_shape_clipping ) {
        _shape_clipping = new SdaiCamera_model_d3_multi_clipping_intersection_select_agg;
    }
    return ( SdaiCamera_model_d3_multi_clipping_intersection_select_agg_ptr ) _shape_clipping;
}

SdaiCamera_model_d3_multi_clipping_intersection_select_agg_ptr_c SdaiCamera_model_d3_multi_clipping_intersection::shape_clipping_() const {
    return ( SdaiCamera_model_d3_multi_clipping_intersection_select_agg_ptr ) _shape_clipping;
}

void SdaiCamera_model_d3_multi_clipping_intersection::shape_clipping_( const SdaiCamera_model_d3_multi_clipping_intersection_select_agg_ptr x ) {
    if( !_shape_clipping ) {
        _shape_clipping = new SdaiCamera_model_d3_multi_clipping_intersection_select_agg;
    }
    _shape_clipping->ShallowCopy( * x );
}

void init_SdaiCamera_model_d3_multi_clipping_intersection( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_geometric_representation_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_geometric_representation_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection);
        SetTypeDescriptor * t_530 = new SetTypeDescriptor;
        t_530->AssignAggrCreator((AggregateCreator) create_SdaiCamera_model_d3_multi_clipping_intersection_select_agg);        // Creator function
        t_530->SetBound1( 2 );
        t_530->SetBound2( 2147483647 );
        t_530->FundamentalType(SET_TYPE);
        t_530->Description("SET [2:?] OF camera_model_d3_multi_clipping_intersection_select");
        t_530->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_530->ReferentType(ap242_managed_model_based_3d_engineering_mim_lf::t_camera_model_d3_multi_clipping_intersection_select);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_530);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2279shape_clipping =
          new AttrDescriptor("shape_clipping",t_530,LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection);
        ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2279shape_clipping);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_camera_model_d3_multi_clipping_intersection );
}

#endif
