#ifndef  ENTITY_SDAIAPPLIED_DOCUMENT_USAGE_CONSTRAINT_ASSIGNMENT_CC
#define  ENTITY_SDAIAPPLIED_DOCUMENT_USAGE_CONSTRAINT_ASSIGNMENT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiApplied_document_usage_constraint_assignment.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1898items = 0;

SdaiApplied_document_usage_constraint_assignment::SdaiApplied_document_usage_constraint_assignment(): SdaiDocument_usage_constraint_assignment(), _items( 0 ) {
        /*  parent: SdaiDocument_usage_constraint_assignment  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment;
    _items = new SdaiDocument_reference_item_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1898items, _items );
    a->set_null();
    attributes.push( a );
}

SdaiApplied_document_usage_constraint_assignment::SdaiApplied_document_usage_constraint_assignment ( SdaiApplied_document_usage_constraint_assignment & e ) : SdaiDocument_usage_constraint_assignment() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiApplied_document_usage_constraint_assignment::~SdaiApplied_document_usage_constraint_assignment() {
    delete _items;
}

SdaiApplied_document_usage_constraint_assignment::SdaiApplied_document_usage_constraint_assignment( SDAI_Application_instance * se, bool addAttrs ) : SdaiDocument_usage_constraint_assignment( se, addAttrs ), _items( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiDocument_usage_constraint_assignment */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment;
    _items = new SdaiDocument_reference_item_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1898items,  _items );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiDocument_reference_item_agg_ptr SdaiApplied_document_usage_constraint_assignment::items_() {
    if( !_items ) {
        _items = new SdaiDocument_reference_item_agg;
    }
    return ( SdaiDocument_reference_item_agg_ptr ) _items;
}

SdaiDocument_reference_item_agg_ptr_c SdaiApplied_document_usage_constraint_assignment::items_() const {
    return ( SdaiDocument_reference_item_agg_ptr ) _items;
}

void SdaiApplied_document_usage_constraint_assignment::items_( const SdaiDocument_reference_item_agg_ptr x ) {
    if( !_items ) {
        _items = new SdaiDocument_reference_item_agg;
    }
    _items->ShallowCopy( * x );
}

void init_SdaiApplied_document_usage_constraint_assignment( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_document_usage_constraint_assignment);
    ap242_managed_model_based_3d_engineering_mim_lf::e_document_usage_constraint_assignment->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment);
        SetTypeDescriptor * t_437 = new SetTypeDescriptor;
        t_437->AssignAggrCreator((AggregateCreator) create_SdaiDocument_reference_item_agg);        // Creator function
        t_437->SetBound1( 1 );
        t_437->SetBound2( 2147483647 );
        t_437->FundamentalType(SET_TYPE);
        t_437->Description("SET [1:?] OF document_reference_item");
        t_437->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_437->ReferentType(ap242_managed_model_based_3d_engineering_mim_lf::t_document_reference_item);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_437);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1898items =
          new AttrDescriptor("items",t_437,LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1898items);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_applied_document_usage_constraint_assignment );
}

#endif
