#ifndef  ENTITY_SDAIA3M_EQUIVALENCE_CRITERION_OF_DETAILED_ASSEMBLY_DATA_CONTENT_H
#define  ENTITY_SDAIA3M_EQUIVALENCE_CRITERION_OF_DETAILED_ASSEMBLY_DATA_CONTENT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content : public SdaiA3m_equivalence_criterion_for_assembly {
     protected:
    public: 
        SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content();
        SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content( SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content & e );
        ~SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content();
        int opcode() {
            return 355;
        }
};

inline SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content * create_SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content() {
    return new SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content;
}

void init_SdaiA3m_equivalence_criterion_of_detailed_assembly_data_content(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_a3m_equivalence_criterion_of_detailed_assembly_data_content;
    extern Derived_attribute *a_554Da3m_equivalence_criterion_comparing_element_types;
    extern Derived_attribute *a_555Da3m_equivalence_criterion_compared_element_types;
}

#endif
