#ifndef  ENTITY_SDAIPRODUCT_SPECIFICATION_H
#define  ENTITY_SDAIPRODUCT_SPECIFICATION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiProduct_specification : public SdaiProduct_identification {
     protected:
        EntityAggregate_ptr _item_concept_feature = NULL;          //  of  product_concept_feature_association

    public: 
        SdaiProduct_specification();
        SdaiProduct_specification( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiProduct_specification( SdaiProduct_specification & e );
        ~SdaiProduct_specification();
        int opcode() {
            return 1156;
        }
        EntityAggregate_ptr_c item_concept_feature_() const;
        EntityAggregate_ptr   item_concept_feature_();
        void item_concept_feature_( const EntityAggregate_ptr x );

};

inline SdaiProduct_specification * create_SdaiProduct_specification() {
    return new SdaiProduct_specification;
}

void init_SdaiProduct_specification(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_product_specification;
}

#endif
