#ifndef  ENTITY_SDAISURFACED_OPEN_SHELL_H
#define  ENTITY_SDAISURFACED_OPEN_SHELL_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSurfaced_open_shell : public SdaiOpen_shell {
     protected:
    public: 
        SdaiSurfaced_open_shell();
        SdaiSurfaced_open_shell( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSurfaced_open_shell( SdaiSurfaced_open_shell & e );
        ~SdaiSurfaced_open_shell();
        int opcode() {
            return 364;
        }
};

inline SdaiSurfaced_open_shell * create_SdaiSurfaced_open_shell() {
    return new SdaiSurfaced_open_shell;
}

void init_SdaiSurfaced_open_shell(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_surfaced_open_shell;
}

#endif
