#ifndef  ENTITY_SDAIINAPT_DATA_H
#define  ENTITY_SDAIINAPT_DATA_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiInapt_data : public SdaiShape_data_quality_criterion {
     protected:
    public: 
        SdaiInapt_data();
        SdaiInapt_data( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiInapt_data( SdaiInapt_data & e );
        ~SdaiInapt_data();
        int opcode() {
            return 30;
        }
};

inline SdaiInapt_data * create_SdaiInapt_data() {
    return new SdaiInapt_data;
}

void init_SdaiInapt_data(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_inapt_data;
}

#endif
