#ifndef  ENTITY_SDAIA3M_EQUIVALENCE_CRITERION_REPORT_ITEM_WITH_MEASURED_VALUE_CC
#define  ENTITY_SDAIA3M_EQUIVALENCE_CRITERION_REPORT_ITEM_WITH_MEASURED_VALUE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiA3m_equivalence_criterion_report_item_with_measured_value.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2102representative_measured_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2103value_type = 0;

SdaiA3m_equivalence_criterion_report_item_with_measured_value::SdaiA3m_equivalence_criterion_report_item_with_measured_value(): SdaiData_equivalence_inspection_criterion_report_item() {
        /*  parent: SdaiData_equivalence_inspection_criterion_report_item  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2102representative_measured_value, & _representative_measured_value );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2103value_type, & _value_type );
    a->set_null();
    attributes.push( a );
}

SdaiA3m_equivalence_criterion_report_item_with_measured_value::SdaiA3m_equivalence_criterion_report_item_with_measured_value ( SdaiA3m_equivalence_criterion_report_item_with_measured_value & e ) : SdaiData_equivalence_inspection_criterion_report_item() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiA3m_equivalence_criterion_report_item_with_measured_value::~SdaiA3m_equivalence_criterion_report_item_with_measured_value() {
}

SdaiA3m_equivalence_criterion_report_item_with_measured_value::SdaiA3m_equivalence_criterion_report_item_with_measured_value( SDAI_Application_instance * se, bool addAttrs ) : SdaiData_equivalence_inspection_criterion_report_item( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiData_equivalence_inspection_criterion_report_item */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2102representative_measured_value,  &_representative_measured_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2103value_type,  &_value_type );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiEquivalence_measured_value_select_ptr SdaiA3m_equivalence_criterion_report_item_with_measured_value::representative_measured_value_()  {
    return &_representative_measured_value;
}

SdaiEquivalence_measured_value_select_ptr_c SdaiA3m_equivalence_criterion_report_item_with_measured_value::representative_measured_value_() const {
    return (const SdaiEquivalence_measured_value_select_ptr) &_representative_measured_value;
}

void SdaiA3m_equivalence_criterion_report_item_with_measured_value::representative_measured_value_( const SdaiEquivalence_measured_value_select_ptr x )  {
    _representative_measured_value = x;
}

SdaiRepresentative_value_type_var SdaiA3m_equivalence_criterion_report_item_with_measured_value::value_type_() {
    return (Representative_value_type) _value_type;
}

const SdaiRepresentative_value_type_var SdaiA3m_equivalence_criterion_report_item_with_measured_value::value_type_() const {
    return (const Representative_value_type) _value_type;
}

void SdaiA3m_equivalence_criterion_report_item_with_measured_value::value_type_( const SdaiRepresentative_value_type_var x ) {
    _value_type.put( x );
}

void init_SdaiA3m_equivalence_criterion_report_item_with_measured_value( Registry& reg ) {
    std::string str;

        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value->_uniqueness_rules = new Uniqueness_rule__set;
        Uniqueness_rule * ur;
        str.clear();
    str.append( "UR1 : " );
    str.append( "SELF\\data_equivalence_inspection_criterion_report_item.criterion_report\n" );
    str.append( ", " );
    str.append( "value_type\n" );
    ur = new Uniqueness_rule( str.c_str() );
    ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value->_uniqueness_rules->Append(ur);
    ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_data_equivalence_inspection_criterion_report_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_data_equivalence_inspection_criterion_report_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2102representative_measured_value =
          new AttrDescriptor("representative_measured_value",ap242_managed_model_based_3d_engineering_mim_lf::t_equivalence_measured_value_select,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2102representative_measured_value);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2103value_type =
          new AttrDescriptor("value_type",ap242_managed_model_based_3d_engineering_mim_lf::t_representative_value_type,
          LFalse,LTrue, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2103value_type);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_equivalence_criterion_report_item_with_measured_value );
}

#endif
