#ifndef  ENTITY_SDAIBINARY_BOOLEAN_EXPRESSION_CC
#define  ENTITY_SDAIBINARY_BOOLEAN_EXPRESSION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiBinary_boolean_expression.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression = 0;

SdaiBinary_boolean_expression::SdaiBinary_boolean_expression(): SdaiBoolean_expression(), _operands( 0 ) {
        /*  parent: SdaiBoolean_expression  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */
        /*  parent: SdaiBinary_generic_expression  */
    HeadEntity(this);
    AppendMultInstance(new SdaiBinary_generic_expression(this));

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression;
}

SdaiBinary_boolean_expression::SdaiBinary_boolean_expression ( SdaiBinary_boolean_expression & e ) : SdaiBoolean_expression() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiBinary_boolean_expression::~SdaiBinary_boolean_expression() {
}

SdaiBinary_boolean_expression::SdaiBinary_boolean_expression( SDAI_Application_instance * se, bool addAttrs ) : SdaiBoolean_expression( se, addAttrs ), _operands( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiBoolean_expression */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */
        /* parent: SdaiBinary_generic_expression */
    se->AppendMultInstance( new SdaiBinary_generic_expression( se, addAttrs ) );

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression;
}


EntityAggregate_ptr SdaiBinary_boolean_expression::operands_() {
    if( !_operands ) {
        _operands = new EntityAggregate;
    }
    return ( EntityAggregate_ptr ) _operands;
}

EntityAggregate_ptr_c SdaiBinary_boolean_expression::operands_() const {
    return ( EntityAggregate_ptr ) _operands;
}

void SdaiBinary_boolean_expression::operands_( const EntityAggregate_ptr x ) {
    if( !_operands ) {
        _operands = new EntityAggregate;
    }
    _operands->ShallowCopy( * x );
}

void init_SdaiBinary_boolean_expression( Registry& reg ) {
    std::string str;

    str.clear();
    str.append( "ABSTRACT SUPERTYPE OF ( " );
    str.append( "ONEOF ( xor_expression, equals_expression )\n" );
    str.append( ")" );
    ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression->AddSupertype_Stmt( str );
    ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_boolean_expression);
    ap242_managed_model_based_3d_engineering_mim_lf::e_boolean_expression->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression);
    ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_binary_generic_expression);
    ap242_managed_model_based_3d_engineering_mim_lf::e_binary_generic_expression->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_binary_boolean_expression );
}

#endif
