#ifndef  ENTITY_SDAILINEARIZED_TABLE_FUNCTION_H
#define  ENTITY_SDAILINEARIZED_TABLE_FUNCTION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiLinearized_table_function : public SdaiExplicit_table_function {
     protected:
        SDAI_Application_instance_ptr _unary_generic_expression_operand = NULL;
        SDAI_Integer _first = 0;
    public: 
        SdaiLinearized_table_function();
        SdaiLinearized_table_function( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiLinearized_table_function( SdaiLinearized_table_function & e );
        ~SdaiLinearized_table_function();
        int opcode() {
            return 70;
        }
        SdaiMaths_function_ptr_c unary_generic_expression_operand_() const;
        SdaiMaths_function_ptr   unary_generic_expression_operand_();
        void unary_generic_expression_operand_( const SdaiMaths_function_ptr x );

        SDAI_Integer   first_() const;
        void first_( const SDAI_Integer x );

};

inline SdaiLinearized_table_function * create_SdaiLinearized_table_function() {
    return new SdaiLinearized_table_function;
}

void init_SdaiLinearized_table_function(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_linearized_table_function;
    extern AttrDescriptor *a_115Runary_generic_expression_operand;
    extern AttrDescriptor *a_116first;
    extern Derived_attribute *a_117Dsource;
}

#endif
