#ifndef  ENTITY_SDAITSDQ_POSITIVE_LENGTH_MEASURE_FOR_TRIANGLE_EDGE_IN_FREE_EDGE_LOOP_H
#define  ENTITY_SDAITSDQ_POSITIVE_LENGTH_MEASURE_FOR_TRIANGLE_EDGE_IN_FREE_EDGE_LOOP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop : public SdaiA3m_data_quality_criterion_specific_applied_value {
     protected:
        SDAI_Application_instance_ptr _a3m_data_quality_criterion_specific_applied_value_criterion_to_assign_the_value = NULL;
        SDAI_Real _a3m_data_quality_criterion_specific_applied_value_applied_value = 0.0;
    public: 
        SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop();
        SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop( SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop & e );
        ~SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop();
        int opcode() {
            return 2280;
        }
        SdaiTriangle_edge_in_free_edge_loop_ptr_c a3m_data_quality_criterion_specific_applied_value_criterion_to_assign_the_value_() const;
        SdaiTriangle_edge_in_free_edge_loop_ptr   a3m_data_quality_criterion_specific_applied_value_criterion_to_assign_the_value_();
        void a3m_data_quality_criterion_specific_applied_value_criterion_to_assign_the_value_( const SdaiTriangle_edge_in_free_edge_loop_ptr x );

        SdaiPositive_length_measure   a3m_data_quality_criterion_specific_applied_value_applied_value_() const;
        void a3m_data_quality_criterion_specific_applied_value_applied_value_( const SdaiPositive_length_measure x );

};

inline SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop * create_SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop() {
    return new SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop;
}

void init_SdaiTsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_tsdq_positive_length_measure_for_triangle_edge_in_free_edge_loop;
    extern AttrDescriptor *a_3373Ra3m_data_quality_criterion_specific_applied_value_criterion_to_assign_the_value;
    extern AttrDescriptor *a_3374Ra3m_data_quality_criterion_specific_applied_value_applied_value;
}

#endif
