#ifndef  ENTITY_SDAIALL_AROUND_SHAPE_ASPECT_CC
#define  ENTITY_SDAIALL_AROUND_SHAPE_ASPECT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiAll_around_shape_aspect.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect = 0;

SdaiAll_around_shape_aspect::SdaiAll_around_shape_aspect(): SdaiContinuous_shape_aspect() {
        /*  parent: SdaiContinuous_shape_aspect  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect;
    MakeDerived( "id", "shape_aspect" );
}

SdaiAll_around_shape_aspect::SdaiAll_around_shape_aspect ( SdaiAll_around_shape_aspect & e ) : SdaiContinuous_shape_aspect() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiAll_around_shape_aspect::~SdaiAll_around_shape_aspect() {
}

SdaiAll_around_shape_aspect::SdaiAll_around_shape_aspect( SDAI_Application_instance * se, bool addAttrs ) : SdaiContinuous_shape_aspect( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiContinuous_shape_aspect */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect;
    MakeDerived( "id", "shape_aspect" );
}


void init_SdaiAll_around_shape_aspect( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_continuous_shape_aspect);
    ap242_managed_model_based_3d_engineering_mim_lf::e_continuous_shape_aspect->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_all_around_shape_aspect );
}

#endif
