#ifndef  ENTITY_SDAIAPPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT_H
#define  ENTITY_SDAIAPPLIED_PERSON_AND_ORGANIZATION_ASSIGNMENT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiApplied_person_and_organization_assignment : public SdaiPerson_and_organization_assignment {
     protected:
        SdaiPerson_and_organization_item_agg_ptr _items = NULL;          //  of  person_and_organization_item

    public: 
        SdaiApplied_person_and_organization_assignment();
        SdaiApplied_person_and_organization_assignment( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiApplied_person_and_organization_assignment( SdaiApplied_person_and_organization_assignment & e );
        ~SdaiApplied_person_and_organization_assignment();
        int opcode() {
            return 2244;
        }
        SdaiPerson_and_organization_item_agg_ptr_c items_() const;
        SdaiPerson_and_organization_item_agg_ptr   items_();
        void items_( const SdaiPerson_and_organization_item_agg_ptr x );

};

inline SdaiApplied_person_and_organization_assignment * create_SdaiApplied_person_and_organization_assignment() {
    return new SdaiApplied_person_and_organization_assignment;
}

void init_SdaiApplied_person_and_organization_assignment(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_applied_person_and_organization_assignment;
    extern AttrDescriptor *a_3314items;
}

#endif
