#ifndef  ENTITY_SDAICSG_PRIMITIVE_SOLID_2D_CC
#define  ENTITY_SDAICSG_PRIMITIVE_SOLID_2D_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiCsg_primitive_solid_2d.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_84Rcsg_solid_tree_root_expression = 0;

SdaiCsg_primitive_solid_2d::SdaiCsg_primitive_solid_2d(): SdaiCsg_solid_2d() {
        /*  parent: SdaiCsg_solid_2d  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_84Rcsg_solid_tree_root_expression, & _csg_solid_tree_root_expression );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "tree_root_expression" );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "tree_root_expression", "csg_solid" );
}

SdaiCsg_primitive_solid_2d::SdaiCsg_primitive_solid_2d ( SdaiCsg_primitive_solid_2d & e ) : SdaiCsg_solid_2d() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiCsg_primitive_solid_2d::~SdaiCsg_primitive_solid_2d() {
}

SdaiCsg_primitive_solid_2d::SdaiCsg_primitive_solid_2d( SDAI_Application_instance * se, bool addAttrs ) : SdaiCsg_solid_2d( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiCsg_solid_2d */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_84Rcsg_solid_tree_root_expression,  &_csg_solid_tree_root_expression );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "tree_root_expression" );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "tree_root_expression", "csg_solid" );
}


SdaiBounded_primitive_2d_ptr SdaiCsg_primitive_solid_2d::csg_solid_tree_root_expression_()  {
    return &_csg_solid_tree_root_expression;
}

SdaiBounded_primitive_2d_ptr_c SdaiCsg_primitive_solid_2d::csg_solid_tree_root_expression_() const {
    return (const SdaiBounded_primitive_2d_ptr) &_csg_solid_tree_root_expression;
}

void SdaiCsg_primitive_solid_2d::csg_solid_tree_root_expression_( const SdaiBounded_primitive_2d_ptr x )  {
    _csg_solid_tree_root_expression = x;
}

void init_SdaiCsg_primitive_solid_2d( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_csg_solid_2d);
    ap242_managed_model_based_3d_engineering_mim_lf::e_csg_solid_2d->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d);
        ap242_managed_model_based_3d_engineering_mim_lf::a_84Rcsg_solid_tree_root_expression =
          new AttrDescriptor("csg_solid.tree_root_expression",ap242_managed_model_based_3d_engineering_mim_lf::t_bounded_primitive_2d,
          LFalse,LFalse, AttrType_Redefining,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d);
        ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_84Rcsg_solid_tree_root_expression);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_csg_primitive_solid_2d );
}

#endif
