#ifndef  ENTITY_SDAISHAPE_FEATURE_FIT_RELATIONSHIP_H
#define  ENTITY_SDAISHAPE_FEATURE_FIT_RELATIONSHIP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiShape_feature_fit_relationship : public SdaiShape_aspect_relationship {
     protected:
    public: 
        SdaiShape_feature_fit_relationship();
        SdaiShape_feature_fit_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiShape_feature_fit_relationship( SdaiShape_feature_fit_relationship & e );
        ~SdaiShape_feature_fit_relationship();
        int opcode() {
            return 1686;
        }
};

inline SdaiShape_feature_fit_relationship * create_SdaiShape_feature_fit_relationship() {
    return new SdaiShape_feature_fit_relationship;
}

void init_SdaiShape_feature_fit_relationship(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_shape_feature_fit_relationship;
    extern Derived_attribute *a_2501Dcharacterized_object_name;
    extern Derived_attribute *a_2502Dcharacterized_object_description;
}

#endif
