#ifndef  ENTITY_SDAIPLANAR_PAIR_VALUE_CC
#define  ENTITY_SDAIPLANAR_PAIR_VALUE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiPlanar_pair_value.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_3017Rpair_value_applies_to_pair = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_3018actual_rotation = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_3019actual_translation_x = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_3020actual_translation_y = 0;

SdaiPlanar_pair_value::SdaiPlanar_pair_value(): SdaiPair_value(), _pair_value_applies_to_pair( 0 ) {
        /*  parent: SdaiPair_value  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3017Rpair_value_applies_to_pair, ( SDAI_Application_instance_ptr * ) & _pair_value_applies_to_pair );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "applies_to_pair" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3018actual_rotation, & _actual_rotation );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3019actual_translation_x, & _actual_translation_x );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3020actual_translation_y, & _actual_translation_y );
    a->set_null();
    attributes.push( a );
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "applies_to_pair", "pair_value" );
}

SdaiPlanar_pair_value::SdaiPlanar_pair_value ( SdaiPlanar_pair_value & e ) : SdaiPair_value() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiPlanar_pair_value::~SdaiPlanar_pair_value() {
}

SdaiPlanar_pair_value::SdaiPlanar_pair_value( SDAI_Application_instance * se, bool addAttrs ) : SdaiPair_value( se, addAttrs ), _pair_value_applies_to_pair( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiPair_value */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3017Rpair_value_applies_to_pair, ( SDAI_Application_instance_ptr * ) &_pair_value_applies_to_pair );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "applies_to_pair" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3018actual_rotation,  &_actual_rotation );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3019actual_translation_x,  &_actual_translation_x );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_3020actual_translation_y,  &_actual_translation_y );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "dim", "geometric_representation_item" );
    MakeDerived( "applies_to_pair", "pair_value" );
}


SdaiPlanar_pair_ptr SdaiPlanar_pair_value::pair_value_applies_to_pair_() {
    if( !_pair_value_applies_to_pair ) {
        _pair_value_applies_to_pair = new SdaiPlanar_pair;
    }
    return (SdaiPlanar_pair_ptr) _pair_value_applies_to_pair;
}

SdaiPlanar_pair_ptr_c SdaiPlanar_pair_value::pair_value_applies_to_pair_() const {
    return (SdaiPlanar_pair_ptr) _pair_value_applies_to_pair;
}

void SdaiPlanar_pair_value::pair_value_applies_to_pair_( const SdaiPlanar_pair_ptr x ) {
    _pair_value_applies_to_pair = x;
}

SdaiPlane_angle_measure SdaiPlanar_pair_value::actual_rotation_() const {
    return (SdaiPlane_angle_measure) _actual_rotation;
}

void SdaiPlanar_pair_value::actual_rotation_( const SdaiPlane_angle_measure x ) {
    _actual_rotation = x;
}

SdaiLength_measure SdaiPlanar_pair_value::actual_translation_x_() const {
    return (SdaiLength_measure) _actual_translation_x;
}

void SdaiPlanar_pair_value::actual_translation_x_( const SdaiLength_measure x ) {
    _actual_translation_x = x;
}

SdaiLength_measure SdaiPlanar_pair_value::actual_translation_y_() const {
    return (SdaiLength_measure) _actual_translation_y;
}

void SdaiPlanar_pair_value::actual_translation_y_( const SdaiLength_measure x ) {
    _actual_translation_y = x;
}

void init_SdaiPlanar_pair_value( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_pair_value);
    ap242_managed_model_based_3d_engineering_mim_lf::e_pair_value->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value);
    ap242_managed_model_based_3d_engineering_mim_lf::a_3017Rpair_value_applies_to_pair =
      new AttrDescriptor( "pair_value.applies_to_pair", ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair, LFalse,
       LFalse, AttrType_Redefining, *ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_3017Rpair_value_applies_to_pair);
        ap242_managed_model_based_3d_engineering_mim_lf::a_3018actual_rotation =
          new AttrDescriptor("actual_rotation",ap242_managed_model_based_3d_engineering_mim_lf::t_plane_angle_measure,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_3018actual_rotation);
        ap242_managed_model_based_3d_engineering_mim_lf::a_3019actual_translation_x =
          new AttrDescriptor("actual_translation_x",ap242_managed_model_based_3d_engineering_mim_lf::t_length_measure,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_3019actual_translation_x);
        ap242_managed_model_based_3d_engineering_mim_lf::a_3020actual_translation_y =
          new AttrDescriptor("actual_translation_y",ap242_managed_model_based_3d_engineering_mim_lf::t_length_measure,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value);
        ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_3020actual_translation_y);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_planar_pair_value );
}

#endif
