#ifndef  ENTITY_SDAIALTERNATE_PRODUCT_RELATIONSHIP_H
#define  ENTITY_SDAIALTERNATE_PRODUCT_RELATIONSHIP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAlternate_product_relationship : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
        SDAI_String _definition;    //  OPTIONAL
        SDAI_Application_instance_ptr _alternate = NULL;
        SDAI_Application_instance_ptr _base = NULL;
        SDAI_String _basis;
    public: 
        SdaiAlternate_product_relationship();
        SdaiAlternate_product_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAlternate_product_relationship( SdaiAlternate_product_relationship & e );
        ~SdaiAlternate_product_relationship();
        int opcode() {
            return 2148;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiText   definition_() const;
        SdaiText   definition_();
        void definition_( const SdaiText x );

        SdaiProduct_ptr_c alternate_() const;
        SdaiProduct_ptr   alternate_();
        void alternate_( const SdaiProduct_ptr x );

        SdaiProduct_ptr_c base_() const;
        SdaiProduct_ptr   base_();
        void base_( const SdaiProduct_ptr x );

  const SdaiText   basis_() const;
        SdaiText   basis_();
        void basis_( const SdaiText x );

};

inline SdaiAlternate_product_relationship * create_SdaiAlternate_product_relationship() {
    return new SdaiAlternate_product_relationship;
}

void init_SdaiAlternate_product_relationship(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_alternate_product_relationship;
    extern AttrDescriptor *a_3156name;
    extern AttrDescriptor *a_3157definition;
    extern AttrDescriptor *a_3158alternate;
    extern AttrDescriptor *a_3159base;
    extern AttrDescriptor *a_3160basis;
}

#endif
