#ifndef  ENTITY_SDAIPHYSICAL_COMPONENT_TERMINAL_H
#define  ENTITY_SDAIPHYSICAL_COMPONENT_TERMINAL_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiPhysical_component_terminal : public SdaiComponent_terminal {
     protected:
    public: 
        SdaiPhysical_component_terminal();
        SdaiPhysical_component_terminal( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiPhysical_component_terminal( SdaiPhysical_component_terminal & e );
        ~SdaiPhysical_component_terminal();
        int opcode() {
            return 1211;
        }
};

inline SdaiPhysical_component_terminal * create_SdaiPhysical_component_terminal() {
    return new SdaiPhysical_component_terminal;
}

void init_SdaiPhysical_component_terminal(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_physical_component_terminal;
}

#endif
