#ifndef  ENTITY_SDAISIMPLIFIED_COUNTERBORE_HOLE_DEFINITION_CC
#define  ENTITY_SDAISIMPLIFIED_COUNTERBORE_HOLE_DEFINITION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiSimplified_counterbore_hole_definition.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition = 0;

SdaiSimplified_counterbore_hole_definition::SdaiSimplified_counterbore_hole_definition(): SdaiCounterbore_hole_definition() {
        /*  parent: SdaiCounterbore_hole_definition  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition;
}

SdaiSimplified_counterbore_hole_definition::SdaiSimplified_counterbore_hole_definition ( SdaiSimplified_counterbore_hole_definition & e ) : SdaiCounterbore_hole_definition() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiSimplified_counterbore_hole_definition::~SdaiSimplified_counterbore_hole_definition() {
}

SdaiSimplified_counterbore_hole_definition::SdaiSimplified_counterbore_hole_definition( SDAI_Application_instance * se, bool addAttrs ) : SdaiCounterbore_hole_definition( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiCounterbore_hole_definition */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition;
}


void init_SdaiSimplified_counterbore_hole_definition( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "SIZEOF( SELF\\explicit_composite_hole.placement\\representation.items ) = 1\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition->_where_rules->Append( wr );
    ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_counterbore_hole_definition);
    ap242_managed_model_based_3d_engineering_mim_lf::e_counterbore_hole_definition->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_simplified_counterbore_hole_definition );
}

#endif
