#ifndef  ENTITY_SDAISTATECHAR_OBJECT_H
#define  ENTITY_SDAISTATECHAR_OBJECT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiStatechar_object : public SdaiCharacterized_object {
     protected:
    public: 
        SdaiStatechar_object();
        SdaiStatechar_object( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiStatechar_object( SdaiStatechar_object & e );
        ~SdaiStatechar_object();
        int opcode() {
            return 1006;
        }
};

inline SdaiStatechar_object * create_SdaiStatechar_object() {
    return new SdaiStatechar_object;
}

void init_SdaiStatechar_object(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_statechar_object;
}

#endif
