#ifndef  ENTITY_SDAISURFACE_CURVE_SWEPT_AREA_SOLID_CC
#define  ENTITY_SDAISURFACE_CURVE_SWEPT_AREA_SOLID_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiSurface_curve_swept_area_solid.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1263directrix = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1264start_param = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1265end_param = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1266reference_surface = 0;

SdaiSurface_curve_swept_area_solid::SdaiSurface_curve_swept_area_solid(): SdaiSwept_area_solid(), _directrix( 0 ), _reference_surface( 0 ) {
        /*  parent: SdaiSwept_area_solid  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1263directrix, ( SDAI_Application_instance_ptr * ) & _directrix );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1264start_param, & _start_param );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1265end_param, & _end_param );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1266reference_surface, ( SDAI_Application_instance_ptr * ) & _reference_surface );
    a->set_null();
    attributes.push( a );
    MakeDerived( "dim", "geometric_representation_item" );
}

SdaiSurface_curve_swept_area_solid::SdaiSurface_curve_swept_area_solid ( SdaiSurface_curve_swept_area_solid & e ) : SdaiSwept_area_solid() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiSurface_curve_swept_area_solid::~SdaiSurface_curve_swept_area_solid() {
}

SdaiSurface_curve_swept_area_solid::SdaiSurface_curve_swept_area_solid( SDAI_Application_instance * se, bool addAttrs ) : SdaiSwept_area_solid( se, addAttrs ), _directrix( 0 ), _reference_surface( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiSwept_area_solid */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1263directrix, ( SDAI_Application_instance_ptr * ) &_directrix );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1264start_param,  &_start_param );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1265end_param,  &_end_param );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1266reference_surface, ( SDAI_Application_instance_ptr * ) &_reference_surface );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "dim", "geometric_representation_item" );
}


SdaiCurve_ptr SdaiSurface_curve_swept_area_solid::directrix_() {
    if( !_directrix ) {
        _directrix = new SdaiCurve;
    }
    return (SdaiCurve_ptr) _directrix;
}

SdaiCurve_ptr_c SdaiSurface_curve_swept_area_solid::directrix_() const {
    return (SdaiCurve_ptr) _directrix;
}

void SdaiSurface_curve_swept_area_solid::directrix_( const SdaiCurve_ptr x ) {
    _directrix = x;
}

SDAI_Real SdaiSurface_curve_swept_area_solid::start_param_() const {
    return (SDAI_Real) _start_param;
}

void SdaiSurface_curve_swept_area_solid::start_param_( const SDAI_Real x ) {
    _start_param = x;
}

SDAI_Real SdaiSurface_curve_swept_area_solid::end_param_() const {
    return (SDAI_Real) _end_param;
}

void SdaiSurface_curve_swept_area_solid::end_param_( const SDAI_Real x ) {
    _end_param = x;
}

SdaiSurface_ptr SdaiSurface_curve_swept_area_solid::reference_surface_() {
    if( !_reference_surface ) {
        _reference_surface = new SdaiSurface;
    }
    return (SdaiSurface_ptr) _reference_surface;
}

SdaiSurface_ptr_c SdaiSurface_curve_swept_area_solid::reference_surface_() const {
    return (SdaiSurface_ptr) _reference_surface;
}

void SdaiSurface_curve_swept_area_solid::reference_surface_( const SdaiSurface_ptr x ) {
    _reference_surface = x;
}

void init_SdaiSurface_curve_swept_area_solid( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SURFACE_CURVE' IN TYPEOF( directrix ) ) ) OR ( reference_surface IN \n" );
    str.append( "        directrix\\surface_curve.basis_surface )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->_where_rules->Append( wr );
    ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_swept_area_solid);
    ap242_managed_model_based_3d_engineering_mim_lf::e_swept_area_solid->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid);
    ap242_managed_model_based_3d_engineering_mim_lf::a_1263directrix =
      new AttrDescriptor( "directrix", ap242_managed_model_based_3d_engineering_mim_lf::e_curve, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid);
        ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1263directrix);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1264start_param =
          new AttrDescriptor("start_param",t_sdaiREAL,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid);
        ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1264start_param);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1265end_param =
          new AttrDescriptor("end_param",t_sdaiREAL,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid);
        ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1265end_param);
    ap242_managed_model_based_3d_engineering_mim_lf::a_1266reference_surface =
      new AttrDescriptor( "reference_surface", ap242_managed_model_based_3d_engineering_mim_lf::e_surface, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid);
        ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1266reference_surface);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_surface_curve_swept_area_solid );
}

#endif
