#ifndef  ENTITY_SDAIRECTANGULAR_ARRAY_PLACEMENT_GROUP_COMPONENT_H
#define  ENTITY_SDAIRECTANGULAR_ARRAY_PLACEMENT_GROUP_COMPONENT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRectangular_array_placement_group_component : public SdaiArray_placement_group {
     protected:
    public: 
        SdaiRectangular_array_placement_group_component();
        SdaiRectangular_array_placement_group_component( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRectangular_array_placement_group_component( SdaiRectangular_array_placement_group_component & e );
        ~SdaiRectangular_array_placement_group_component();
        int opcode() {
            return 1533;
        }
};

inline SdaiRectangular_array_placement_group_component * create_SdaiRectangular_array_placement_group_component() {
    return new SdaiRectangular_array_placement_group_component;
}

void init_SdaiRectangular_array_placement_group_component(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_rectangular_array_placement_group_component;
}

#endif
