#ifndef  ENTITY_SDAIEXTERNALLY_DEFINED_GENERAL_PROPERTY_CC
#define  ENTITY_SDAIEXTERNALLY_DEFINED_GENERAL_PROPERTY_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiExternally_defined_general_property.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property = 0;

SdaiExternally_defined_general_property::SdaiExternally_defined_general_property(): SdaiGeneral_property(), _source( 0 ) {
        /*  parent: SdaiGeneral_property  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */
        /*  parent: SdaiExternally_defined_item  */
    HeadEntity(this);
    AppendMultInstance(new SdaiExternally_defined_item(this));

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property;
}

SdaiExternally_defined_general_property::SdaiExternally_defined_general_property ( SdaiExternally_defined_general_property & e ) : SdaiGeneral_property() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiExternally_defined_general_property::~SdaiExternally_defined_general_property() {
}

SdaiExternally_defined_general_property::SdaiExternally_defined_general_property( SDAI_Application_instance * se, bool addAttrs ) : SdaiGeneral_property( se, addAttrs ), _source( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiGeneral_property */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */
        /* parent: SdaiExternally_defined_item */
    se->AppendMultInstance( new SdaiExternally_defined_item( se, addAttrs ) );

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property;
}


SdaiSource_item_ptr SdaiExternally_defined_general_property::item_id_()  {
    return &_item_id;
}

SdaiSource_item_ptr_c SdaiExternally_defined_general_property::item_id_() const {
    return (const SdaiSource_item_ptr) &_item_id;
}

void SdaiExternally_defined_general_property::item_id_( const SdaiSource_item_ptr x )  {
    _item_id = x;
}

SdaiExternal_source_ptr SdaiExternally_defined_general_property::source_() {
    if( !_source ) {
        _source = new SdaiExternal_source;
    }
    return (SdaiExternal_source_ptr) _source;
}

SdaiExternal_source_ptr_c SdaiExternally_defined_general_property::source_() const {
    return (SdaiExternal_source_ptr) _source;
}

void SdaiExternally_defined_general_property::source_( const SdaiExternal_source_ptr x ) {
    _source = x;
}

void init_SdaiExternally_defined_general_property( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_general_property);
    ap242_managed_model_based_3d_engineering_mim_lf::e_general_property->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property);
    ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_externally_defined_general_property );
}

#endif
