#ifndef  ENTITY_SDAICOUNTERDRILL_HOLE_OCCURRENCE_H
#define  ENTITY_SDAICOUNTERDRILL_HOLE_OCCURRENCE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiCounterdrill_hole_occurrence : public SdaiShape_aspect_occurrence {
     protected:
        SDAI_Application_instance_ptr _shape_aspect_occurrence_definition = NULL;
    public: 
        SdaiCounterdrill_hole_occurrence();
        SdaiCounterdrill_hole_occurrence( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiCounterdrill_hole_occurrence( SdaiCounterdrill_hole_occurrence & e );
        ~SdaiCounterdrill_hole_occurrence();
        int opcode() {
            return 889;
        }
        SdaiCounterdrill_hole_definition_ptr_c shape_aspect_occurrence_definition_() const;
        SdaiCounterdrill_hole_definition_ptr   shape_aspect_occurrence_definition_();
        void shape_aspect_occurrence_definition_( const SdaiCounterdrill_hole_definition_ptr x );

};

inline SdaiCounterdrill_hole_occurrence * create_SdaiCounterdrill_hole_occurrence() {
    return new SdaiCounterdrill_hole_occurrence;
}

void init_SdaiCounterdrill_hole_occurrence(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_counterdrill_hole_occurrence;
    extern AttrDescriptor *a_1323Rshape_aspect_occurrence_definition;
}

#endif
