#ifndef  ENTITY_SDAIRATIONAL_REPRESENTATION_ITEM_H
#define  ENTITY_SDAIRATIONAL_REPRESENTATION_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRational_representation_item : public SdaiRepresentation_item {
     protected:
        EntityAggregate_ptr _binary_generic_expression_operands = NULL;          //  of  numeric_expression

    public: 
        SdaiRational_representation_item();
        SdaiRational_representation_item( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRational_representation_item( SdaiRational_representation_item & e );
        ~SdaiRational_representation_item();
        int opcode() {
            return 723;
        }
        EntityAggregate_ptr_c binary_generic_expression_operands_() const;
        EntityAggregate_ptr   binary_generic_expression_operands_();
        void binary_generic_expression_operands_( const EntityAggregate_ptr x );

};

inline SdaiRational_representation_item * create_SdaiRational_representation_item() {
    return new SdaiRational_representation_item;
}

void init_SdaiRational_representation_item(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_rational_representation_item;
}

#endif
