#ifndef  ENTITY_SDAICONNECTION_DEFINITION_TO_CONNECTION_CC
#define  ENTITY_SDAICONNECTION_DEFINITION_TO_CONNECTION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiConnection_definition_to_connection.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection = 0;

SdaiConnection_definition_to_connection::SdaiConnection_definition_to_connection(): SdaiGroup() {
        /*  parent: SdaiGroup  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection;
    MakeDerived( "id", "group" );
}

SdaiConnection_definition_to_connection::SdaiConnection_definition_to_connection ( SdaiConnection_definition_to_connection & e ) : SdaiGroup() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiConnection_definition_to_connection::~SdaiConnection_definition_to_connection() {
}

SdaiConnection_definition_to_connection::SdaiConnection_definition_to_connection( SDAI_Application_instance * se, bool addAttrs ) : SdaiGroup( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiGroup */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection;
    MakeDerived( "id", "group" );
}


void init_SdaiConnection_definition_to_connection( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_group);
    ap242_managed_model_based_3d_engineering_mim_lf::e_group->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_connection_definition_to_connection );
}

#endif
