#ifndef  ENTITY_SDAIACTION_STATUS_H
#define  ENTITY_SDAIACTION_STATUS_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiAction_status : public SDAI_Application_instance {
    protected:
        SDAI_String _status;
        SDAI_Application_instance_ptr _assigned_action = NULL;
    public: 
        SdaiAction_status();
        SdaiAction_status( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiAction_status( SdaiAction_status & e );
        ~SdaiAction_status();
        int opcode() {
            return 320;
        }
  const SdaiLabel   status_() const;
        SdaiLabel   status_();
        void status_( const SdaiLabel x );

        SdaiExecuted_action_ptr_c assigned_action_() const;
        SdaiExecuted_action_ptr   assigned_action_();
        void assigned_action_( const SdaiExecuted_action_ptr x );

};

inline SdaiAction_status * create_SdaiAction_status() {
    return new SdaiAction_status;
}

void init_SdaiAction_status(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_action_status;
    extern AttrDescriptor *a_490status;
    extern AttrDescriptor *a_491assigned_action;
}

#endif
