#ifndef  ENTITY_SDAIRULE_CONDITION_H
#define  ENTITY_SDAIRULE_CONDITION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRule_condition : public SdaiAtomic_formula {
     protected:
    public: 
        SdaiRule_condition();
        SdaiRule_condition( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRule_condition( SdaiRule_condition & e );
        ~SdaiRule_condition();
        int opcode() {
            return 2045;
        }
};

inline SdaiRule_condition * create_SdaiRule_condition() {
    return new SdaiRule_condition;
}

void init_SdaiRule_condition(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_rule_condition;
}

#endif
