#ifndef  ENTITY_SDAINON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION_H
#define  ENTITY_SDAINON_MANIFOLD_SURFACE_SHAPE_REPRESENTATION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiNon_manifold_surface_shape_representation : public SdaiShape_representation {
     protected:
        SdaiNon_manifold_surface_shape_representation_select_agg_ptr _representation_items = NULL;          //  of  non_manifold_surface_shape_representation_select

    public: 
        SdaiNon_manifold_surface_shape_representation();
        SdaiNon_manifold_surface_shape_representation( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiNon_manifold_surface_shape_representation( SdaiNon_manifold_surface_shape_representation & e );
        ~SdaiNon_manifold_surface_shape_representation();
        int opcode() {
            return 1602;
        }
        SdaiNon_manifold_surface_shape_representation_select_agg_ptr_c representation_items_() const;
        SdaiNon_manifold_surface_shape_representation_select_agg_ptr   representation_items_();
        void representation_items_( const SdaiNon_manifold_surface_shape_representation_select_agg_ptr x );

};

inline SdaiNon_manifold_surface_shape_representation * create_SdaiNon_manifold_surface_shape_representation() {
    return new SdaiNon_manifold_surface_shape_representation;
}

void init_SdaiNon_manifold_surface_shape_representation(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_non_manifold_surface_shape_representation;
    extern AttrDescriptor *a_2375Rrepresentation_items;
}

#endif
