#ifndef  ENTITY_SDAISURFACE_PATCH_SET_H
#define  ENTITY_SDAISURFACE_PATCH_SET_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSurface_patch_set : public SdaiGeometric_representation_item {
     protected:
        EntityAggregate_ptr _patches = NULL;          //  of  surface_patch

    public: 
        SdaiSurface_patch_set();
        SdaiSurface_patch_set( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSurface_patch_set( SdaiSurface_patch_set & e );
        ~SdaiSurface_patch_set();
        int opcode() {
            return 248;
        }
        EntityAggregate_ptr_c patches_() const;
        EntityAggregate_ptr   patches_();
        void patches_( const EntityAggregate_ptr x );

};

inline SdaiSurface_patch_set * create_SdaiSurface_patch_set() {
    return new SdaiSurface_patch_set;
}

void init_SdaiSurface_patch_set(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_surface_patch_set;
    extern AttrDescriptor *a_400patches;
}

#endif
