#ifndef  ENTITY_SDAIGENERAL_MATERIAL_PROPERTY_CC
#define  ENTITY_SDAIGENERAL_MATERIAL_PROPERTY_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiGeneral_material_property.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property = 0;

SdaiGeneral_material_property::SdaiGeneral_material_property(): SdaiGeneral_property() {
        /*  parent: SdaiGeneral_property  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property;
}

SdaiGeneral_material_property::SdaiGeneral_material_property ( SdaiGeneral_material_property & e ) : SdaiGeneral_property() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiGeneral_material_property::~SdaiGeneral_material_property() {
}

SdaiGeneral_material_property::SdaiGeneral_material_property( SDAI_Application_instance * se, bool addAttrs ) : SdaiGeneral_property( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiGeneral_property */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property;
}


void init_SdaiGeneral_material_property( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "SIZEOF( QUERY ( gpa <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.GENERAL_PROPERTY_ASSOCIATION.'\n" );
    str.append( "        + 'BASE_DEFINITION'  ) | ( NOT ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.MATERIAL_PROPERTY' IN TYPEOF( gpa\\\n" );
    str.append( "        general_property_association.derived_definition ) ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property->_where_rules->Append( wr );
    ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_general_property);
    ap242_managed_model_based_3d_engineering_mim_lf::e_general_property->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_general_material_property );
}

#endif
