#ifndef  ENTITY_SDAICONCEPT_FEATURE_RELATIONSHIP_WITH_CONDITION_H
#define  ENTITY_SDAICONCEPT_FEATURE_RELATIONSHIP_WITH_CONDITION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiConcept_feature_relationship_with_condition : public SdaiConcept_feature_relationship {
     protected:
        SDAI_Application_instance_ptr _conditional_operator = NULL;
    public: 
        SdaiConcept_feature_relationship_with_condition();
        SdaiConcept_feature_relationship_with_condition( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiConcept_feature_relationship_with_condition( SdaiConcept_feature_relationship_with_condition & e );
        ~SdaiConcept_feature_relationship_with_condition();
        int opcode() {
            return 1615;
        }
        SdaiConcept_feature_operator_ptr_c conditional_operator_() const;
        SdaiConcept_feature_operator_ptr   conditional_operator_();
        void conditional_operator_( const SdaiConcept_feature_operator_ptr x );

};

inline SdaiConcept_feature_relationship_with_condition * create_SdaiConcept_feature_relationship_with_condition() {
    return new SdaiConcept_feature_relationship_with_condition;
}

void init_SdaiConcept_feature_relationship_with_condition(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_concept_feature_relationship_with_condition;
    extern AttrDescriptor *a_2392conditional_operator;
}

#endif
