#ifndef  ENTITY_SDAIINAPT_RELATION_OF_PMI_AND_FEATURE_H
#define  ENTITY_SDAIINAPT_RELATION_OF_PMI_AND_FEATURE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiInapt_relation_of_pmi_and_feature : public SdaiA3m_inapt_pmi_data {
     protected:
    public: 
        SdaiInapt_relation_of_pmi_and_feature();
        SdaiInapt_relation_of_pmi_and_feature( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiInapt_relation_of_pmi_and_feature( SdaiInapt_relation_of_pmi_and_feature & e );
        ~SdaiInapt_relation_of_pmi_and_feature();
        int opcode() {
            return 711;
        }
};

inline SdaiInapt_relation_of_pmi_and_feature * create_SdaiInapt_relation_of_pmi_and_feature() {
    return new SdaiInapt_relation_of_pmi_and_feature;
}

void init_SdaiInapt_relation_of_pmi_and_feature(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_inapt_relation_of_pmi_and_feature;
}

#endif
