#ifndef  ENTITY_SDAIDIMENSIONAL_LOCATION_CC
#define  ENTITY_SDAIDIMENSIONAL_LOCATION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiDimensional_location.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location = 0;

SdaiDimensional_location::SdaiDimensional_location(): SdaiShape_aspect_relationship() {
        /*  parent: SdaiShape_aspect_relationship  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location;
    MakeDerived( "id", "shape_aspect_relationship" );
}

SdaiDimensional_location::SdaiDimensional_location ( SdaiDimensional_location & e ) : SdaiShape_aspect_relationship() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiDimensional_location::~SdaiDimensional_location() {
}

SdaiDimensional_location::SdaiDimensional_location( SDAI_Application_instance * se, bool addAttrs ) : SdaiShape_aspect_relationship( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiShape_aspect_relationship */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location;
    MakeDerived( "id", "shape_aspect_relationship" );
}


void init_SdaiDimensional_location( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "SELF\\shape_aspect_relationship.relating_shape_aspect :<>: SELF\\shape_aspect_relationship.related_shape_aspect\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->_where_rules->Append( wr );
        str.clear();
        str.append( "wr2: (" );
    str.append( "SELF\\shape_aspect_relationship.relating_shape_aspect.of_shape :=: SELF\\shape_aspect_relationship.related_shape_aspect.of_shape\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->_where_rules->Append( wr );
        str.clear();
        str.append( "wr3: (" );
    str.append( "( SELF\\shape_aspect_relationship.relating_shape_aspect\\shape_aspect.product_definitional <> UNKNOWN ) AND ( SELF\\\n" );
    str.append( "        shape_aspect_relationship.related_shape_aspect\\shape_aspect.product_definitional <> UNKNOWN )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->_where_rules->Append( wr );
    str.clear();
    str.append( "SUPERTYPE OF ( " );
    str.append( "ONEOF ( angular_location, dimensional_location_with_path )\n" );
    str.append( ")" );
    ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->AddSupertype_Stmt( str );
    ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect_relationship);
    ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect_relationship->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_dimensional_location );
}

#endif
