#ifndef  ENTITY_SDAIHIGH_DEGREE_PLANAR_SURFACE_CC
#define  ENTITY_SDAIHIGH_DEGREE_PLANAR_SURFACE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiHigh_degree_planar_surface.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2434Rshape_data_quality_criterion_assessment_specification = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2435approximation_tolerance = 0;

SdaiHigh_degree_planar_surface::SdaiHigh_degree_planar_surface(): SdaiOvercomplex_geometry(), _shape_data_quality_criterion_assessment_specification( 0 ) {
        /*  parent: SdaiOvercomplex_geometry  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2434Rshape_data_quality_criterion_assessment_specification, ( SDAI_Application_instance_ptr * ) & _shape_data_quality_criterion_assessment_specification );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "assessment_specification" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2435approximation_tolerance, & _approximation_tolerance );
    a->set_null();
    attributes.push( a );
    MakeDerived( "assessment_specification", "shape_data_quality_criterion" );
}

SdaiHigh_degree_planar_surface::SdaiHigh_degree_planar_surface ( SdaiHigh_degree_planar_surface & e ) : SdaiOvercomplex_geometry() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiHigh_degree_planar_surface::~SdaiHigh_degree_planar_surface() {
}

SdaiHigh_degree_planar_surface::SdaiHigh_degree_planar_surface( SDAI_Application_instance * se, bool addAttrs ) : SdaiOvercomplex_geometry( se, addAttrs ), _shape_data_quality_criterion_assessment_specification( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiOvercomplex_geometry */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2434Rshape_data_quality_criterion_assessment_specification, ( SDAI_Application_instance_ptr * ) &_shape_data_quality_criterion_assessment_specification );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "assessment_specification" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2435approximation_tolerance,  &_approximation_tolerance );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "assessment_specification", "shape_data_quality_criterion" );
}


SdaiShape_data_quality_assessment_by_numerical_test_ptr SdaiHigh_degree_planar_surface::shape_data_quality_criterion_assessment_specification_() {
    if( !_shape_data_quality_criterion_assessment_specification ) {
        _shape_data_quality_criterion_assessment_specification = new SdaiShape_data_quality_assessment_by_numerical_test;
    }
    return (SdaiShape_data_quality_assessment_by_numerical_test_ptr) _shape_data_quality_criterion_assessment_specification;
}

SdaiShape_data_quality_assessment_by_numerical_test_ptr_c SdaiHigh_degree_planar_surface::shape_data_quality_criterion_assessment_specification_() const {
    return (SdaiShape_data_quality_assessment_by_numerical_test_ptr) _shape_data_quality_criterion_assessment_specification;
}

void SdaiHigh_degree_planar_surface::shape_data_quality_criterion_assessment_specification_( const SdaiShape_data_quality_assessment_by_numerical_test_ptr x ) {
    _shape_data_quality_criterion_assessment_specification = x;
}

SdaiLength_measure SdaiHigh_degree_planar_surface::approximation_tolerance_() const {
    return (SdaiLength_measure) _approximation_tolerance;
}

void SdaiHigh_degree_planar_surface::approximation_tolerance_( const SdaiLength_measure x ) {
    _approximation_tolerance = x;
}

void init_SdaiHigh_degree_planar_surface( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_DATA_QUALITY_LOWER_VALUE_LIMIT' IN TYPEOF( SELF\\\n" );
    str.append( "        shape_data_quality_criterion.assessment_specification\\shape_data_quality_assessment_by_numerical_test.threshold ) ) AND ( \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.COUNT_MEASURE'  IN value_limit_type( SELF\\shape_data_quality_criterion.\n" );
    str.append( "        assessment_specification\\shape_data_quality_assessment_by_numerical_test.threshold ) )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules->Append( wr );
        str.clear();
        str.append( "wr2: (" );
    str.append( "validate_measured_data_type( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.COUNT_MEASURE' )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules->Append( wr );
        str.clear();
        str.append( "wr3: (" );
    str.append( "validate_inspected_elements_type( SELF, [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.B_SPLINE_SURFACE'] )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules->Append( wr );
        str.clear();
        str.append( "wr4: (" );
    str.append( "validate_locations_of_extreme_value_type( SELF, [] )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules->Append( wr );
        str.clear();
        str.append( "wr5: (" );
    str.append( "validate_accuracy_types( SELF, [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE'] )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->_where_rules->Append( wr );
    ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_overcomplex_geometry);
    ap242_managed_model_based_3d_engineering_mim_lf::e_overcomplex_geometry->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface);
    ap242_managed_model_based_3d_engineering_mim_lf::a_2434Rshape_data_quality_criterion_assessment_specification =
      new AttrDescriptor( "shape_data_quality_criterion.assessment_specification", ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_assessment_by_numerical_test, LFalse,
       LFalse, AttrType_Redefining, *ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface);
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2434Rshape_data_quality_criterion_assessment_specification);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2435approximation_tolerance =
          new AttrDescriptor("approximation_tolerance",ap242_managed_model_based_3d_engineering_mim_lf::t_length_measure,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface);
        ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2435approximation_tolerance);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_high_degree_planar_surface );
}

#endif
