#ifndef  ENTITY_SDAIA3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM_CC
#define  ENTITY_SDAIA3M_DATA_QUALITY_INSPECTION_CRITERION_REPORT_ITEM_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiA3m_data_quality_inspection_criterion_report_item.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2021representative_measured_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2022value_type_to_report = 0;

SdaiA3m_data_quality_inspection_criterion_report_item::SdaiA3m_data_quality_inspection_criterion_report_item(): SdaiData_quality_inspection_criterion_report_item() {
        /*  parent: SdaiData_quality_inspection_criterion_report_item  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2021representative_measured_value, & _representative_measured_value );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2022value_type_to_report, & _value_type_to_report );
    a->set_null();
    attributes.push( a );
}

SdaiA3m_data_quality_inspection_criterion_report_item::SdaiA3m_data_quality_inspection_criterion_report_item ( SdaiA3m_data_quality_inspection_criterion_report_item & e ) : SdaiData_quality_inspection_criterion_report_item() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiA3m_data_quality_inspection_criterion_report_item::~SdaiA3m_data_quality_inspection_criterion_report_item() {
}

SdaiA3m_data_quality_inspection_criterion_report_item::SdaiA3m_data_quality_inspection_criterion_report_item( SDAI_Application_instance * se, bool addAttrs ) : SdaiData_quality_inspection_criterion_report_item( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiData_quality_inspection_criterion_report_item */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2021representative_measured_value,  &_representative_measured_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2022value_type_to_report,  &_value_type_to_report );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiA3m_data_quality_measured_value_select_ptr SdaiA3m_data_quality_inspection_criterion_report_item::representative_measured_value_()  {
    return &_representative_measured_value;
}

SdaiA3m_data_quality_measured_value_select_ptr_c SdaiA3m_data_quality_inspection_criterion_report_item::representative_measured_value_() const {
    return (const SdaiA3m_data_quality_measured_value_select_ptr) &_representative_measured_value;
}

void SdaiA3m_data_quality_inspection_criterion_report_item::representative_measured_value_( const SdaiA3m_data_quality_measured_value_select_ptr x )  {
    _representative_measured_value = x;
}

SdaiSummary_stats_value_type_var SdaiA3m_data_quality_inspection_criterion_report_item::value_type_to_report_() {
    return (Summary_stats_value_type) _value_type_to_report;
}

const SdaiSummary_stats_value_type_var SdaiA3m_data_quality_inspection_criterion_report_item::value_type_to_report_() const {
    return (const Summary_stats_value_type) _value_type_to_report;
}

void SdaiA3m_data_quality_inspection_criterion_report_item::value_type_to_report_( const SdaiSummary_stats_value_type_var x ) {
    _value_type_to_report.put( x );
}

void init_SdaiA3m_data_quality_inspection_criterion_report_item( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_data_quality_inspection_criterion_report_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_data_quality_inspection_criterion_report_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2021representative_measured_value =
          new AttrDescriptor("representative_measured_value",ap242_managed_model_based_3d_engineering_mim_lf::t_a3m_data_quality_measured_value_select,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2021representative_measured_value);
        ap242_managed_model_based_3d_engineering_mim_lf::a_2022value_type_to_report =
          new AttrDescriptor("value_type_to_report",ap242_managed_model_based_3d_engineering_mim_lf::t_summary_stats_value_type,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2022value_type_to_report);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_data_quality_inspection_criterion_report_item );
}

#endif
