#ifndef  ENTITY_SDAIIDENTIFICATION_ROLE_H
#define  ENTITY_SDAIIDENTIFICATION_ROLE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiIdentification_role : public SDAI_Application_instance {
    protected:
        SDAI_String _name;
        SDAI_String _description;    //  OPTIONAL
    public: 
        SdaiIdentification_role();
        SdaiIdentification_role( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiIdentification_role( SdaiIdentification_role & e );
        ~SdaiIdentification_role();
        int opcode() {
            return 693;
        }
  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

};

inline SdaiIdentification_role * create_SdaiIdentification_role() {
    return new SdaiIdentification_role;
}

void init_SdaiIdentification_role(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_identification_role;
    extern AttrDescriptor *a_1086name;
    extern AttrDescriptor *a_1087description;
}

#endif
