#ifndef  ENTITY_SDAIDERIVED_UNIT_ELEMENT_CC
#define  ENTITY_SDAIDERIVED_UNIT_ELEMENT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiDerived_unit_element.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1744unit = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1745exponent = 0;

SdaiDerived_unit_element::SdaiDerived_unit_element() : _unit( 0 ) {
        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1744unit, ( SDAI_Application_instance_ptr * ) & _unit );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1745exponent, & _exponent );
    a->set_null();
    attributes.push( a );
}

SdaiDerived_unit_element::SdaiDerived_unit_element ( SdaiDerived_unit_element & e ) : SDAI_Application_instance() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiDerived_unit_element::~SdaiDerived_unit_element() {
}

SdaiDerived_unit_element::SdaiDerived_unit_element( SDAI_Application_instance * se, bool addAttrs ) : _unit( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
    ( void ) addAttrs; /* quell potentially unused var */

        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1744unit, ( SDAI_Application_instance_ptr * ) &_unit );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1745exponent,  &_exponent );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiNamed_unit_ptr SdaiDerived_unit_element::unit_() {
    if( !_unit ) {
        _unit = new SdaiNamed_unit;
    }
    return (SdaiNamed_unit_ptr) _unit;
}

SdaiNamed_unit_ptr_c SdaiDerived_unit_element::unit_() const {
    return (SdaiNamed_unit_ptr) _unit;
}

void SdaiDerived_unit_element::unit_( const SdaiNamed_unit_ptr x ) {
    _unit = x;
}

SDAI_Real SdaiDerived_unit_element::exponent_() const {
    return (SDAI_Real) _exponent;
}

void SdaiDerived_unit_element::exponent_( const SDAI_Real x ) {
    _exponent = x;
}

void init_SdaiDerived_unit_element( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::a_1744unit =
      new AttrDescriptor( "unit", ap242_managed_model_based_3d_engineering_mim_lf::e_named_unit, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element);
        ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1744unit);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1745exponent =
          new AttrDescriptor("exponent",t_sdaiREAL,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element);
        ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1745exponent);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_derived_unit_element );
}

#endif
