#ifndef  ENTITY_SDAIGEOMETRY_WITH_LOCAL_NEAR_DEGENERACY_CC
#define  ENTITY_SDAIGEOMETRY_WITH_LOCAL_NEAR_DEGENERACY_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiGeometry_with_local_near_degeneracy.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy = 0;

SdaiGeometry_with_local_near_degeneracy::SdaiGeometry_with_local_near_degeneracy(): SdaiInapt_geometry() {
        /*  parent: SdaiInapt_geometry  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy;
}

SdaiGeometry_with_local_near_degeneracy::SdaiGeometry_with_local_near_degeneracy ( SdaiGeometry_with_local_near_degeneracy & e ) : SdaiInapt_geometry() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiGeometry_with_local_near_degeneracy::~SdaiGeometry_with_local_near_degeneracy() {
}

SdaiGeometry_with_local_near_degeneracy::SdaiGeometry_with_local_near_degeneracy( SDAI_Application_instance * se, bool addAttrs ) : SdaiInapt_geometry( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiInapt_geometry */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy;
}


void init_SdaiGeometry_with_local_near_degeneracy( Registry& reg ) {
    std::string str;

    str.clear();
    str.append( "ABSTRACT SUPERTYPE OF ( " );
    str.append( "ONEOF ( curve_with_small_curvature_radius, short_length_curve_segment, surface_with_small_curvature_radius, \n" );
    str.append( "            small_area_surface_patch, narrow_surface_patch, indistinct_surface_knots, indistinct_curve_knots, \n" );
    str.append( "            nearly_degenerate_surface_boundary, nearly_degenerate_surface_patch )\n" );
    str.append( ")" );
    ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy->AddSupertype_Stmt( str );
    ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_inapt_geometry);
    ap242_managed_model_based_3d_engineering_mim_lf::e_inapt_geometry->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_geometry_with_local_near_degeneracy );
}

#endif
