#ifndef  ENTITY_SDAISDGC_WITH_DIMENSION_H
#define  ENTITY_SDAISDGC_WITH_DIMENSION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSdgc_with_dimension : public SdaiSurface_distance_geometric_constraint {
     protected:
        SDAI_Real _distance_value = 0.0;
    public: 
        SdaiSdgc_with_dimension();
        SdaiSdgc_with_dimension( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSdgc_with_dimension( SdaiSdgc_with_dimension & e );
        ~SdaiSdgc_with_dimension();
        int opcode() {
            return 315;
        }
        SdaiNon_negative_length_measure   distance_value_() const;
        void distance_value_( const SdaiNon_negative_length_measure x );

};

inline SdaiSdgc_with_dimension * create_SdaiSdgc_with_dimension() {
    return new SdaiSdgc_with_dimension;
}

void init_SdaiSdgc_with_dimension(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_sdgc_with_dimension;
    extern AttrDescriptor *a_479distance_value;
}

#endif
