#ifndef  ENTITY_SDAICLASSIFICATION_ASSIGNMENT_CC
#define  ENTITY_SDAICLASSIFICATION_ASSIGNMENT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiClassification_assignment.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2311assigned_class = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_2312role = 0;

SdaiClassification_assignment::SdaiClassification_assignment() : _assigned_class( 0 ), _role( 0 ) {
        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2311assigned_class, ( SDAI_Application_instance_ptr * ) & _assigned_class );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2312role, ( SDAI_Application_instance_ptr * ) & _role );
    a->set_null();
    attributes.push( a );
}

SdaiClassification_assignment::SdaiClassification_assignment ( SdaiClassification_assignment & e ) : SDAI_Application_instance() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiClassification_assignment::~SdaiClassification_assignment() {
}

SdaiClassification_assignment::SdaiClassification_assignment( SDAI_Application_instance * se, bool addAttrs ) : _assigned_class( 0 ), _role( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
    ( void ) addAttrs; /* quell potentially unused var */

        /*  no SuperTypes */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2311assigned_class, ( SDAI_Application_instance_ptr * ) &_assigned_class );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_2312role, ( SDAI_Application_instance_ptr * ) &_role );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiGroup_ptr SdaiClassification_assignment::assigned_class_() {
    if( !_assigned_class ) {
        _assigned_class = new SdaiGroup;
    }
    return (SdaiGroup_ptr) _assigned_class;
}

SdaiGroup_ptr_c SdaiClassification_assignment::assigned_class_() const {
    return (SdaiGroup_ptr) _assigned_class;
}

void SdaiClassification_assignment::assigned_class_( const SdaiGroup_ptr x ) {
    _assigned_class = x;
}

SdaiClassification_role_ptr SdaiClassification_assignment::role_() {
    if( !_role ) {
        _role = new SdaiClassification_role;
    }
    return (SdaiClassification_role_ptr) _role;
}

SdaiClassification_role_ptr_c SdaiClassification_assignment::role_() const {
    return (SdaiClassification_role_ptr) _role;
}

void SdaiClassification_assignment::role_( const SdaiClassification_role_ptr x ) {
    _role = x;
}

void init_SdaiClassification_assignment( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment->AddSupertype_Stmt( "ABSTRACT SUPERTYPE" );
    ap242_managed_model_based_3d_engineering_mim_lf::a_2311assigned_class =
      new AttrDescriptor( "assigned_class", ap242_managed_model_based_3d_engineering_mim_lf::e_group, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2311assigned_class);
    ap242_managed_model_based_3d_engineering_mim_lf::a_2312role =
      new AttrDescriptor( "role", ap242_managed_model_based_3d_engineering_mim_lf::e_classification_role, LFalse,
       LFalse, AttrType_Explicit, *ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_2312role);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_classification_assignment );
}

#endif
