#ifndef  ENTITY_SDAIPRODUCT_PROCESS_PLAN_H
#define  ENTITY_SDAIPRODUCT_PROCESS_PLAN_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiProduct_process_plan : public SdaiProduct_definition_process {
     protected:
    public: 
        SdaiProduct_process_plan();
        SdaiProduct_process_plan( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiProduct_process_plan( SdaiProduct_process_plan & e );
        ~SdaiProduct_process_plan();
        int opcode() {
            return 1731;
        }
};

inline SdaiProduct_process_plan * create_SdaiProduct_process_plan() {
    return new SdaiProduct_process_plan;
}

void init_SdaiProduct_process_plan(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_product_process_plan;
}

#endif
