#ifndef  ENTITY_SDAIPOINT_BASED_LLAI_CC
#define  ENTITY_SDAIPOINT_BASED_LLAI_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiPoint_based_llai.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai = 0;

SdaiPoint_based_llai::SdaiPoint_based_llai(): SdaiLimited_length_area_indicator() {
        /*  parent: SdaiLimited_length_area_indicator  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai;
    MakeDerived( "name", "product_definition" );
}

SdaiPoint_based_llai::SdaiPoint_based_llai ( SdaiPoint_based_llai & e ) : SdaiLimited_length_area_indicator() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiPoint_based_llai::~SdaiPoint_based_llai() {
}

SdaiPoint_based_llai::SdaiPoint_based_llai( SDAI_Application_instance * se, bool addAttrs ) : SdaiLimited_length_area_indicator( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiLimited_length_area_indicator */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai;
    MakeDerived( "name", "product_definition" );
}


void init_SdaiPoint_based_llai( Registry& reg ) {
    std::string str;

    str.clear();
    str.append( "SUPERTYPE OF ( " );
    str.append( "ONEOF ( core_sample, strategy_point )\n" );
    str.append( ")" );
    ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai->AddSupertype_Stmt( str );
    ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_limited_length_area_indicator);
    ap242_managed_model_based_3d_engineering_mim_lf::e_limited_length_area_indicator->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_point_based_llai );
}

#endif
