#ifndef  ENTITY_SDAIA3M_EXTREME_INSTANCE_CC
#define  ENTITY_SDAIA3M_EXTREME_INSTANCE_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiA3m_extreme_instance.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1192locations_of_extreme_value = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1193measured_value = 0;

SdaiA3m_extreme_instance::SdaiA3m_extreme_instance(): SdaiRepresentation_item(), _locations_of_extreme_value( 0 ) {
        /*  parent: SdaiRepresentation_item  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance;
    _locations_of_extreme_value = new SdaiA3m_location_of_extreme_value_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1192locations_of_extreme_value, _locations_of_extreme_value );
    a->set_null();
    attributes.push( a );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1193measured_value, & _measured_value );
    a->set_null();
    attributes.push( a );
}

SdaiA3m_extreme_instance::SdaiA3m_extreme_instance ( SdaiA3m_extreme_instance & e ) : SdaiRepresentation_item() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiA3m_extreme_instance::~SdaiA3m_extreme_instance() {
    delete _locations_of_extreme_value;
}

SdaiA3m_extreme_instance::SdaiA3m_extreme_instance( SDAI_Application_instance * se, bool addAttrs ) : SdaiRepresentation_item( se, addAttrs ), _locations_of_extreme_value( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiRepresentation_item */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance;
    _locations_of_extreme_value = new SdaiA3m_location_of_extreme_value_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1192locations_of_extreme_value,  _locations_of_extreme_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1193measured_value,  &_measured_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
}


SdaiA3m_location_of_extreme_value_select_agg_ptr SdaiA3m_extreme_instance::locations_of_extreme_value_() {
    if( !_locations_of_extreme_value ) {
        _locations_of_extreme_value = new SdaiA3m_location_of_extreme_value_select_agg;
    }
    return ( SdaiA3m_location_of_extreme_value_select_agg_ptr ) _locations_of_extreme_value;
}

SdaiA3m_location_of_extreme_value_select_agg_ptr_c SdaiA3m_extreme_instance::locations_of_extreme_value_() const {
    return ( SdaiA3m_location_of_extreme_value_select_agg_ptr ) _locations_of_extreme_value;
}

void SdaiA3m_extreme_instance::locations_of_extreme_value_( const SdaiA3m_location_of_extreme_value_select_agg_ptr x ) {
    if( !_locations_of_extreme_value ) {
        _locations_of_extreme_value = new SdaiA3m_location_of_extreme_value_select_agg;
    }
    _locations_of_extreme_value->ShallowCopy( * x );
}

SdaiA3m_data_quality_measured_value_select_ptr SdaiA3m_extreme_instance::measured_value_()  {
    return &_measured_value;
}

SdaiA3m_data_quality_measured_value_select_ptr_c SdaiA3m_extreme_instance::measured_value_() const {
    return (const SdaiA3m_data_quality_measured_value_select_ptr) &_measured_value;
}

void SdaiA3m_extreme_instance::measured_value_( const SdaiA3m_data_quality_measured_value_select_ptr x )  {
    _measured_value = x;
}

void init_SdaiA3m_extreme_instance( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_representation_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_representation_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance);
        SetTypeDescriptor * t_282 = new SetTypeDescriptor;
        t_282->AssignAggrCreator((AggregateCreator) create_SdaiA3m_location_of_extreme_value_select_agg);        // Creator function
        t_282->SetBound1( 1 );
        t_282->SetBound2( 2147483647 );
        t_282->FundamentalType(SET_TYPE);
        t_282->Description("SET [1:?] OF a3m_location_of_extreme_value_select");
        t_282->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_282->ReferentType(ap242_managed_model_based_3d_engineering_mim_lf::t_a3m_location_of_extreme_value_select);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_282);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1192locations_of_extreme_value =
          new AttrDescriptor("locations_of_extreme_value",t_282,LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1192locations_of_extreme_value);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1193measured_value =
          new AttrDescriptor("measured_value",ap242_managed_model_based_3d_engineering_mim_lf::t_a3m_data_quality_measured_value_select,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance);
        ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1193measured_value);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_a3m_extreme_instance );
}

#endif
