#ifndef  ENTITY_SDAISHAPE_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM_CC
#define  ENTITY_SDAISHAPE_DATA_QUALITY_INSPECTION_INSTANCE_REPORT_ITEM_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiShape_data_quality_inspection_instance_report_item.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_696Rdata_quality_inspection_instance_report_item_inspected_elements = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_697measured_value = 0;

SdaiShape_data_quality_inspection_instance_report_item::SdaiShape_data_quality_inspection_instance_report_item(): SdaiData_quality_inspection_instance_report_item(), _data_quality_inspection_instance_report_item_inspected_elements( 0 ) {
        /*  parent: SdaiData_quality_inspection_instance_report_item  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item;
    _data_quality_inspection_instance_report_item_inspected_elements = new SdaiInspected_shape_element_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_696Rdata_quality_inspection_instance_report_item_inspected_elements, _data_quality_inspection_instance_report_item_inspected_elements );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "inspected_elements" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_697measured_value, & _measured_value );
    a->set_null();
    attributes.push( a );
    MakeDerived( "inspected_elements", "data_quality_inspection_instance_report_item" );
}

SdaiShape_data_quality_inspection_instance_report_item::SdaiShape_data_quality_inspection_instance_report_item ( SdaiShape_data_quality_inspection_instance_report_item & e ) : SdaiData_quality_inspection_instance_report_item() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiShape_data_quality_inspection_instance_report_item::~SdaiShape_data_quality_inspection_instance_report_item() {
    delete _data_quality_inspection_instance_report_item_inspected_elements;
}

SdaiShape_data_quality_inspection_instance_report_item::SdaiShape_data_quality_inspection_instance_report_item( SDAI_Application_instance * se, bool addAttrs ) : SdaiData_quality_inspection_instance_report_item( se, addAttrs ), _data_quality_inspection_instance_report_item_inspected_elements( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiData_quality_inspection_instance_report_item */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item;
    _data_quality_inspection_instance_report_item_inspected_elements = new SdaiInspected_shape_element_select_agg;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_696Rdata_quality_inspection_instance_report_item_inspected_elements,  _data_quality_inspection_instance_report_item_inspected_elements );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "inspected_elements" );
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_697measured_value,  &_measured_value );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "inspected_elements", "data_quality_inspection_instance_report_item" );
}


SdaiInspected_shape_element_select_agg_ptr SdaiShape_data_quality_inspection_instance_report_item::data_quality_inspection_instance_report_item_inspected_elements_() {
    if( !_data_quality_inspection_instance_report_item_inspected_elements ) {
        _data_quality_inspection_instance_report_item_inspected_elements = new SdaiInspected_shape_element_select_agg;
    }
    return ( SdaiInspected_shape_element_select_agg_ptr ) _data_quality_inspection_instance_report_item_inspected_elements;
}

SdaiInspected_shape_element_select_agg_ptr_c SdaiShape_data_quality_inspection_instance_report_item::data_quality_inspection_instance_report_item_inspected_elements_() const {
    return ( SdaiInspected_shape_element_select_agg_ptr ) _data_quality_inspection_instance_report_item_inspected_elements;
}

void SdaiShape_data_quality_inspection_instance_report_item::data_quality_inspection_instance_report_item_inspected_elements_( const SdaiInspected_shape_element_select_agg_ptr x ) {
    if( !_data_quality_inspection_instance_report_item_inspected_elements ) {
        _data_quality_inspection_instance_report_item_inspected_elements = new SdaiInspected_shape_element_select_agg;
    }
    _data_quality_inspection_instance_report_item_inspected_elements->ShallowCopy( * x );
}

SdaiMeasured_value_select_ptr SdaiShape_data_quality_inspection_instance_report_item::measured_value_()  {
    return &_measured_value;
}

SdaiMeasured_value_select_ptr_c SdaiShape_data_quality_inspection_instance_report_item::measured_value_() const {
    return (const SdaiMeasured_value_select_ptr) &_measured_value;
}

void SdaiShape_data_quality_inspection_instance_report_item::measured_value_( const SdaiMeasured_value_select_ptr x )  {
    _measured_value = x;
}

void init_SdaiShape_data_quality_inspection_instance_report_item( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_data_quality_inspection_instance_report_item);
    ap242_managed_model_based_3d_engineering_mim_lf::e_data_quality_inspection_instance_report_item->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item);
        SetTypeDescriptor * t_157 = new SetTypeDescriptor;
        t_157->AssignAggrCreator((AggregateCreator) create_SdaiInspected_shape_element_select_agg);        // Creator function
        t_157->SetBound1( 1 );
        t_157->SetBound2( 2147483647 );
        t_157->FundamentalType(SET_TYPE);
        t_157->Description("SET [1:?] OF inspected_shape_element_select");
        t_157->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_157->ReferentType(ap242_managed_model_based_3d_engineering_mim_lf::t_inspected_shape_element_select);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_157);
        ap242_managed_model_based_3d_engineering_mim_lf::a_696Rdata_quality_inspection_instance_report_item_inspected_elements =
          new AttrDescriptor("data_quality_inspection_instance_report_item.inspected_elements",t_157,LFalse,LFalse, AttrType_Redefining,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item);
        ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_696Rdata_quality_inspection_instance_report_item_inspected_elements);
        ap242_managed_model_based_3d_engineering_mim_lf::a_697measured_value =
          new AttrDescriptor("measured_value",ap242_managed_model_based_3d_engineering_mim_lf::t_measured_value_select,
          LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item);
        ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_697measured_value);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_shape_data_quality_inspection_instance_report_item );
}

#endif
