#ifndef  ENTITY_SDAIPREVIOUS_CHANGE_ELEMENT_ASSIGNMENT_CC
#define  ENTITY_SDAIPREVIOUS_CHANGE_ELEMENT_ASSIGNMENT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiPrevious_change_element_assignment.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1536Rgroup_assignment_assigned_group = 0;
AttrDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::a_1537items = 0;

SdaiPrevious_change_element_assignment::SdaiPrevious_change_element_assignment(): SdaiGroup_assignment(), _items( 0 ) {
        /*  parent: SdaiGroup_assignment  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1536Rgroup_assignment_assigned_group, & _group_assignment_assigned_group );
    a->set_null();
    attributes.push( a );
    MakeRedefined( a, "assigned_group" );
    _items = new SdaiChange_management_object_agg;
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1537items, _items );
    a->set_null();
    attributes.push( a );
    MakeDerived( "assigned_group", "group_assignment" );
    MakeDerived( "role", "group_assignment" );
}

SdaiPrevious_change_element_assignment::SdaiPrevious_change_element_assignment ( SdaiPrevious_change_element_assignment & e ) : SdaiGroup_assignment() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiPrevious_change_element_assignment::~SdaiPrevious_change_element_assignment() {
    delete _items;
}

SdaiPrevious_change_element_assignment::SdaiPrevious_change_element_assignment( SDAI_Application_instance * se, bool addAttrs ) : SdaiGroup_assignment( se, addAttrs ), _items( 0 ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiGroup_assignment */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment;
    STEPattribute * a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1536Rgroup_assignment_assigned_group,  &_group_assignment_assigned_group );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeRedefined( a, "assigned_group" );
    _items = new SdaiChange_management_object_agg;
    a = new STEPattribute( * ap242_managed_model_based_3d_engineering_mim_lf::a_1537items,  _items );
        /* initialize to NULL (even if not optional)  */
    a ->set_null();
        /* Put attribute on this class' attributes list so the access functions still work. */
    attributes.push( a );
        /* Put attribute on the attributes list for the main inheritance hierarchy.  */
        /* The push method rejects duplicates found by comparing attrDescriptor's.   */
    if( addAttrs ) {
        se->attributes.push( a );
    }
    MakeDerived( "assigned_group", "group_assignment" );
    MakeDerived( "role", "group_assignment" );
}


SdaiPrevious_element_assignment_select_ptr SdaiPrevious_change_element_assignment::group_assignment_assigned_group_()  {
    return &_group_assignment_assigned_group;
}

SdaiPrevious_element_assignment_select_ptr_c SdaiPrevious_change_element_assignment::group_assignment_assigned_group_() const {
    return (const SdaiPrevious_element_assignment_select_ptr) &_group_assignment_assigned_group;
}

void SdaiPrevious_change_element_assignment::group_assignment_assigned_group_( const SdaiPrevious_element_assignment_select_ptr x )  {
    _group_assignment_assigned_group = x;
}

SdaiChange_management_object_agg_ptr SdaiPrevious_change_element_assignment::items_() {
    if( !_items ) {
        _items = new SdaiChange_management_object_agg;
    }
    return ( SdaiChange_management_object_agg_ptr ) _items;
}

SdaiChange_management_object_agg_ptr_c SdaiPrevious_change_element_assignment::items_() const {
    return ( SdaiChange_management_object_agg_ptr ) _items;
}

void SdaiPrevious_change_element_assignment::items_( const SdaiChange_management_object_agg_ptr x ) {
    if( !_items ) {
        _items = new SdaiChange_management_object_agg;
    }
    _items->ShallowCopy( * x );
}

void init_SdaiPrevious_change_element_assignment( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_group_assignment);
    ap242_managed_model_based_3d_engineering_mim_lf::e_group_assignment->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1536Rgroup_assignment_assigned_group =
          new AttrDescriptor("group_assignment.assigned_group",ap242_managed_model_based_3d_engineering_mim_lf::t_previous_element_assignment_select,
          LFalse,LFalse, AttrType_Redefining,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1536Rgroup_assignment_assigned_group);
        SetTypeDescriptor * t_370 = new SetTypeDescriptor;
        t_370->AssignAggrCreator((AggregateCreator) create_SdaiChange_management_object_agg);        // Creator function
        t_370->SetBound1( 1 );
        t_370->SetBound2( 2147483647 );
        t_370->FundamentalType(SET_TYPE);
        t_370->Description("SET [1:?] OF change_management_object");
        t_370->OriginatingSchema(ap242_managed_model_based_3d_engineering_mim_lf::schema);
        t_370->ReferentType(ap242_managed_model_based_3d_engineering_mim_lf::t_change_management_object);
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddUnnamedType(t_370);
        ap242_managed_model_based_3d_engineering_mim_lf::a_1537items =
          new AttrDescriptor("items",t_370,LFalse,LFalse, AttrType_Explicit,
          *ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment);
        ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment->AddExplicitAttr (ap242_managed_model_based_3d_engineering_mim_lf::a_1537items);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_previous_change_element_assignment );
}

#endif
