#ifndef  ENTITY_SDAIENTITY_ASSERTION_CC
#define  ENTITY_SDAIENTITY_ASSERTION_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiEntity_assertion.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion = 0;

SdaiEntity_assertion::SdaiEntity_assertion(): SdaiFact_type() {
        /*  parent: SdaiFact_type  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion;
    MakeDerived( "id", "property_definition" );
}

SdaiEntity_assertion::SdaiEntity_assertion ( SdaiEntity_assertion & e ) : SdaiFact_type() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiEntity_assertion::~SdaiEntity_assertion() {
}

SdaiEntity_assertion::SdaiEntity_assertion( SDAI_Application_instance * se, bool addAttrs ) : SdaiFact_type( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiFact_type */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion;
    MakeDerived( "id", "property_definition" );
}


void init_SdaiEntity_assertion( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_fact_type);
    ap242_managed_model_based_3d_engineering_mim_lf::e_fact_type->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_entity_assertion );
}

#endif
