#ifndef  ENTITY_SDAIRISK_PERCEPTION_RELATIONSHIP_H
#define  ENTITY_SDAIRISK_PERCEPTION_RELATIONSHIP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiRisk_perception_relationship : public SdaiProduct_definition_relationship {
     protected:
        SDAI_Application_instance_ptr _product_definition_relationship_relating_product_definition = NULL;
        SDAI_Application_instance_ptr _product_definition_relationship_related_product_definition = NULL;
    public: 
        SdaiRisk_perception_relationship();
        SdaiRisk_perception_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiRisk_perception_relationship( SdaiRisk_perception_relationship & e );
        ~SdaiRisk_perception_relationship();
        int opcode() {
            return 2380;
        }
        SdaiRisk_perception_ptr_c product_definition_relationship_relating_product_definition_() const;
        SdaiRisk_perception_ptr   product_definition_relationship_relating_product_definition_();
        void product_definition_relationship_relating_product_definition_( const SdaiRisk_perception_ptr x );

        SdaiRisk_perception_ptr_c product_definition_relationship_related_product_definition_() const;
        SdaiRisk_perception_ptr   product_definition_relationship_related_product_definition_();
        void product_definition_relationship_related_product_definition_( const SdaiRisk_perception_ptr x );

};

inline SdaiRisk_perception_relationship * create_SdaiRisk_perception_relationship() {
    return new SdaiRisk_perception_relationship;
}

void init_SdaiRisk_perception_relationship(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_risk_perception_relationship;
    extern AttrDescriptor *a_3525Rproduct_definition_relationship_relating_product_definition;
    extern AttrDescriptor *a_3526Rproduct_definition_relationship_related_product_definition;
}

#endif
