#ifndef  ENTITY_SDAISHAPE_REPRESENTATION_REFERENCE_H
#define  ENTITY_SDAISHAPE_REPRESENTATION_REFERENCE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiShape_representation_reference : public SdaiRepresentation_reference {
     protected:
    public: 
        SdaiShape_representation_reference();
        SdaiShape_representation_reference( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiShape_representation_reference( SdaiShape_representation_reference & e );
        ~SdaiShape_representation_reference();
        int opcode() {
            return 1438;
        }
};

inline SdaiShape_representation_reference * create_SdaiShape_representation_reference() {
    return new SdaiShape_representation_reference;
}

void init_SdaiShape_representation_reference(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_shape_representation_reference;
}

#endif
