#ifndef  ENTITY_SDAIEXTERNAL_IDENTIFICATION_ASSIGNMENT_H
#define  ENTITY_SDAIEXTERNAL_IDENTIFICATION_ASSIGNMENT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiExternal_identification_assignment : public SdaiIdentification_assignment {
     protected:
        SDAI_Application_instance_ptr _source = NULL;
    public: 
        SdaiExternal_identification_assignment();
        SdaiExternal_identification_assignment( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiExternal_identification_assignment( SdaiExternal_identification_assignment & e );
        ~SdaiExternal_identification_assignment();
        int opcode() {
            return 65;
        }
        SdaiExternal_source_ptr_c source_() const;
        SdaiExternal_source_ptr   source_();
        void source_( const SdaiExternal_source_ptr x );

};

inline SdaiExternal_identification_assignment * create_SdaiExternal_identification_assignment() {
    return new SdaiExternal_identification_assignment;
}

void init_SdaiExternal_identification_assignment(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_external_identification_assignment;
    extern AttrDescriptor *a_108source;
}

#endif
