#ifndef  ENTITY_SDAICLOSED_CURVE_STYLE_PARAMETERS_H
#define  ENTITY_SDAICLOSED_CURVE_STYLE_PARAMETERS_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiClosed_curve_style_parameters : public SdaiCurve_style_parameters_representation {
     protected:
    public: 
        SdaiClosed_curve_style_parameters();
        SdaiClosed_curve_style_parameters( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiClosed_curve_style_parameters( SdaiClosed_curve_style_parameters & e );
        ~SdaiClosed_curve_style_parameters();
        int opcode() {
            return 1824;
        }
};

inline SdaiClosed_curve_style_parameters * create_SdaiClosed_curve_style_parameters() {
    return new SdaiClosed_curve_style_parameters;
}

void init_SdaiClosed_curve_style_parameters(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_closed_curve_style_parameters;
}

#endif
