#ifndef  ENTITY_SDAIV5_UUID_ATTRIBUTE_H
#define  ENTITY_SDAIV5_UUID_ATTRIBUTE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiV5_uuid_attribute : public SdaiUuid_attribute {
     protected:
    public: 
        SdaiV5_uuid_attribute();
        SdaiV5_uuid_attribute( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiV5_uuid_attribute( SdaiV5_uuid_attribute & e );
        ~SdaiV5_uuid_attribute();
        int opcode() {
            return 260;
        }
};

inline SdaiV5_uuid_attribute * create_SdaiV5_uuid_attribute() {
    return new SdaiV5_uuid_attribute;
}

void init_SdaiV5_uuid_attribute(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_v5_uuid_attribute;
}

#endif
