#ifndef  ENTITY_SDAITURNED_KNURL_CC
#define  ENTITY_SDAITURNED_KNURL_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "entity/SdaiTurned_knurl.h"

EntityDescriptor * ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl = 0;

SdaiTurned_knurl::SdaiTurned_knurl(): SdaiFeature_definition() {
        /*  parent: SdaiFeature_definition  */
        /* Ignore the first parent since it is */
        /* part of the main inheritance hierarchy */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl;
}

SdaiTurned_knurl::SdaiTurned_knurl ( SdaiTurned_knurl & e ) : SdaiFeature_definition() {
    CopyAs( ( SDAI_Application_instance_ptr ) & e );
}

SdaiTurned_knurl::~SdaiTurned_knurl() {
}

SdaiTurned_knurl::SdaiTurned_knurl( SDAI_Application_instance * se, bool addAttrs ) : SdaiFeature_definition( se, addAttrs ) {
    /* Set this to point to the head entity. */
    HeadEntity(se);
        /* parent: SdaiFeature_definition */
        /* Ignore the first parent since it is part *
        ** of the main inheritance hierarchy        */

    eDesc = ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl;
}


void init_SdaiTurned_knurl( Registry& reg ) {
    std::string str;

    ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules = new Where_rule__list;
        Where_rule * wr;
        str.clear();
        str.append( "wr1: (" );
    str.append( "SELF\\characterized_object.description IN [ 'diamond', 'diagonal', 'straight']\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr2: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( \n" );
    str.append( "        SIZEOF( QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION_REPRESENTATION.'\n" );
    str.append( "        + 'DEFINITION'  ) | ( ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_REPRESENTATION_WITH_PARAMETERS' IN \n" );
    str.append( "        TYPEOF( pdr.used_representation ) ) AND ( 6 <= SIZEOF( pdr.used_representation.items ) ) AND ( SIZEOF( pdr.\n" );
    str.append( "        used_representation.items ) <= 9 ) ) ) ) = 1 ) ) ) = 1\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr3: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.MEASURE_REPRESENTATION_ITEM' IN \n" );
    str.append( "        TYPEOF( it ) ) AND ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.COUNT_MEASURE' IN TYPEOF( it\\measure_with_unit.\n" );
    str.append( "        value_component ) ) AND ( it.name = 'number of teeth' ) ) ) ) <= 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr4: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE_WITH_UNIT'] * TYPEOF( \n" );
    str.append( "        it ) ) = 2 ) AND ( it.name = 'major diameter' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr5: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE_WITH_UNIT'] * TYPEOF( \n" );
    str.append( "        it ) ) = 2 ) AND ( it.name = 'nominal diameter' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr6: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE_WITH_UNIT'] * TYPEOF( \n" );
    str.append( "        it ) ) = 2 ) AND ( it.name = 'tooth depth' ) ) ) ) <= 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr7: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE_WITH_UNIT'] * TYPEOF( \n" );
    str.append( "        it ) ) = 2 ) AND ( it.name = 'root fillet' ) ) ) ) <= 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr8: (" );
    str.append( "SIZEOF( QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION' ) | ( NOT ( \n" );
    str.append( "        SIZEOF( QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.LENGTH_MEASURE_WITH_UNIT'] * TYPEOF( \n" );
    str.append( "        it ) ) = 2 ) AND ( it.name = 'diametral pitch' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr9: (" );
    str.append( "( NOT ( SELF\\characterized_object.description IN [ 'diamond', 'diagonal'] ) ) OR ( SIZEOF( QUERY ( pd <* USEDIN( SELF, \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION'  ) | ( NOT ( SIZEOF( \n" );
    str.append( "        QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( SIZEOF( [ 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'MEASURE_REPRESENTATION_ITEM' , 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PLANE_ANGLE_MEASURE_WITH_UNIT'] * \n" );
    str.append( "        TYPEOF( it ) ) = 2 ) AND ( it.name = 'helix angle' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0 )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr10: (" );
    str.append( "( NOT ( SELF\\characterized_object.description = 'diagonal' ) ) OR ( SIZEOF( QUERY ( pd <* USEDIN( SELF, \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.DEFINITION'  ) | ( NOT ( SIZEOF( \n" );
    str.append( "        QUERY ( impl_rep <* QUERY ( pdr <* USEDIN( pd, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'PROPERTY_DEFINITION_REPRESENTATION.DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_REPRESENTATION_WITH_PARAMETERS'  IN TYPEOF( pdr.used_representation ) ) ) | ( NOT ( SIZEOF( QUERY ( it <* \n" );
    str.append( "        impl_rep.used_representation.items | ( ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.DESCRIPTIVE_REPRESENTATION_ITEM' \n" );
    str.append( "        IN TYPEOF( it ) ) AND ( it.name = 'helix hand' ) ) ) ) = 1 ) ) ) ) = 0 ) ) ) ) = 0 )\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr11: (" );
    str.append( "SIZEOF( QUERY ( pds <* QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.'\n" );
    str.append( "        + 'DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PRODUCT_DEFINITION_SHAPE' IN TYPEOF( pd ) ) ) | ( \n" );
    str.append( "        NOT ( SIZEOF( QUERY ( sa_occ <* USEDIN( pds, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_ASPECT.OF_SHAPE' ) | \n" );
    str.append( "        ( ( sa_occ.description = 'partial area occurrence' ) AND ( SIZEOF( QUERY ( sdr <* QUERY ( sar <* USEDIN( sa_occ, \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_ASPECT_RELATIONSHIP.RELATED_SHAPE_ASPECT'  ) | ( ( sar.description \n" );
    str.append( "        = 'applied area usage' ) AND ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_DEFINING_RELATIONSHIP' IN TYPEOF( \n" );
    str.append( "        sar ) ) ) ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.APPLIED_AREA' IN TYPEOF( sdr.relating_shape_aspect ) ) ) ) \n" );
    str.append( "        = 1 ) ) ) ) = 1 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
        str.clear();
        str.append( "wr12: (" );
    str.append( "SIZEOF( QUERY ( pds <* QUERY ( pd <* USEDIN( SELF, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PROPERTY_DEFINITION.'\n" );
    str.append( "        + 'DEFINITION'  ) | ( 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.PRODUCT_DEFINITION_SHAPE' IN TYPEOF( pd ) ) ) | ( \n" );
    str.append( "        NOT ( SIZEOF( QUERY ( sa_occ <* USEDIN( pds, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_ASPECT.OF_SHAPE' ) | \n" );
    str.append( "        ( SIZEOF( QUERY ( sdr <* QUERY ( sar <* USEDIN( sa_occ, 'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.'\n" );
    str.append( "        + 'SHAPE_ASPECT_RELATIONSHIP.RELATED_SHAPE_ASPECT'  ) | ( ( sar.description = 'applied shape' ) AND ( \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_DEFINING_RELATIONSHIP'  IN TYPEOF( sar ) ) ) ) | ( \n" );
    str.append( "        'AP242_MANAGED_MODEL_BASED_3D_ENGINEERING_MIM_LF.SHAPE_ASPECT'  IN TYPEOF( sdr.relating_shape_aspect ) ) ) ) = 1 ) ) ) = \n" );
    str.append( "        1 ) ) ) ) = 0\n" );
        str.append( ");\n" );
        wr = new Where_rule( str.c_str() );
        ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->_where_rules->Append( wr );
    ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl->AddSupertype(ap242_managed_model_based_3d_engineering_mim_lf::e_feature_definition);
    ap242_managed_model_based_3d_engineering_mim_lf::e_feature_definition->AddSubtype(ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl);
        reg.AddEntity( *ap242_managed_model_based_3d_engineering_mim_lf::e_turned_knurl );
}

#endif
