#ifndef  ENTITY_SDAIUSAGE_ASSOCIATION_H
#define  ENTITY_SDAIUSAGE_ASSOCIATION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiUsage_association : public SdaiAction_method_relationship {
     protected:
        SDAI_Application_instance_ptr _action_method_relationship_relating_method = NULL;
        SDAI_Application_instance_ptr _action_method_relationship_related_method = NULL;
    public: 
        SdaiUsage_association();
        SdaiUsage_association( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiUsage_association( SdaiUsage_association & e );
        ~SdaiUsage_association();
        int opcode() {
            return 1561;
        }
        SdaiInformation_usage_right_ptr_c action_method_relationship_relating_method_() const;
        SdaiInformation_usage_right_ptr   action_method_relationship_relating_method_();
        void action_method_relationship_relating_method_( const SdaiInformation_usage_right_ptr x );

        SdaiInformation_usage_right_ptr_c action_method_relationship_related_method_() const;
        SdaiInformation_usage_right_ptr   action_method_relationship_related_method_();
        void action_method_relationship_related_method_( const SdaiInformation_usage_right_ptr x );

};

inline SdaiUsage_association * create_SdaiUsage_association() {
    return new SdaiUsage_association;
}

void init_SdaiUsage_association(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_usage_association;
    extern AttrDescriptor *a_2307Raction_method_relationship_relating_method;
    extern AttrDescriptor *a_2308Raction_method_relationship_related_method;
    extern Derived_attribute *a_2309Drelated;
    extern Derived_attribute *a_2310Drelating;
}

#endif
