#ifndef  ENTITY_SDAIOUTER_BOUNDARY_CURVE_H
#define  ENTITY_SDAIOUTER_BOUNDARY_CURVE_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiOuter_boundary_curve : public SdaiBoundary_curve {
     protected:
    public: 
        SdaiOuter_boundary_curve();
        SdaiOuter_boundary_curve( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiOuter_boundary_curve( SdaiOuter_boundary_curve & e );
        ~SdaiOuter_boundary_curve();
        int opcode() {
            return 514;
        }
};

inline SdaiOuter_boundary_curve * create_SdaiOuter_boundary_curve() {
    return new SdaiOuter_boundary_curve;
}

void init_SdaiOuter_boundary_curve(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_outer_boundary_curve;
}

#endif
