#ifndef  ENTITY_SDAIEXPLICIT_PROCEDURAL_SHAPE_REPRESENTATION_RELATIONSHIP_H
#define  ENTITY_SDAIEXPLICIT_PROCEDURAL_SHAPE_REPRESENTATION_RELATIONSHIP_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiExplicit_procedural_shape_representation_relationship : public SdaiExplicit_procedural_representation_relationship {
     protected:
        SDAI_Application_instance_ptr _representation_relationship_rep_1 = NULL;
        SDAI_Application_instance_ptr _representation_relationship_rep_2 = NULL;
    public: 
        SdaiExplicit_procedural_shape_representation_relationship();
        SdaiExplicit_procedural_shape_representation_relationship( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiExplicit_procedural_shape_representation_relationship( SdaiExplicit_procedural_shape_representation_relationship & e );
        ~SdaiExplicit_procedural_shape_representation_relationship();
        int opcode() {
            return 2285;
        }
        SdaiProcedural_shape_representation_ptr_c representation_relationship_rep_1_() const;
        SdaiProcedural_shape_representation_ptr   representation_relationship_rep_1_();
        void representation_relationship_rep_1_( const SdaiProcedural_shape_representation_ptr x );

        SdaiShape_representation_ptr_c representation_relationship_rep_2_() const;
        SdaiShape_representation_ptr   representation_relationship_rep_2_();
        void representation_relationship_rep_2_( const SdaiShape_representation_ptr x );

};

inline SdaiExplicit_procedural_shape_representation_relationship * create_SdaiExplicit_procedural_shape_representation_relationship() {
    return new SdaiExplicit_procedural_shape_representation_relationship;
}

void init_SdaiExplicit_procedural_shape_representation_relationship(Registry& reg);

namespace ap242_managed_model_based_3d_engineering_mim_lf {
    extern EntityDescriptor *e_explicit_procedural_shape_representation_relationship;
    extern AttrDescriptor *a_3385Rrepresentation_relationship_rep_1;
    extern AttrDescriptor *a_3386Rrepresentation_relationship_rep_2;
}

#endif
