# CMake generated Testfile for 
# Source directory: /home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3
# Build directory: /home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(generate_cpp_sdai_select_segfault_210e3 "/usr/local/bin/cmake" "--build" "." "--target" "generate_cpp_sdai_select_segfault_210e3" "--config" "")
set_tests_properties(generate_cpp_sdai_select_segfault_210e3 PROPERTIES  LABELS "cpp_schema_gen" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;47;add_test;/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;124;SCHEMA_TESTS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;111;SCHEMA_TARGETS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;0;")
add_test(build_cpp_sdai_select_segfault_210e3 "/usr/local/bin/cmake" "--build" "." "--target" "p21read_sdai_select_segfault_210e3" "--config" "")
set_tests_properties(build_cpp_sdai_select_segfault_210e3 PROPERTIES  DEPENDS "generate_cpp_sdai_select_segfault_210e3" LABELS "cpp_schema_build" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;53;add_test;/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;124;SCHEMA_TESTS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;111;SCHEMA_TARGETS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;0;")
add_test(build_lazy_cpp_sdai_select_segfault_210e3 "/usr/local/bin/cmake" "--build" "." "--target" "lazy_sdai_select_segfault_210e3" "--config" "")
set_tests_properties(build_lazy_cpp_sdai_select_segfault_210e3 PROPERTIES  DEPENDS "build_cpp_sdai_select_segfault_210e3" LABELS "cpp_schema_build" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;60;add_test;/home/runner/work/stepcode/stepcode/cmake/SC_CXX_schema_macros.cmake;124;SCHEMA_TESTS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;111;SCHEMA_TARGETS;/home/runner/work/stepcode/stepcode/build_test/schemas/sdai_select_segfault_210e3/CMakeLists.txt;0;")
