# CMake generated Testfile for 
# Source directory: /home/runner/work/stepcode/stepcode/src/exppp/test
# Build directory: /home/runner/work/stepcode/stepcode/build_test/src/exppp/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(build_exppp "/usr/local/bin/cmake" "--build" "." "--target" "exppp" "--config" "")
set_tests_properties(build_exppp PROPERTIES  WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;9;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(build_tst_breakLongStr "/usr/local/bin/cmake" "--build" "." "--target" "tst_breakLongStr" "--config" "")
set_tests_properties(build_tst_breakLongStr PROPERTIES  WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;18;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_breakLongStr "/home/runner/work/stepcode/stepcode/build_test/bin/tst_breakLongStr")
set_tests_properties(test_breakLongStr PROPERTIES  DEPENDS "build_tst_breakLongStr" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;24;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_exppp_unique_qualifiers "/usr/local/bin/cmake" "-DEXPPP=/home/runner/work/stepcode/stepcode/build_test/bin/exppp" "-DINFILE=/home/runner/work/stepcode/stepcode/test/unitary_schemas/unique_qualifiers.exp" "-P" "/home/runner/work/stepcode/stepcode/src/exppp/test/unique_qualifiers.cmake")
set_tests_properties(test_exppp_unique_qualifiers PROPERTIES  DEPENDS "build_exppp" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test/src/exppp/test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;33;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_exppp_lost_var "/usr/local/bin/cmake" "-DEXPPP=/home/runner/work/stepcode/stepcode/build_test/bin/exppp" "-DINFILE=/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_lost_var.exp" "-P" "/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_lost_var.cmake")
set_tests_properties(test_exppp_lost_var PROPERTIES  DEPENDS "build_exppp" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test/src/exppp/test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;40;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_exppp_inverse_qualifiers "/usr/local/bin/cmake" "-DEXPPP=/home/runner/work/stepcode/stepcode/build_test/bin/exppp" "-DINFILE=/home/runner/work/stepcode/stepcode/test/unitary_schemas/inverse_qualifiers.exp" "-P" "/home/runner/work/stepcode/stepcode/src/exppp/test/inverse_qualifiers.cmake")
set_tests_properties(test_exppp_inverse_qualifiers PROPERTIES  DEPENDS "build_exppp" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test/src/exppp/test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;47;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_exppp_div_slash "/usr/local/bin/cmake" "-DEXPPP=/home/runner/work/stepcode/stepcode/build_test/bin/exppp" "-DINFILE=/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_div_slash.exp" "-P" "/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_div_slash.cmake")
set_tests_properties(test_exppp_div_slash PROPERTIES  DEPENDS "build_exppp" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test/src/exppp/test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;54;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
add_test(test_exppp_supertype_andor "/usr/local/bin/cmake" "-DEXPPP=/home/runner/work/stepcode/stepcode/build_test/bin/exppp" "-DINFILE=/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_supertype_andor.exp" "-P" "/home/runner/work/stepcode/stepcode/src/exppp/test/exppp_supertype_andor.cmake")
set_tests_properties(test_exppp_supertype_andor PROPERTIES  DEPENDS "build_exppp" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test/src/exppp/test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;61;add_test;/home/runner/work/stepcode/stepcode/src/exppp/test/CMakeLists.txt;0;")
