# CMake generated Testfile for 
# Source directory: /home/runner/work/stepcode/stepcode/src/clstepcore/test
# Build directory: /home/runner/work/stepcode/stepcode/build_test/src/clstepcore/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(build_cpp_SupertypesIterator "/usr/local/bin/cmake" "--build" "." "--target" "tst_SupertypesIterator" "--config" "")
set_tests_properties(build_cpp_SupertypesIterator PROPERTIES  DEPENDS "stepcore" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;11;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;23;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(test_SupertypesIterator "/home/runner/work/stepcode/stepcode/build_test/bin/tst_SupertypesIterator")
set_tests_properties(test_SupertypesIterator PROPERTIES  DEPENDS "build_cpp_SupertypesIterator" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;16;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;23;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(build_cpp_operators_STEPattribute "/usr/local/bin/cmake" "--build" "." "--target" "tst_operators_STEPattribute" "--config" "")
set_tests_properties(build_cpp_operators_STEPattribute PROPERTIES  DEPENDS "stepcore" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;11;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;24;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(test_operators_STEPattribute "/home/runner/work/stepcode/stepcode/build_test/bin/tst_operators_STEPattribute")
set_tests_properties(test_operators_STEPattribute PROPERTIES  DEPENDS "build_cpp_operators_STEPattribute" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;16;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;24;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(build_cpp_operators_SDAI_Select "/usr/local/bin/cmake" "--build" "." "--target" "tst_operators_SDAI_Select" "--config" "")
set_tests_properties(build_cpp_operators_SDAI_Select PROPERTIES  DEPENDS "stepcore" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;11;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;25;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(test_operators_SDAI_Select "/home/runner/work/stepcode/stepcode/build_test/bin/tst_operators_SDAI_Select")
set_tests_properties(test_operators_SDAI_Select PROPERTIES  DEPENDS "build_cpp_operators_SDAI_Select" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;16;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;25;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(build_cpp_null_attr "/usr/local/bin/cmake" "--build" "." "--target" "tst_null_attr" "--config" "")
set_tests_properties(build_cpp_null_attr PROPERTIES  DEPENDS "stepcore" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;11;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;26;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
add_test(test_null_attr "/home/runner/work/stepcode/stepcode/build_test/bin/tst_null_attr")
set_tests_properties(test_null_attr PROPERTIES  DEPENDS "build_cpp_null_attr" LABELS "cpp_unit_stepcore" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;16;add_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;26;add_stepcore_test;/home/runner/work/stepcode/stepcode/src/clstepcore/test/CMakeLists.txt;0;")
