#ifndef  TYPE_SDAIDIMENSIONAL_CHARACTERISTIC_H
#define  TYPE_SDAIDIMENSIONAL_CHARACTERISTIC_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiDimensional_characteristic
class SC_SCHEMA_EXPORT SdaiDimensional_characteristic  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   DIMENSIONAL_LOCATION    --  sdaiINSTANCE
    //   DIMENSIONAL_SIZE    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiDimensional_characteristic( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_dimensional_characteristic );
    //  part 1
    SdaiDimensional_characteristic( const SdaiDimensional_location_ptr&,
                                    const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_dimensional_characteristic );
    SdaiDimensional_characteristic( const SdaiDimensional_size_ptr&,
                                    const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_dimensional_characteristic );
    virtual ~SdaiDimensional_characteristic();

    //  part 2
    operator SdaiDimensional_location_ptr();
    operator SdaiDimensional_size_ptr();

    //  part 3
        SdaiShape_aspect_ptr_c applies_to_() const;
        SdaiShape_aspect_ptr   applies_to_();
        void applies_to_( const SdaiShape_aspect_ptr x );

        SdaiShape_aspect_ptr_c related_shape_aspect_() const;
        SdaiShape_aspect_ptr   related_shape_aspect_();
        void related_shape_aspect_( const SdaiShape_aspect_ptr x );

        SdaiShape_aspect_ptr_c relating_shape_aspect_() const;
        SdaiShape_aspect_ptr   relating_shape_aspect_();
        void relating_shape_aspect_( const SdaiShape_aspect_ptr x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiDimensional_characteristic& operator =( const SdaiDimensional_location_ptr& );
    SdaiDimensional_characteristic& operator =( const SdaiDimensional_size_ptr& );
    // not in SDAI
    SdaiDimensional_characteristic& ShallowCopy ( const SdaiDimensional_characteristic& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiDimensional_characteristic& operator =( SdaiDimensional_characteristic * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsDimensional_location() const;
    Logical IsDimensional_size() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiDimensional_characteristic () { return new SdaiDimensional_characteristic; }
typedef SdaiDimensional_characteristic * SdaiDimensional_characteristicH;
typedef SdaiDimensional_characteristic_ptr SdaiDimensional_characteristic_var;


class SdaiDimensional_characteristic_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiDimensional_characteristic_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_dimensional_characteristic );
    ~SdaiDimensional_characteristic_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiDimensional_characteristic( sel_type )); }
};
inline STEPaggregate * create_SdaiDimensional_characteristic_agg () { return new SdaiDimensional_characteristic_agg; }
typedef SdaiDimensional_characteristic_agg_ptr SdaiDimensional_characteristic_agg_var;

/////  END SELECT TYPE dimensional_characteristic

void init_SdaiDimensional_characteristic(Registry& reg);

#endif
