#ifndef  TYPE_SDAIREQUIREMENT_SOURCE_ITEM_H
#define  TYPE_SDAIREQUIREMENT_SOURCE_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiRequirement_source_item
class SC_SCHEMA_EXPORT SdaiRequirement_source_item  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   ACTION_METHOD    --  sdaiINSTANCE
    //   APPLIED_ACTION_METHOD_ASSIGNMENT    --  sdaiINSTANCE
    //   APPLIED_STATE_OBSERVED_ASSIGNMENT    --  sdaiINSTANCE
    //   APPLIED_STATE_TYPE_ASSIGNMENT    --  sdaiINSTANCE
    //   CHARACTERIZED_OBJECT    --  sdaiINSTANCE
    //   CONTRACT    --  sdaiINSTANCE
    //   DIMENSIONAL_LOCATION    --  sdaiINSTANCE
    //   DIMENSIONAL_SIZE    --  sdaiINSTANCE
    //   EXECUTED_ACTION    --  sdaiINSTANCE
    //   GEOMETRIC_TOLERANCE    --  sdaiINSTANCE
    //   GROUP    --  sdaiINSTANCE
    //   GROUP_RELATIONSHIP    --  sdaiINSTANCE
    //   INTERFACE_CONNECTOR_OCCURRENCE    --  sdaiINSTANCE
    //   ORGANIZATION    --  sdaiINSTANCE
    //   ORGANIZATIONAL_PROJECT    --  sdaiINSTANCE
    //   PERSON_AND_ORGANIZATION    --  sdaiINSTANCE
    //   PRODUCT    --  sdaiINSTANCE
    //   PRODUCT_DEFINITION    --  sdaiINSTANCE
    //   PRODUCT_DEFINITION_FORMATION    --  sdaiINSTANCE
    //   PRODUCT_DEFINITION_RELATIONSHIP    --  sdaiINSTANCE
    //   SHAPE_ASPECT    --  sdaiINSTANCE
    //   STATE_OBSERVED    --  sdaiINSTANCE
    //   STATE_TYPE    --  sdaiINSTANCE
    //   VALIDATION    --  sdaiINSTANCE
    //   VERIFICATION    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiRequirement_source_item( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    //  part 1
    SdaiRequirement_source_item( const SdaiAction_method_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiApplied_action_method_assignment_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiApplied_state_observed_assignment_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiApplied_state_type_assignment_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiCharacterized_object_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiContract_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiDimensional_location_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiDimensional_size_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiExecuted_action_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiGeometric_tolerance_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiGroup_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiGroup_relationship_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiInterface_connector_occurrence_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiOrganization_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiOrganizational_project_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiPerson_and_organization_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiProduct_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiProduct_definition_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiProduct_definition_formation_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiProduct_definition_relationship_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiShape_aspect_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiState_observed_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiState_type_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiValidation_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    SdaiRequirement_source_item( const SdaiVerification_ptr&,
                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    virtual ~SdaiRequirement_source_item();

    //  part 2
    operator SdaiAction_method_ptr();
    operator SdaiApplied_action_method_assignment_ptr();
    operator SdaiApplied_state_observed_assignment_ptr();
    operator SdaiApplied_state_type_assignment_ptr();
    operator SdaiCharacterized_object_ptr();
    operator SdaiContract_ptr();
    operator SdaiDimensional_location_ptr();
    operator SdaiDimensional_size_ptr();
    operator SdaiExecuted_action_ptr();
    operator SdaiGeometric_tolerance_ptr();
    operator SdaiGroup_ptr();
    operator SdaiGroup_relationship_ptr();
    operator SdaiInterface_connector_occurrence_ptr();
    operator SdaiOrganization_ptr();
    operator SdaiOrganizational_project_ptr();
    operator SdaiPerson_and_organization_ptr();
    operator SdaiProduct_ptr();
    operator SdaiProduct_definition_ptr();
    operator SdaiProduct_definition_formation_ptr();
    operator SdaiProduct_definition_relationship_ptr();
    operator SdaiShape_aspect_ptr();
    operator SdaiState_observed_ptr();
    operator SdaiState_type_ptr();
    operator SdaiValidation_ptr();
    operator SdaiVerification_ptr();

    //  part 3
        Logical   product_definitional_() const;
        void product_definitional_( const Logical x );

        SdaiProduct_definition_shape_ptr_c of_shape_() const;
        SdaiProduct_definition_shape_ptr   of_shape_();
        void of_shape_( const SdaiProduct_definition_shape_ptr x );

        SdaiProduct_definition_or_reference_ptr_c related_product_definition_() const;
        SdaiProduct_definition_or_reference_ptr   related_product_definition_();
        void related_product_definition_( const SdaiProduct_definition_or_reference_ptr x );

        SdaiProduct_definition_or_reference_ptr_c relating_product_definition_() const;
        SdaiProduct_definition_or_reference_ptr   relating_product_definition_();
        void relating_product_definition_( const SdaiProduct_definition_or_reference_ptr x );

        SdaiProduct_ptr_c of_product_() const;
        SdaiProduct_ptr   of_product_();
        void of_product_( const SdaiProduct_ptr x );

        SdaiProduct_definition_formation_ptr_c formation_() const;
        SdaiProduct_definition_formation_ptr   formation_();
        void formation_( const SdaiProduct_definition_formation_ptr x );

        EntityAggregate_ptr_c frame_of_reference_() const;
        EntityAggregate_ptr   frame_of_reference_();
        void frame_of_reference_( const EntityAggregate_ptr x );

        SdaiOrganization_ptr_c the_organization_() const;
        SdaiOrganization_ptr   the_organization_();
        void the_organization_( const SdaiOrganization_ptr x );

        SdaiPerson_ptr_c the_person_() const;
        SdaiPerson_ptr   the_person_();
        void the_person_( const SdaiPerson_ptr x );

        EntityAggregate_ptr_c responsible_organizations_() const;
        EntityAggregate_ptr   responsible_organizations_();
        void responsible_organizations_( const EntityAggregate_ptr x );

        SdaiGroup_ptr_c related_group_() const;
        SdaiGroup_ptr   related_group_();
        void related_group_( const SdaiGroup_ptr x );

        SdaiGroup_ptr_c relating_group_() const;
        SdaiGroup_ptr   relating_group_();
        void relating_group_( const SdaiGroup_ptr x );

        EntityAggregate_ptr_c tolerance_relationship_() const;
        EntityAggregate_ptr   tolerance_relationship_();
        void tolerance_relationship_( const EntityAggregate_ptr x );

        EntityAggregate_ptr_c auxiliary_classification_() const;
        EntityAggregate_ptr   auxiliary_classification_();
        void auxiliary_classification_( const EntityAggregate_ptr x );

        SdaiGeometric_tolerance_target_ptr_c toleranced_shape_aspect_() const;
        SdaiGeometric_tolerance_target_ptr   toleranced_shape_aspect_();
        void toleranced_shape_aspect_( const SdaiGeometric_tolerance_target_ptr x );

        SdaiLength_measure_with_unit_ptr_c magnitude_() const;
        SdaiLength_measure_with_unit_ptr   magnitude_();
        void magnitude_( const SdaiLength_measure_with_unit_ptr x );

        SdaiAction_method_ptr_c chosen_method_() const;
        SdaiAction_method_ptr   chosen_method_();
        void chosen_method_( const SdaiAction_method_ptr x );

        SdaiShape_aspect_ptr_c applies_to_() const;
        SdaiShape_aspect_ptr   applies_to_();
        void applies_to_( const SdaiShape_aspect_ptr x );

        SdaiShape_aspect_ptr_c related_shape_aspect_() const;
        SdaiShape_aspect_ptr   related_shape_aspect_();
        void related_shape_aspect_( const SdaiShape_aspect_ptr x );

        SdaiShape_aspect_ptr_c relating_shape_aspect_() const;
        SdaiShape_aspect_ptr   relating_shape_aspect_();
        void relating_shape_aspect_( const SdaiShape_aspect_ptr x );

        SdaiContract_type_ptr_c kind_() const;
        SdaiContract_type_ptr   kind_();
        void kind_( const SdaiContract_type_ptr x );

        SdaiState_type_ptr_c assigned_state_type_() const;
        SdaiState_type_ptr   assigned_state_type_();
        void assigned_state_type_( const SdaiState_type_ptr x );

        SdaiState_observed_ptr_c assigned_state_observed_() const;
        SdaiState_observed_ptr   assigned_state_observed_();
        void assigned_state_observed_( const SdaiState_observed_ptr x );

        SdaiAction_method_items_agg_ptr_c items_() const;
        SdaiAction_method_items_agg_ptr   items_();
        void items_( const SdaiAction_method_items_agg_ptr x );

        SdaiAction_method_role_ptr_c role_() const;
        SdaiAction_method_role_ptr   role_();
        void role_( const SdaiAction_method_role_ptr x );

        SdaiAction_method_ptr_c assigned_action_method_() const;
        SdaiAction_method_ptr   assigned_action_method_();
        void assigned_action_method_( const SdaiAction_method_ptr x );

  const SdaiText   purpose_() const;
        SdaiText   purpose_();
        void purpose_( const SdaiText x );

  const SdaiText   consequence_() const;
        SdaiText   consequence_();
        void consequence_( const SdaiText x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiRequirement_source_item& operator =( const SdaiAction_method_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiApplied_action_method_assignment_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiApplied_state_observed_assignment_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiApplied_state_type_assignment_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiCharacterized_object_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiContract_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiDimensional_location_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiDimensional_size_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiExecuted_action_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiGeometric_tolerance_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiGroup_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiGroup_relationship_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiInterface_connector_occurrence_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiOrganization_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiOrganizational_project_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiPerson_and_organization_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiProduct_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiProduct_definition_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiProduct_definition_formation_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiProduct_definition_relationship_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiShape_aspect_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiState_observed_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiState_type_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiValidation_ptr& );
    SdaiRequirement_source_item& operator =( const SdaiVerification_ptr& );
    // not in SDAI
    SdaiRequirement_source_item& ShallowCopy ( const SdaiRequirement_source_item& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiRequirement_source_item& operator =( SdaiRequirement_source_item * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsAction_method() const;
    Logical IsApplied_action_method_assignment() const;
    Logical IsApplied_state_observed_assignment() const;
    Logical IsApplied_state_type_assignment() const;
    Logical IsCharacterized_object() const;
    Logical IsContract() const;
    Logical IsDimensional_location() const;
    Logical IsDimensional_size() const;
    Logical IsExecuted_action() const;
    Logical IsGeometric_tolerance() const;
    Logical IsGroup() const;
    Logical IsGroup_relationship() const;
    Logical IsInterface_connector_occurrence() const;
    Logical IsOrganization() const;
    Logical IsOrganizational_project() const;
    Logical IsPerson_and_organization() const;
    Logical IsProduct() const;
    Logical IsProduct_definition() const;
    Logical IsProduct_definition_formation() const;
    Logical IsProduct_definition_relationship() const;
    Logical IsShape_aspect() const;
    Logical IsState_observed() const;
    Logical IsState_type() const;
    Logical IsValidation() const;
    Logical IsVerification() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiRequirement_source_item () { return new SdaiRequirement_source_item; }
typedef SdaiRequirement_source_item * SdaiRequirement_source_itemH;
typedef SdaiRequirement_source_item_ptr SdaiRequirement_source_item_var;


class SdaiRequirement_source_item_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiRequirement_source_item_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_requirement_source_item );
    ~SdaiRequirement_source_item_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiRequirement_source_item( sel_type )); }
};
inline STEPaggregate * create_SdaiRequirement_source_item_agg () { return new SdaiRequirement_source_item_agg; }
typedef SdaiRequirement_source_item_agg_ptr SdaiRequirement_source_item_agg_var;

/////  END SELECT TYPE requirement_source_item

void init_SdaiRequirement_source_item(Registry& reg);

#endif
