#ifndef  TYPE_SDAIANGLE_DIRECTION_REFERENCE_SELECT_H
#define  TYPE_SDAIANGLE_DIRECTION_REFERENCE_SELECT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiAngle_direction_reference_select
class SC_SCHEMA_EXPORT SdaiAngle_direction_reference_select  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   CURVE    --  sdaiINSTANCE
    //   DIRECTION    --  sdaiINSTANCE
    //   POINT_PATH    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiAngle_direction_reference_select( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_angle_direction_reference_select );
    //  part 1
    SdaiAngle_direction_reference_select( const SdaiCurve_ptr&,
                                          const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_angle_direction_reference_select );
    SdaiAngle_direction_reference_select( const SdaiDirection_ptr&,
                                          const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_angle_direction_reference_select );
    SdaiAngle_direction_reference_select( const SdaiPoint_path_ptr&,
                                          const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_angle_direction_reference_select );
    virtual ~SdaiAngle_direction_reference_select();

    //  part 2
    operator SdaiCurve_ptr();
    operator SdaiDirection_ptr();
    operator SdaiPoint_path_ptr();

    //  part 3
        SdaiPoint_path_members_ptr_c compound_representation_item_item_element_() const;
        SdaiPoint_path_members_ptr   compound_representation_item_item_element_();
        void compound_representation_item_item_element_( const SdaiPoint_path_members_ptr x );

        SdaiCompound_item_definition_ptr_c item_element_() const;
        SdaiCompound_item_definition_ptr   item_element_();
        void item_element_( const SdaiCompound_item_definition_ptr x );

        RealAggregate_ptr_c direction_ratios_() const;
        RealAggregate_ptr   direction_ratios_();
        void direction_ratios_( const RealAggregate_ptr x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiAngle_direction_reference_select& operator =( const SdaiCurve_ptr& );
    SdaiAngle_direction_reference_select& operator =( const SdaiDirection_ptr& );
    SdaiAngle_direction_reference_select& operator =( const SdaiPoint_path_ptr& );
    // not in SDAI
    SdaiAngle_direction_reference_select& ShallowCopy ( const SdaiAngle_direction_reference_select& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiAngle_direction_reference_select& operator =( SdaiAngle_direction_reference_select * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsCurve() const;
    Logical IsDirection() const;
    Logical IsPoint_path() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiAngle_direction_reference_select () { return new SdaiAngle_direction_reference_select; }
typedef SdaiAngle_direction_reference_select * SdaiAngle_direction_reference_selectH;
typedef SdaiAngle_direction_reference_select_ptr SdaiAngle_direction_reference_select_var;


class SdaiAngle_direction_reference_select_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiAngle_direction_reference_select_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_angle_direction_reference_select );
    ~SdaiAngle_direction_reference_select_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiAngle_direction_reference_select( sel_type )); }
};
inline STEPaggregate * create_SdaiAngle_direction_reference_select_agg () { return new SdaiAngle_direction_reference_select_agg; }
typedef SdaiAngle_direction_reference_select_agg_ptr SdaiAngle_direction_reference_select_agg_var;

/////  END SELECT TYPE angle_direction_reference_select

void init_SdaiAngle_direction_reference_select(Registry& reg);

#endif
