#ifndef  TYPE_SDAITESSELLATED_EDGE_OR_VERTEX_H
#define  TYPE_SDAITESSELLATED_EDGE_OR_VERTEX_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiTessellated_edge_or_vertex
class SC_SCHEMA_EXPORT SdaiTessellated_edge_or_vertex  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   TESSELLATED_EDGE    --  sdaiINSTANCE
    //   TESSELLATED_VERTEX    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiTessellated_edge_or_vertex( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_edge_or_vertex );
    //  part 1
    SdaiTessellated_edge_or_vertex( const SdaiTessellated_edge_ptr&,
                                    const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_edge_or_vertex );
    SdaiTessellated_edge_or_vertex( const SdaiTessellated_vertex_ptr&,
                                    const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_edge_or_vertex );
    virtual ~SdaiTessellated_edge_or_vertex();

    //  part 2
    operator SdaiTessellated_edge_ptr();
    operator SdaiTessellated_vertex_ptr();

    //  part 3
        SDAI_Integer   point_index_() const;
        void point_index_( const SDAI_Integer x );

        SdaiVertex_point_ptr_c topological_link_() const;
        SdaiVertex_point_ptr   topological_link_();
        void topological_link_( const SdaiVertex_point_ptr x );

        IntAggregate_ptr_c line_strip_() const;
        IntAggregate_ptr   line_strip_();
        void line_strip_( const IntAggregate_ptr x );

        SdaiEdge_or_curve_ptr_c geometric_link_() const;
        SdaiEdge_or_curve_ptr   geometric_link_();
        void geometric_link_( const SdaiEdge_or_curve_ptr x );

        SdaiCoordinates_list_ptr_c coordinates_() const;
        SdaiCoordinates_list_ptr   coordinates_();
        void coordinates_( const SdaiCoordinates_list_ptr x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiTessellated_edge_or_vertex& operator =( const SdaiTessellated_edge_ptr& );
    SdaiTessellated_edge_or_vertex& operator =( const SdaiTessellated_vertex_ptr& );
    // not in SDAI
    SdaiTessellated_edge_or_vertex& ShallowCopy ( const SdaiTessellated_edge_or_vertex& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiTessellated_edge_or_vertex& operator =( SdaiTessellated_edge_or_vertex * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsTessellated_edge() const;
    Logical IsTessellated_vertex() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiTessellated_edge_or_vertex () { return new SdaiTessellated_edge_or_vertex; }
typedef SdaiTessellated_edge_or_vertex * SdaiTessellated_edge_or_vertexH;
typedef SdaiTessellated_edge_or_vertex_ptr SdaiTessellated_edge_or_vertex_var;


class SdaiTessellated_edge_or_vertex_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiTessellated_edge_or_vertex_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_edge_or_vertex );
    ~SdaiTessellated_edge_or_vertex_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiTessellated_edge_or_vertex( sel_type )); }
};
inline STEPaggregate * create_SdaiTessellated_edge_or_vertex_agg () { return new SdaiTessellated_edge_or_vertex_agg; }
typedef SdaiTessellated_edge_or_vertex_agg_ptr SdaiTessellated_edge_or_vertex_agg_var;

/////  END SELECT TYPE tessellated_edge_or_vertex

void init_SdaiTessellated_edge_or_vertex(Registry& reg);

#endif
