#ifndef  TYPE_SDAIUSED_EQUIVALENCE_REPRESENTATION_SELECT_H
#define  TYPE_SDAIUSED_EQUIVALENCE_REPRESENTATION_SELECT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiUsed_equivalence_representation_select
class SC_SCHEMA_EXPORT SdaiUsed_equivalence_representation_select  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   DATA_EQUIVALENCE_CRITERIA_REPRESENTATION    --  sdaiINSTANCE
    //   DATA_EQUIVALENCE_INSPECTION_RESULT_REPRESENTATION    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiUsed_equivalence_representation_select( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_used_equivalence_representation_select );
    //  part 1
    SdaiUsed_equivalence_representation_select( const SdaiData_equivalence_criteria_representation_ptr&,
                                                const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_used_equivalence_representation_select );
    SdaiUsed_equivalence_representation_select( const SdaiData_equivalence_inspection_result_representation_ptr&,
                                                const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_used_equivalence_representation_select );
    virtual ~SdaiUsed_equivalence_representation_select();

    //  part 2
    operator SdaiData_equivalence_criteria_representation_ptr();
    operator SdaiData_equivalence_inspection_result_representation_ptr();

    //  part 3
        SdaiData_equivalence_criteria_representation_ptr_c criteria_inspected_() const;
        SdaiData_equivalence_criteria_representation_ptr   criteria_inspected_();
        void criteria_inspected_( const SdaiData_equivalence_criteria_representation_ptr x );

        SdaiRepresentation_context_ptr_c context_of_items_() const;
        SdaiRepresentation_context_ptr   context_of_items_();
        void context_of_items_( const SdaiRepresentation_context_ptr x );

        EntityAggregate_ptr_c items_() const;
        EntityAggregate_ptr   items_();
        void items_( const EntityAggregate_ptr x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiUsed_equivalence_representation_select& operator =( const SdaiData_equivalence_criteria_representation_ptr& );
    SdaiUsed_equivalence_representation_select& operator =( const SdaiData_equivalence_inspection_result_representation_ptr& );
    // not in SDAI
    SdaiUsed_equivalence_representation_select& ShallowCopy ( const SdaiUsed_equivalence_representation_select& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiUsed_equivalence_representation_select& operator =( SdaiUsed_equivalence_representation_select * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsData_equivalence_criteria_representation() const;
    Logical IsData_equivalence_inspection_result_representation() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiUsed_equivalence_representation_select () { return new SdaiUsed_equivalence_representation_select; }
typedef SdaiUsed_equivalence_representation_select * SdaiUsed_equivalence_representation_selectH;
typedef SdaiUsed_equivalence_representation_select_ptr SdaiUsed_equivalence_representation_select_var;


class SdaiUsed_equivalence_representation_select_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiUsed_equivalence_representation_select_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_used_equivalence_representation_select );
    ~SdaiUsed_equivalence_representation_select_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiUsed_equivalence_representation_select( sel_type )); }
};
inline STEPaggregate * create_SdaiUsed_equivalence_representation_select_agg () { return new SdaiUsed_equivalence_representation_select_agg; }
typedef SdaiUsed_equivalence_representation_select_agg_ptr SdaiUsed_equivalence_representation_select_agg_var;

/////  END SELECT TYPE used_equivalence_representation_select

void init_SdaiUsed_equivalence_representation_select(Registry& reg);

#endif
