#ifndef  TYPE_SDAICOLOUR_TYPE_ENUM_VAR_CC
#define  TYPE_SDAICOLOUR_TYPE_ENUM_VAR_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "type/SdaiColour_type_enum_var.h"

const char *
SdaiColour_type_enum_var::element_at (int n) const  {
  switch (n)  {
  case Colour_type_enum__rgbt8:  return "RGBT8";
  case Colour_type_enum__rgb8:  return "RGB8";
  case Colour_type_enum_unset        :
  default                :  return "UNSET";
  }
}

SdaiColour_type_enum_var::SdaiColour_type_enum_var (const char * n, EnumTypeDescriptor *et)
  : type(et)
{
  set_value (n);
}

SdaiColour_type_enum_var::operator Colour_type_enum () const {
  switch (v) {
        case Colour_type_enum__rgbt8        :  return Colour_type_enum__rgbt8;
        case Colour_type_enum__rgb8        :  return Colour_type_enum__rgb8;
        case Colour_type_enum_unset        :
        default                :  return Colour_type_enum_unset;
  }
}

SDAI_Enum *
create_SdaiColour_type_enum_var ()
{
    return new SdaiColour_type_enum_var( "", ap242_managed_model_based_3d_engineering_mim_lf::t_colour_type_enum );
}


SdaiColour_type_enum_var_agg::SdaiColour_type_enum_var_agg( EnumTypeDescriptor *et )
    : enum_type(et)
{
}

SdaiColour_type_enum_var_agg::~SdaiColour_type_enum_var_agg()
{
}

STEPaggregate *
create_SdaiColour_type_enum_var_agg ()
{
    return new SdaiColour_type_enum_var_agg( ap242_managed_model_based_3d_engineering_mim_lf::t_colour_type_enum );
}

void init_SdaiColour_type_enum_var( Registry& reg ) {
    std::string str;
        ap242_managed_model_based_3d_engineering_mim_lf::t_colour_type_enum = new EnumTypeDescriptor (
                  "Colour_Type_Enum",        // Name
                  sdaiENUMERATION,        // FundamentalType
                  ap242_managed_model_based_3d_engineering_mim_lf::schema,        // Originating Schema
                  "ENUMERATION of (rgb8, rgbt8)",        // Description
                  (EnumCreator) create_SdaiColour_type_enum_var);        // Creator function
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddType(ap242_managed_model_based_3d_engineering_mim_lf::t_colour_type_enum);
    reg.AddType (*ap242_managed_model_based_3d_engineering_mim_lf::t_colour_type_enum);
}

#endif
