#ifndef  TYPE_SDAISTATISTICAL_VALUE_TYPE_VAR_H
#define  TYPE_SDAISTATISTICAL_VALUE_TYPE_VAR_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

enum Statistical_value_type {
        Statistical_value_type__number_of_inspected_instances,
        Statistical_value_type__number_of_quality_defects_detected,
        Statistical_value_type_unset
};

class SC_SCHEMA_EXPORT SdaiStatistical_value_type_var  :  public SDAI_Enum  {
  protected:
        EnumTypeDescriptor *type;

  public:
        SdaiStatistical_value_type_var (const char * n =0, EnumTypeDescriptor *et =ap242_managed_model_based_3d_engineering_mim_lf::t_statistical_value_type);
        SdaiStatistical_value_type_var (Statistical_value_type e, EnumTypeDescriptor *et =ap242_managed_model_based_3d_engineering_mim_lf::t_statistical_value_type)
                : type(et) {  set_value (e);  }
        SdaiStatistical_value_type_var (const SdaiStatistical_value_type_var &e) { set_value(e); }
        ~SdaiStatistical_value_type_var () { }
        SdaiStatistical_value_type_var& operator= (const SdaiStatistical_value_type_var& e)
                {  set_value (e);  return *this;  }
        operator Statistical_value_type () const;

        inline virtual const char * Name () const
                {  return type->Name();  }
        inline virtual int no_elements () const  {  return 2;  }
        virtual const char * element_at (int n) const;
};

typedef       SdaiStatistical_value_type_var *   SdaiStatistical_value_type_var_ptr;

typedef const SdaiStatistical_value_type_var *   SdaiStatistical_value_type_var_ptr_c;
  SDAI_Enum * create_SdaiStatistical_value_type_var();

class SdaiStatistical_value_type_var_agg  :  public EnumAggregate  {
  protected:
    EnumTypeDescriptor *enum_type;

  public:
    SdaiStatistical_value_type_var_agg( EnumTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_statistical_value_type);
    virtual ~SdaiStatistical_value_type_var_agg();
    virtual SingleLinkNode * NewNode()
        { return new EnumNode (new SdaiStatistical_value_type_var( "", enum_type )); }
};

typedef       SdaiStatistical_value_type_var_agg *   SdaiStatistical_value_type_var_agg_ptr;

typedef const SdaiStatistical_value_type_var_agg *   SdaiStatistical_value_type_var_agg_ptr_c;
  STEPaggregate * create_SdaiStatistical_value_type_var_agg ();
void init_SdaiStatistical_value_type_var(Registry& reg);

#endif
