#ifndef  TYPE_SDAIPOINT_AND_VECTOR_MEMBER_CC
#define  TYPE_SDAIPOINT_AND_VECTOR_MEMBER_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "type/SdaiPoint_and_vector_member.h"


//////////  SELECT TYPE point_and_vector_member

const TypeDescriptor * 
SdaiPoint_and_vector_member::AssignEntity (SDAI_Application_instance * se)
{
  (void)se;
  //  DIRECTION
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_direction))
  {  
    _app_inst = (SdaiDirection_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_direction);
  }
  //  POINT
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_point))
  {  
    _app_inst = (SdaiPoint_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_point);
  }
  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
  std::cerr << se -> EntityName () << std::endl;
#endif
  return 0;
}

SDAI_Select * 
SdaiPoint_and_vector_member::NewSelect ()
{
    SdaiPoint_and_vector_member * tmp = new SdaiPoint_and_vector_member();
    return tmp;
}


// STEP Part 21

void
SdaiPoint_and_vector_member::STEPwrite_content (ostream& out, const char * currSch) const {
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
}

BASE_TYPE
SdaiPoint_and_vector_member::ValueType() const {
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_direction)
        return sdaiINSTANCE;
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_point)
        return sdaiINSTANCE;
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return (BASE_TYPE)0;
}

void
SdaiPoint_and_vector_member::STEPwrite_verbose (ostream& out, const char *currSch) const
{
    const TypeDescriptor *td = CurrentUnderlyingType();
    std::string tmp;

    if ( td ) {
        // If we have a legal underlying type, get its name acc
        // to the current schema.
        StrToUpper( td->Name(currSch), tmp );
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_direction) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_point) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return;
}

Severity
SdaiPoint_and_vector_member::STEPread_content (istream& in, InstMgrBase * instances,
            const char *utype, int addFileId, const char *currSch)
{
  (void)instances;
  (void)utype;
  (void)addFileId;
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
    return severity ();
}

Severity
SdaiPoint_and_vector_member::StrToVal_content (const char * str, InstMgrBase * instances)
{
  (void)str;
  (void)instances;
  switch (base_type)  {
  default:  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
std::cerr << str << "  " << instances << std::endl;
#endif
    return SEVERITY_WARNING;
  }
#ifdef __GNUG__

  return SEVERITY_NULL;
#endif
}

// STEP Part 22:  SDAI

    //  part 0
SdaiPoint_and_vector_member::SdaiPoint_and_vector_member( const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript)
{
#ifdef SC_LOGGING
    if( *logStream )
    {
    *logStream << "DAVE ERR entering SdaiPoint_and_vector_member constructor." << std::endl;
    }
#endif
   _app_inst = NULL;
   _app_inst = NULL;
   nullify();
#ifdef SC_LOGGING
    if( *logStream )
    {
//    *logStream << "DAVE ERR exiting SdaiPoint_and_vector_member constructor." << std::endl;
    }
#endif
}

    //  part 1
SdaiPoint_and_vector_member::SdaiPoint_and_vector_member( const SdaiDirection_ptr& o,
                                                          const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_direction)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiPoint_and_vector_member constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiPoint_and_vector_member constructor." << std::endl; }
#endif
}

SdaiPoint_and_vector_member::SdaiPoint_and_vector_member( const SdaiPoint_ptr& o,
                                                          const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_point)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiPoint_and_vector_member constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiPoint_and_vector_member constructor." << std::endl; }
#endif
}

SdaiPoint_and_vector_member::~SdaiPoint_and_vector_member() {
}

SdaiPoint_and_vector_member_agg::SdaiPoint_and_vector_member_agg( SelectTypeDescriptor *s)
  : SelectAggregate(), sel_type(s)
{
}

SdaiPoint_and_vector_member_agg::~SdaiPoint_and_vector_member_agg() { }


    //  part 2
SdaiPoint_and_vector_member::operator SdaiDirection_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction )
      return ((SdaiDirection_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}

SdaiPoint_and_vector_member::operator SdaiPoint_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point )
      return ((SdaiPoint_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}


    //  part 3

RealAggregate_ptr SdaiPoint_and_vector_member::direction_ratios_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    return ((SdaiDirection_ptr) _app_inst) ->direction_ratios_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


RealAggregate_ptr_c SdaiPoint_and_vector_member::direction_ratios_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    return ((const SdaiDirection_ptr) _app_inst) ->direction_ratios_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiPoint_and_vector_member::direction_ratios_( const RealAggregate_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    {  ((SdaiDirection_ptr) _app_inst) ->direction_ratios_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiLabel SdaiPoint_and_vector_member::name_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    return ((SdaiDirection_ptr) _app_inst) ->name_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point ) 
    //  POINT
    return ((SdaiPoint_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


const SdaiLabel SdaiPoint_and_vector_member::name_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    return ((const SdaiDirection_ptr) _app_inst) ->name_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point ) 
    //  POINT
    return ((const SdaiPoint_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiPoint_and_vector_member::name_( const SdaiLabel x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) 
    //  DIRECTION
    {  ((SdaiDirection_ptr) _app_inst) ->name_( x );
      return;
    }
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point ) 
    //  POINT
    {  ((SdaiPoint_ptr) _app_inst) ->name_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

    //  part 4
SdaiPoint_and_vector_member& SdaiPoint_and_vector_member::operator =( const SdaiDirection_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_direction );
   return *this;
}

SdaiPoint_and_vector_member& SdaiPoint_and_vector_member::operator =( const SdaiPoint_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_point );
   return *this;
}


#ifndef COMPILER_DEFINES_OPERATOR_EQ

SdaiPoint_and_vector_member& SdaiPoint_and_vector_member::operator =( const SdaiPoint_and_vector_member_ptr& o ) {
    SDAI_Select::operator=( *o );
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_point ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    return *this;
}

SDAI_Select& SdaiPoint_and_vector_member::operator =( const SDAI_Select& o ) {
    SDAI_Select::operator=( o );
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_direction ) {
        _app_inst = ( ( SdaiPoint_and_vector_member& ) o )._app_inst;
        return *this;
    }
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_point ) {
        _app_inst = ( ( SdaiPoint_and_vector_member& ) o )._app_inst;
        return *this;
    }
   return *this;
}

#endif //ndef COMPILER_DEFINES_OPERATOR_EQ

    //  part 5
Logical SdaiPoint_and_vector_member::IsDirection() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_direction )
      return LTrue;
   return LFalse;
}

Logical SdaiPoint_and_vector_member::IsPoint() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_point )
      return LTrue;
   return LFalse;
}

//////////  END SELECT TYPE SdaiPoint_and_vector_member


void init_SdaiPoint_and_vector_member( Registry& reg ) {
    std::string str;
        ap242_managed_model_based_3d_engineering_mim_lf::t_point_and_vector_member = new SelectTypeDescriptor (
                  ~(sdaiINSTANCE),        //unique elements,
                  "Point_And_Vector_Member",        // Name
                  sdaiSELECT,        // FundamentalType
                  ap242_managed_model_based_3d_engineering_mim_lf::schema,        // Originating Schema
                  "SELECT (Direction, Point)",        // Description
                  (SelectCreator) create_SdaiPoint_and_vector_member);        // Creator function
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddType(ap242_managed_model_based_3d_engineering_mim_lf::t_point_and_vector_member);
    ap242_managed_model_based_3d_engineering_mim_lf::t_point_and_vector_member -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_direction);
    ap242_managed_model_based_3d_engineering_mim_lf::t_point_and_vector_member -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_point);
    reg.AddType (*ap242_managed_model_based_3d_engineering_mim_lf::t_point_and_vector_member);
}

#endif
