#ifndef  TYPE_SDAIB_SPLINE_OR_RECTANGULAR_COMPOSITE_SURFACE_SELECT_CC
#define  TYPE_SDAIB_SPLINE_OR_RECTANGULAR_COMPOSITE_SURFACE_SELECT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "type/SdaiB_spline_or_rectangular_composite_surface_select.h"


//////////  SELECT TYPE b_spline_or_rectangular_composite_surface_select

const TypeDescriptor * 
SdaiB_spline_or_rectangular_composite_surface_select::AssignEntity (SDAI_Application_instance * se)
{
  (void)se;
  //  B_SPLINE_SURFACE
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface))
  {  
    _app_inst = (SdaiB_spline_surface_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface);
  }
  //  RECTANGULAR_COMPOSITE_SURFACE
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface))
  {  
    _app_inst = (SdaiRectangular_composite_surface_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface);
  }
  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
  std::cerr << se -> EntityName () << std::endl;
#endif
  return 0;
}

SDAI_Select * 
SdaiB_spline_or_rectangular_composite_surface_select::NewSelect ()
{
    SdaiB_spline_or_rectangular_composite_surface_select * tmp = new SdaiB_spline_or_rectangular_composite_surface_select();
    return tmp;
}


// STEP Part 21

void
SdaiB_spline_or_rectangular_composite_surface_select::STEPwrite_content (ostream& out, const char * currSch) const {
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
}

BASE_TYPE
SdaiB_spline_or_rectangular_composite_surface_select::ValueType() const {
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface)
        return sdaiINSTANCE;
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface)
        return sdaiINSTANCE;
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return (BASE_TYPE)0;
}

void
SdaiB_spline_or_rectangular_composite_surface_select::STEPwrite_verbose (ostream& out, const char *currSch) const
{
    const TypeDescriptor *td = CurrentUnderlyingType();
    std::string tmp;

    if ( td ) {
        // If we have a legal underlying type, get its name acc
        // to the current schema.
        StrToUpper( td->Name(currSch), tmp );
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return;
}

Severity
SdaiB_spline_or_rectangular_composite_surface_select::STEPread_content (istream& in, InstMgrBase * instances,
            const char *utype, int addFileId, const char *currSch)
{
  (void)instances;
  (void)utype;
  (void)addFileId;
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
    return severity ();
}

Severity
SdaiB_spline_or_rectangular_composite_surface_select::StrToVal_content (const char * str, InstMgrBase * instances)
{
  (void)str;
  (void)instances;
  switch (base_type)  {
  default:  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
std::cerr << str << "  " << instances << std::endl;
#endif
    return SEVERITY_WARNING;
  }
#ifdef __GNUG__

  return SEVERITY_NULL;
#endif
}

// STEP Part 22:  SDAI

    //  part 0
SdaiB_spline_or_rectangular_composite_surface_select::SdaiB_spline_or_rectangular_composite_surface_select( const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript)
{
#ifdef SC_LOGGING
    if( *logStream )
    {
    *logStream << "DAVE ERR entering SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl;
    }
#endif
   _app_inst = NULL;
   _app_inst = NULL;
   nullify();
#ifdef SC_LOGGING
    if( *logStream )
    {
//    *logStream << "DAVE ERR exiting SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl;
    }
#endif
}

    //  part 1
SdaiB_spline_or_rectangular_composite_surface_select::SdaiB_spline_or_rectangular_composite_surface_select( const SdaiB_spline_surface_ptr& o,
                                                                                                            const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl; }
#endif
}

SdaiB_spline_or_rectangular_composite_surface_select::SdaiB_spline_or_rectangular_composite_surface_select( const SdaiRectangular_composite_surface_ptr& o,
                                                                                                            const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiB_spline_or_rectangular_composite_surface_select constructor." << std::endl; }
#endif
}

SdaiB_spline_or_rectangular_composite_surface_select::~SdaiB_spline_or_rectangular_composite_surface_select() {
}

SdaiB_spline_or_rectangular_composite_surface_select_agg::SdaiB_spline_or_rectangular_composite_surface_select_agg( SelectTypeDescriptor *s)
  : SelectAggregate(), sel_type(s)
{
}

SdaiB_spline_or_rectangular_composite_surface_select_agg::~SdaiB_spline_or_rectangular_composite_surface_select_agg() { }


    //  part 2
SdaiB_spline_or_rectangular_composite_surface_select::operator SdaiB_spline_surface_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface )
      return ((SdaiB_spline_surface_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}

SdaiB_spline_or_rectangular_composite_surface_select::operator SdaiRectangular_composite_surface_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface )
      return ((SdaiRectangular_composite_surface_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}


    //  part 3

GenericAggregate_ptr SdaiB_spline_or_rectangular_composite_surface_select::segments_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    return ((SdaiRectangular_composite_surface_ptr) _app_inst) ->segments_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


GenericAggregate_ptr_c SdaiB_spline_or_rectangular_composite_surface_select::segments_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    return ((const SdaiRectangular_composite_surface_ptr) _app_inst) ->segments_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::segments_( const GenericAggregate_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    {  ((SdaiRectangular_composite_surface_ptr) _app_inst) ->segments_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

Logical SdaiB_spline_or_rectangular_composite_surface_select::self_intersect_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->self_intersect_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (Logical) 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::self_intersect_( const Logical x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->self_intersect_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

Logical SdaiB_spline_or_rectangular_composite_surface_select::v_closed_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->v_closed_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (Logical) 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::v_closed_( const Logical x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->v_closed_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

Logical SdaiB_spline_or_rectangular_composite_surface_select::u_closed_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->u_closed_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (Logical) 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::u_closed_( const Logical x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->u_closed_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiB_spline_surface_form_var SdaiB_spline_or_rectangular_composite_surface_select::surface_form_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->surface_form_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (B_spline_surface_form) 0;
}


const SdaiB_spline_surface_form_var SdaiB_spline_or_rectangular_composite_surface_select::surface_form_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((const SdaiB_spline_surface_ptr) _app_inst) ->surface_form_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (B_spline_surface_form) 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::surface_form_( const SdaiB_spline_surface_form_var x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->surface_form_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

GenericAggregate_ptr SdaiB_spline_or_rectangular_composite_surface_select::control_points_list_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->control_points_list_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


GenericAggregate_ptr_c SdaiB_spline_or_rectangular_composite_surface_select::control_points_list_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((const SdaiB_spline_surface_ptr) _app_inst) ->control_points_list_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::control_points_list_( const GenericAggregate_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->control_points_list_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SDAI_Integer SdaiB_spline_or_rectangular_composite_surface_select::v_degree_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->v_degree_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::v_degree_( const SDAI_Integer x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->v_degree_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SDAI_Integer SdaiB_spline_or_rectangular_composite_surface_select::u_degree_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->u_degree_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::u_degree_( const SDAI_Integer x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->u_degree_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiLabel SdaiB_spline_or_rectangular_composite_surface_select::name_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((SdaiB_spline_surface_ptr) _app_inst) ->name_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    return ((SdaiRectangular_composite_surface_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


const SdaiLabel SdaiB_spline_or_rectangular_composite_surface_select::name_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    return ((const SdaiB_spline_surface_ptr) _app_inst) ->name_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    return ((const SdaiRectangular_composite_surface_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiB_spline_or_rectangular_composite_surface_select::name_( const SdaiLabel x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) 
    //  B_SPLINE_SURFACE
    {  ((SdaiB_spline_surface_ptr) _app_inst) ->name_( x );
      return;
    }
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) 
    //  RECTANGULAR_COMPOSITE_SURFACE
    {  ((SdaiRectangular_composite_surface_ptr) _app_inst) ->name_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

    //  part 4
SdaiB_spline_or_rectangular_composite_surface_select& SdaiB_spline_or_rectangular_composite_surface_select::operator =( const SdaiB_spline_surface_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface );
   return *this;
}

SdaiB_spline_or_rectangular_composite_surface_select& SdaiB_spline_or_rectangular_composite_surface_select::operator =( const SdaiRectangular_composite_surface_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface );
   return *this;
}


#ifndef COMPILER_DEFINES_OPERATOR_EQ

SdaiB_spline_or_rectangular_composite_surface_select& SdaiB_spline_or_rectangular_composite_surface_select::operator =( const SdaiB_spline_or_rectangular_composite_surface_select_ptr& o ) {
    SDAI_Select::operator=( *o );
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    return *this;
}

SDAI_Select& SdaiB_spline_or_rectangular_composite_surface_select::operator =( const SDAI_Select& o ) {
    SDAI_Select::operator=( o );
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface ) {
        _app_inst = ( ( SdaiB_spline_or_rectangular_composite_surface_select& ) o )._app_inst;
        return *this;
    }
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface ) {
        _app_inst = ( ( SdaiB_spline_or_rectangular_composite_surface_select& ) o )._app_inst;
        return *this;
    }
   return *this;
}

#endif //ndef COMPILER_DEFINES_OPERATOR_EQ

    //  part 5
Logical SdaiB_spline_or_rectangular_composite_surface_select::IsB_spline_surface() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface )
      return LTrue;
   return LFalse;
}

Logical SdaiB_spline_or_rectangular_composite_surface_select::IsRectangular_composite_surface() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface )
      return LTrue;
   return LFalse;
}

//////////  END SELECT TYPE SdaiB_spline_or_rectangular_composite_surface_select


void init_SdaiB_spline_or_rectangular_composite_surface_select( Registry& reg ) {
    std::string str;
        ap242_managed_model_based_3d_engineering_mim_lf::t_b_spline_or_rectangular_composite_surface_select = new SelectTypeDescriptor (
                  ~(sdaiINSTANCE),        //unique elements,
                  "B_Spline_Or_Rectangular_Composite_Surface_Select",        // Name
                  sdaiSELECT,        // FundamentalType
                  ap242_managed_model_based_3d_engineering_mim_lf::schema,        // Originating Schema
                  "SELECT (B_Spline_Surface, Rectangular_Composite_Surface)",        // Description
                  (SelectCreator) create_SdaiB_spline_or_rectangular_composite_surface_select);        // Creator function
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddType(ap242_managed_model_based_3d_engineering_mim_lf::t_b_spline_or_rectangular_composite_surface_select);
    ap242_managed_model_based_3d_engineering_mim_lf::t_b_spline_or_rectangular_composite_surface_select -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_b_spline_surface);
    ap242_managed_model_based_3d_engineering_mim_lf::t_b_spline_or_rectangular_composite_surface_select -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_rectangular_composite_surface);
    reg.AddType (*ap242_managed_model_based_3d_engineering_mim_lf::t_b_spline_or_rectangular_composite_surface_select);
}

#endif
