#ifndef  TYPE_SDAILENGTH_OR_PLANE_ANGLE_MEASURE_WITH_UNIT_SELECT_CC
#define  TYPE_SDAILENGTH_OR_PLANE_ANGLE_MEASURE_WITH_UNIT_SELECT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "type/SdaiLength_or_plane_angle_measure_with_unit_select.h"


//////////  SELECT TYPE length_or_plane_angle_measure_with_unit_select

const TypeDescriptor * 
SdaiLength_or_plane_angle_measure_with_unit_select::AssignEntity (SDAI_Application_instance * se)
{
  (void)se;
  //  LENGTH_MEASURE_WITH_UNIT
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit))
  {  
    _app_inst = (SdaiLength_measure_with_unit_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit);
  }
  //  PLANE_ANGLE_MEASURE_WITH_UNIT
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit))
  {  
    _app_inst = (SdaiPlane_angle_measure_with_unit_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit);
  }
  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
  std::cerr << se -> EntityName () << std::endl;
#endif
  return 0;
}

SDAI_Select * 
SdaiLength_or_plane_angle_measure_with_unit_select::NewSelect ()
{
    SdaiLength_or_plane_angle_measure_with_unit_select * tmp = new SdaiLength_or_plane_angle_measure_with_unit_select();
    return tmp;
}


// STEP Part 21

void
SdaiLength_or_plane_angle_measure_with_unit_select::STEPwrite_content (ostream& out, const char * currSch) const {
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
}

BASE_TYPE
SdaiLength_or_plane_angle_measure_with_unit_select::ValueType() const {
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit)
        return sdaiINSTANCE;
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit)
        return sdaiINSTANCE;
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return (BASE_TYPE)0;
}

void
SdaiLength_or_plane_angle_measure_with_unit_select::STEPwrite_verbose (ostream& out, const char *currSch) const
{
    const TypeDescriptor *td = CurrentUnderlyingType();
    std::string tmp;

    if ( td ) {
        // If we have a legal underlying type, get its name acc
        // to the current schema.
        StrToUpper( td->Name(currSch), tmp );
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return;
}

Severity
SdaiLength_or_plane_angle_measure_with_unit_select::STEPread_content (istream& in, InstMgrBase * instances,
            const char *utype, int addFileId, const char *currSch)
{
  (void)instances;
  (void)utype;
  (void)addFileId;
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
    return severity ();
}

Severity
SdaiLength_or_plane_angle_measure_with_unit_select::StrToVal_content (const char * str, InstMgrBase * instances)
{
  (void)str;
  (void)instances;
  switch (base_type)  {
  default:  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
std::cerr << str << "  " << instances << std::endl;
#endif
    return SEVERITY_WARNING;
  }
#ifdef __GNUG__

  return SEVERITY_NULL;
#endif
}

// STEP Part 22:  SDAI

    //  part 0
SdaiLength_or_plane_angle_measure_with_unit_select::SdaiLength_or_plane_angle_measure_with_unit_select( const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript)
{
#ifdef SC_LOGGING
    if( *logStream )
    {
    *logStream << "DAVE ERR entering SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl;
    }
#endif
   _app_inst = NULL;
   _app_inst = NULL;
   nullify();
#ifdef SC_LOGGING
    if( *logStream )
    {
//    *logStream << "DAVE ERR exiting SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl;
    }
#endif
}

    //  part 1
SdaiLength_or_plane_angle_measure_with_unit_select::SdaiLength_or_plane_angle_measure_with_unit_select( const SdaiLength_measure_with_unit_ptr& o,
                                                                                                        const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl; }
#endif
}

SdaiLength_or_plane_angle_measure_with_unit_select::SdaiLength_or_plane_angle_measure_with_unit_select( const SdaiPlane_angle_measure_with_unit_ptr& o,
                                                                                                        const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiLength_or_plane_angle_measure_with_unit_select constructor." << std::endl; }
#endif
}

SdaiLength_or_plane_angle_measure_with_unit_select::~SdaiLength_or_plane_angle_measure_with_unit_select() {
}

SdaiLength_or_plane_angle_measure_with_unit_select_agg::SdaiLength_or_plane_angle_measure_with_unit_select_agg( SelectTypeDescriptor *s)
  : SelectAggregate(), sel_type(s)
{
}

SdaiLength_or_plane_angle_measure_with_unit_select_agg::~SdaiLength_or_plane_angle_measure_with_unit_select_agg() { }


    //  part 2
SdaiLength_or_plane_angle_measure_with_unit_select::operator SdaiLength_measure_with_unit_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit )
      return ((SdaiLength_measure_with_unit_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}

SdaiLength_or_plane_angle_measure_with_unit_select::operator SdaiPlane_angle_measure_with_unit_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit )
      return ((SdaiPlane_angle_measure_with_unit_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}


    //  part 3

SdaiUnit_ptr SdaiLength_or_plane_angle_measure_with_unit_select::unit_component_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    return ((SdaiLength_measure_with_unit_ptr) _app_inst) ->unit_component_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    return ((SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->unit_component_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


SdaiUnit_ptr_c SdaiLength_or_plane_angle_measure_with_unit_select::unit_component_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    return ((const SdaiLength_measure_with_unit_ptr) _app_inst) ->unit_component_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    return ((const SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->unit_component_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiLength_or_plane_angle_measure_with_unit_select::unit_component_( const SdaiUnit_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    {  ((SdaiLength_measure_with_unit_ptr) _app_inst) ->unit_component_( x );
      return;
    }
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    {  ((SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->unit_component_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiMeasure_value_ptr SdaiLength_or_plane_angle_measure_with_unit_select::value_component_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    return ((SdaiLength_measure_with_unit_ptr) _app_inst) ->value_component_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    return ((SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->value_component_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


SdaiMeasure_value_ptr_c SdaiLength_or_plane_angle_measure_with_unit_select::value_component_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    return ((const SdaiLength_measure_with_unit_ptr) _app_inst) ->value_component_();
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    return ((const SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->value_component_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiLength_or_plane_angle_measure_with_unit_select::value_component_( const SdaiMeasure_value_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) 
    //  LENGTH_MEASURE_WITH_UNIT
    {  ((SdaiLength_measure_with_unit_ptr) _app_inst) ->value_component_( x );
      return;
    }
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) 
    //  PLANE_ANGLE_MEASURE_WITH_UNIT
    {  ((SdaiPlane_angle_measure_with_unit_ptr) _app_inst) ->value_component_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

    //  part 4
SdaiLength_or_plane_angle_measure_with_unit_select& SdaiLength_or_plane_angle_measure_with_unit_select::operator =( const SdaiLength_measure_with_unit_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit );
   return *this;
}

SdaiLength_or_plane_angle_measure_with_unit_select& SdaiLength_or_plane_angle_measure_with_unit_select::operator =( const SdaiPlane_angle_measure_with_unit_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit );
   return *this;
}


#ifndef COMPILER_DEFINES_OPERATOR_EQ

SdaiLength_or_plane_angle_measure_with_unit_select& SdaiLength_or_plane_angle_measure_with_unit_select::operator =( const SdaiLength_or_plane_angle_measure_with_unit_select_ptr& o ) {
    SDAI_Select::operator=( *o );
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    return *this;
}

SDAI_Select& SdaiLength_or_plane_angle_measure_with_unit_select::operator =( const SDAI_Select& o ) {
    SDAI_Select::operator=( o );
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit ) {
        _app_inst = ( ( SdaiLength_or_plane_angle_measure_with_unit_select& ) o )._app_inst;
        return *this;
    }
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit ) {
        _app_inst = ( ( SdaiLength_or_plane_angle_measure_with_unit_select& ) o )._app_inst;
        return *this;
    }
   return *this;
}

#endif //ndef COMPILER_DEFINES_OPERATOR_EQ

    //  part 5
Logical SdaiLength_or_plane_angle_measure_with_unit_select::IsLength_measure_with_unit() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit )
      return LTrue;
   return LFalse;
}

Logical SdaiLength_or_plane_angle_measure_with_unit_select::IsPlane_angle_measure_with_unit() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit )
      return LTrue;
   return LFalse;
}

//////////  END SELECT TYPE SdaiLength_or_plane_angle_measure_with_unit_select


void init_SdaiLength_or_plane_angle_measure_with_unit_select( Registry& reg ) {
    std::string str;
        ap242_managed_model_based_3d_engineering_mim_lf::t_length_or_plane_angle_measure_with_unit_select = new SelectTypeDescriptor (
                  ~(sdaiINSTANCE),        //unique elements,
                  "Length_Or_Plane_Angle_Measure_With_Unit_Select",        // Name
                  sdaiSELECT,        // FundamentalType
                  ap242_managed_model_based_3d_engineering_mim_lf::schema,        // Originating Schema
                  "SELECT (Length_Measure_With_Unit, Plane_Angle_Measure_With_Unit)",        // Description
                  (SelectCreator) create_SdaiLength_or_plane_angle_measure_with_unit_select);        // Creator function
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddType(ap242_managed_model_based_3d_engineering_mim_lf::t_length_or_plane_angle_measure_with_unit_select);
    ap242_managed_model_based_3d_engineering_mim_lf::t_length_or_plane_angle_measure_with_unit_select -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_length_measure_with_unit);
    ap242_managed_model_based_3d_engineering_mim_lf::t_length_or_plane_angle_measure_with_unit_select -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_plane_angle_measure_with_unit);
    reg.AddType (*ap242_managed_model_based_3d_engineering_mim_lf::t_length_or_plane_angle_measure_with_unit_select);
}

#endif
