#ifndef  TYPE_SDAITESSELLATED_CONSTRUCTIVE_ELEMENT_SELECT_H
#define  TYPE_SDAITESSELLATED_CONSTRUCTIVE_ELEMENT_SELECT_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiTessellated_constructive_element_select
class SC_SCHEMA_EXPORT SdaiTessellated_constructive_element_select  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   PLACEMENT    --  sdaiINSTANCE
    //   TESSELLATED_CURVE_SET    --  sdaiINSTANCE
    //   TESSELLATED_EDGE    --  sdaiINSTANCE
    //   TESSELLATED_FACE    --  sdaiINSTANCE
    //   TESSELLATED_SURFACE_SET    --  sdaiINSTANCE
    //   TESSELLATED_VERTEX    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiTessellated_constructive_element_select( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    //  part 1
    SdaiTessellated_constructive_element_select( const SdaiPlacement_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    SdaiTessellated_constructive_element_select( const SdaiTessellated_curve_set_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    SdaiTessellated_constructive_element_select( const SdaiTessellated_edge_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    SdaiTessellated_constructive_element_select( const SdaiTessellated_face_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    SdaiTessellated_constructive_element_select( const SdaiTessellated_surface_set_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    SdaiTessellated_constructive_element_select( const SdaiTessellated_vertex_ptr&,
                                                 const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    virtual ~SdaiTessellated_constructive_element_select();

    //  part 2
    operator SdaiPlacement_ptr();
    operator SdaiTessellated_curve_set_ptr();
    operator SdaiTessellated_edge_ptr();
    operator SdaiTessellated_face_ptr();
    operator SdaiTessellated_surface_set_ptr();
    operator SdaiTessellated_vertex_ptr();

    //  part 3
        SDAI_Integer   point_index_() const;
        void point_index_( const SDAI_Integer x );

        SdaiVertex_point_ptr_c topological_link_() const;
        SdaiVertex_point_ptr   topological_link_();
        void topological_link_( const SdaiVertex_point_ptr x );

        GenericAggregate_ptr_c normals_() const;
        GenericAggregate_ptr   normals_();
        void normals_( const GenericAggregate_ptr x );

        SDAI_Integer   pnmax_() const;
        void pnmax_( const SDAI_Integer x );

        IntAggregate_ptr_c line_strip_() const;
        IntAggregate_ptr   line_strip_();
        void line_strip_( const IntAggregate_ptr x );

        SdaiEdge_or_curve_ptr_c geometric_link_() const;
        SdaiEdge_or_curve_ptr   geometric_link_();
        void geometric_link_( const SdaiEdge_or_curve_ptr x );

        GenericAggregate_ptr_c line_strips_() const;
        GenericAggregate_ptr   line_strips_();
        void line_strips_( const GenericAggregate_ptr x );

        SdaiCoordinates_list_ptr_c coordinates_() const;
        SdaiCoordinates_list_ptr   coordinates_();
        void coordinates_( const SdaiCoordinates_list_ptr x );

        SdaiCartesian_point_ptr_c location_() const;
        SdaiCartesian_point_ptr   location_();
        void location_( const SdaiCartesian_point_ptr x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );


    //  part 4
    SdaiTessellated_constructive_element_select& operator =( const SdaiPlacement_ptr& );
    SdaiTessellated_constructive_element_select& operator =( const SdaiTessellated_curve_set_ptr& );
    SdaiTessellated_constructive_element_select& operator =( const SdaiTessellated_edge_ptr& );
    SdaiTessellated_constructive_element_select& operator =( const SdaiTessellated_face_ptr& );
    SdaiTessellated_constructive_element_select& operator =( const SdaiTessellated_surface_set_ptr& );
    SdaiTessellated_constructive_element_select& operator =( const SdaiTessellated_vertex_ptr& );
    // not in SDAI
    SdaiTessellated_constructive_element_select& ShallowCopy ( const SdaiTessellated_constructive_element_select& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiTessellated_constructive_element_select& operator =( SdaiTessellated_constructive_element_select * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsPlacement() const;
    Logical IsTessellated_curve_set() const;
    Logical IsTessellated_edge() const;
    Logical IsTessellated_face() const;
    Logical IsTessellated_surface_set() const;
    Logical IsTessellated_vertex() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiTessellated_constructive_element_select () { return new SdaiTessellated_constructive_element_select; }
typedef SdaiTessellated_constructive_element_select * SdaiTessellated_constructive_element_selectH;
typedef SdaiTessellated_constructive_element_select_ptr SdaiTessellated_constructive_element_select_var;


class SdaiTessellated_constructive_element_select_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiTessellated_constructive_element_select_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_tessellated_constructive_element_select );
    ~SdaiTessellated_constructive_element_select_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiTessellated_constructive_element_select( sel_type )); }
};
inline STEPaggregate * create_SdaiTessellated_constructive_element_select_agg () { return new SdaiTessellated_constructive_element_select_agg; }
typedef SdaiTessellated_constructive_element_select_agg_ptr SdaiTessellated_constructive_element_select_agg_var;

/////  END SELECT TYPE tessellated_constructive_element_select

void init_SdaiTessellated_constructive_element_select(Registry& reg);

#endif
