#ifndef  TYPE_SDAIPERSON_DEFINITION_ITEM_H
#define  TYPE_SDAIPERSON_DEFINITION_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiPerson_definition_item
class SC_SCHEMA_EXPORT SdaiPerson_definition_item  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   EXPERIENCE_TYPE    --  sdaiINSTANCE
    //   QUALIFICATION_TYPE    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiPerson_definition_item( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_person_definition_item );
    //  part 1
    SdaiPerson_definition_item( const SdaiExperience_type_ptr&,
                                const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_person_definition_item );
    SdaiPerson_definition_item( const SdaiQualification_type_ptr&,
                                const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_person_definition_item );
    virtual ~SdaiPerson_definition_item();

    //  part 2
    operator SdaiExperience_type_ptr();
    operator SdaiQualification_type_ptr();

    //  part 3
  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiIdentifier   id_() const;
        SdaiIdentifier   id_();
        void id_( const SdaiIdentifier x );


    //  part 4
    SdaiPerson_definition_item& operator =( const SdaiExperience_type_ptr& );
    SdaiPerson_definition_item& operator =( const SdaiQualification_type_ptr& );
    // not in SDAI
    SdaiPerson_definition_item& ShallowCopy ( const SdaiPerson_definition_item& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiPerson_definition_item& operator =( SdaiPerson_definition_item * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsExperience_type() const;
    Logical IsQualification_type() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiPerson_definition_item () { return new SdaiPerson_definition_item; }
typedef SdaiPerson_definition_item * SdaiPerson_definition_itemH;
typedef SdaiPerson_definition_item_ptr SdaiPerson_definition_item_var;


class SdaiPerson_definition_item_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiPerson_definition_item_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_person_definition_item );
    ~SdaiPerson_definition_item_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiPerson_definition_item( sel_type )); }
};
inline STEPaggregate * create_SdaiPerson_definition_item_agg () { return new SdaiPerson_definition_item_agg; }
typedef SdaiPerson_definition_item_agg_ptr SdaiPerson_definition_item_agg_var;

/////  END SELECT TYPE person_definition_item

void init_SdaiPerson_definition_item(Registry& reg);

#endif
