#ifndef  TYPE_SDAIRISK_IMPACT_ITEM_H
#define  TYPE_SDAIRISK_IMPACT_ITEM_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.


//////////  SELECT TYPE SdaiRisk_impact_item
class SC_SCHEMA_EXPORT SdaiRisk_impact_item  :  public SDAI_Select {
  protected:
    //  types in SELECT 
    //   PRODUCT    --  sdaiINSTANCE
    //   PRODUCT_DEFINITION_FORMATION    --  sdaiINSTANCE
       SDAI_Application_instance_ptr _app_inst;

  public:
    virtual const TypeDescriptor * AssignEntity (SDAI_Application_instance * se);
    virtual SDAI_Select * NewSelect ();

    virtual BASE_TYPE ValueType() const;


// STEP Part 21
    virtual void STEPwrite_content (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual void STEPwrite_verbose (ostream& out =std::cout,
                    const char *currSch =0) const;
    virtual Severity STEPread_content (istream& in =cin,
        InstMgrBase * instances =0, const char *utype =0,
        int addFileId =0, const char *currSch =0);
    virtual Severity StrToVal_content (const char *,
        InstMgrBase * instances =0);

// STEP Part 22:  SDAI

// constructors
    SdaiRisk_impact_item( const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_risk_impact_item );
    //  part 1
    SdaiRisk_impact_item( const SdaiProduct_ptr&,
                          const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_risk_impact_item );
    SdaiRisk_impact_item( const SdaiProduct_definition_formation_ptr&,
                          const SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_risk_impact_item );
    virtual ~SdaiRisk_impact_item();

    //  part 2
    operator SdaiProduct_ptr();
    operator SdaiProduct_definition_formation_ptr();

    //  part 3
        SdaiProduct_ptr_c of_product_() const;
        SdaiProduct_ptr   of_product_();
        void of_product_( const SdaiProduct_ptr x );

        EntityAggregate_ptr_c frame_of_reference_() const;
        EntityAggregate_ptr   frame_of_reference_();
        void frame_of_reference_( const EntityAggregate_ptr x );

  const SdaiText   description_() const;
        SdaiText   description_();
        void description_( const SdaiText x );

  const SdaiLabel   name_() const;
        SdaiLabel   name_();
        void name_( const SdaiLabel x );

  const SdaiIdentifier   id_() const;
        SdaiIdentifier   id_();
        void id_( const SdaiIdentifier x );


    //  part 4
    SdaiRisk_impact_item& operator =( const SdaiProduct_ptr& );
    SdaiRisk_impact_item& operator =( const SdaiProduct_definition_formation_ptr& );
    // not in SDAI
    SdaiRisk_impact_item& ShallowCopy ( const SdaiRisk_impact_item& );

#ifdef COMPILER_DEFINES_OPERATOR_EQ
#else
    SdaiRisk_impact_item& operator =( SdaiRisk_impact_item * const & );
    SDAI_Select& operator =( const SDAI_Select& );
#endif

    //  part 5
    Logical IsProduct() const;
    Logical IsProduct_definition_formation() const;

    //  part 6 ... UnderlyingTypeName () implemented in SDAI_Select class ...

    //  part 7 ... NONE    only for complex selects...
};

inline SDAI_Select * create_SdaiRisk_impact_item () { return new SdaiRisk_impact_item; }
typedef SdaiRisk_impact_item * SdaiRisk_impact_itemH;
typedef SdaiRisk_impact_item_ptr SdaiRisk_impact_item_var;


class SdaiRisk_impact_item_agg : public SelectAggregate {
  protected:
    SelectTypeDescriptor *sel_type;

  public:
    SdaiRisk_impact_item_agg( SelectTypeDescriptor * =ap242_managed_model_based_3d_engineering_mim_lf::t_risk_impact_item );
    ~SdaiRisk_impact_item_agg();
    virtual SingleLinkNode * NewNode()
     { return new SelectNode (new SdaiRisk_impact_item( sel_type )); }
};
inline STEPaggregate * create_SdaiRisk_impact_item_agg () { return new SdaiRisk_impact_item_agg; }
typedef SdaiRisk_impact_item_agg_ptr SdaiRisk_impact_item_agg_var;

/////  END SELECT TYPE risk_impact_item

void init_SdaiRisk_impact_item(Registry& reg);

#endif
