#ifndef  TYPE_SDAIINTERNAL_OR_REFLECTED_SHAPE_ASPECT_CC
#define  TYPE_SDAIINTERNAL_OR_REFLECTED_SHAPE_ASPECT_CC

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

#include "schema.h"
#include "type/SdaiInternal_or_reflected_shape_aspect.h"


//////////  SELECT TYPE internal_or_reflected_shape_aspect

const TypeDescriptor * 
SdaiInternal_or_reflected_shape_aspect::AssignEntity (SDAI_Application_instance * se)
{
  (void)se;
  //  SHAPE_ASPECT
  if (se -> IsA (ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect))
  {  
    _app_inst = (SdaiShape_aspect_ptr) se;
    return SetUnderlyingType (ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect);
  }
  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
  std::cerr << se -> EntityName () << std::endl;
#endif
  return 0;
}

SDAI_Select * 
SdaiInternal_or_reflected_shape_aspect::NewSelect ()
{
    SdaiInternal_or_reflected_shape_aspect * tmp = new SdaiInternal_or_reflected_shape_aspect();
    return tmp;
}


// STEP Part 21

void
SdaiInternal_or_reflected_shape_aspect::STEPwrite_content (ostream& out, const char * currSch) const {
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier) {
        _string.STEPwrite (out);
        return;
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect) {
        _app_inst -> STEPwrite_reference (out);
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
}

BASE_TYPE
SdaiInternal_or_reflected_shape_aspect::ValueType() const {
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier)
        return sdaiSTRING;
    if (CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect)
        return sdaiINSTANCE;
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return (BASE_TYPE)0;
}

void
SdaiInternal_or_reflected_shape_aspect::STEPwrite_verbose (ostream& out, const char *currSch) const
{
    const TypeDescriptor *td = CurrentUnderlyingType();
    std::string tmp;

    if ( td ) {
        // If we have a legal underlying type, get its name acc
        // to the current schema.
        StrToUpper( td->Name(currSch), tmp );
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier) {
        out << tmp << "(";
        _string.STEPwrite (out);
        out << ")";
        return;
    }
    if (td == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect) {
        out <<  tmp << "(";
        _app_inst -> STEPwrite_reference (out);
        out << ")";
        return;
    }
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
    return;
}

Severity
SdaiInternal_or_reflected_shape_aspect::STEPread_content (istream& in, InstMgrBase * instances,
            const char *utype, int addFileId, const char *currSch)
{
  (void)instances;
  (void)utype;
  (void)addFileId;
  (void)currSch;
      if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier) {
        _string.STEPread (in, &_error);
        return severity ();
    }
    if (CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect) {
        // set Underlying Type in Select class
        _app_inst = ReadEntityRef(in, &_error, ",)", instances, addFileId);
        if( _app_inst && ( _app_inst != S_ENTITY_NULL) &&
               ( CurrentUnderlyingType()->CanBe( _app_inst->eDesc ) ) ) {
            return severity();
        } else {
             Error ("Reference to instance that is not indicated type\n");
            _app_inst = 0;
            nullify ();
            return severity (SEVERITY_USERMSG);
        }
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
    return severity ();
}

Severity
SdaiInternal_or_reflected_shape_aspect::StrToVal_content (const char * str, InstMgrBase * instances)
{
  (void)str;
  (void)instances;
  switch (base_type)  {
  case sdaiSTRING :  
    return _string.StrToVal (str);
  default:  // should never be here - done in Select class

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
#ifdef __SUNCPLUSPLUS__
std::cerr << str << "  " << instances << std::endl;
#endif
    return SEVERITY_WARNING;
  }
#ifdef __GNUG__

  return SEVERITY_NULL;
#endif
}

// STEP Part 22:  SDAI

    //  part 0
SdaiInternal_or_reflected_shape_aspect::SdaiInternal_or_reflected_shape_aspect( const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript)
{
#ifdef SC_LOGGING
    if( *logStream )
    {
    *logStream << "DAVE ERR entering SdaiInternal_or_reflected_shape_aspect constructor." << std::endl;
    }
#endif
   _app_inst = NULL;
   nullify();
#ifdef SC_LOGGING
    if( *logStream )
    {
//    *logStream << "DAVE ERR exiting SdaiInternal_or_reflected_shape_aspect constructor." << std::endl;
    }
#endif
}

    //  part 1
SdaiInternal_or_reflected_shape_aspect::SdaiInternal_or_reflected_shape_aspect( const SdaiIdentifier& o,
                                                                                const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::t_identifier)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiInternal_or_reflected_shape_aspect constructor." << std::endl; }
#endif
   _string = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiInternal_or_reflected_shape_aspect constructor." << std::endl; }
#endif
}

SdaiInternal_or_reflected_shape_aspect::SdaiInternal_or_reflected_shape_aspect( const SdaiShape_aspect_ptr& o,
                                                                                const SelectTypeDescriptor *typedescript )
  : SDAI_Select (typedescript, ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect)
{
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR entering SdaiInternal_or_reflected_shape_aspect constructor." << std::endl; }
#endif
   _app_inst = o;
#ifdef SC_LOGGING
    if( *logStream ) { *logStream << "DAVE ERR exiting SdaiInternal_or_reflected_shape_aspect constructor." << std::endl; }
#endif
}

SdaiInternal_or_reflected_shape_aspect::~SdaiInternal_or_reflected_shape_aspect() {
}

SdaiInternal_or_reflected_shape_aspect_agg::SdaiInternal_or_reflected_shape_aspect_agg( SelectTypeDescriptor *s)
  : SelectAggregate(), sel_type(s)
{
}

SdaiInternal_or_reflected_shape_aspect_agg::~SdaiInternal_or_reflected_shape_aspect_agg() { }


    //  part 2
SdaiInternal_or_reflected_shape_aspect::operator SdaiIdentifier()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier )
      return  _string;

   severity( SEVERITY_WARNING );
   Error( "Underlying type is not SdaiIdentifier" );

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return 0;
}

SdaiInternal_or_reflected_shape_aspect::operator SdaiShape_aspect_ptr()
{
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect )
      return ((SdaiShape_aspect_ptr) _app_inst);

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
   return NULL;
}


    //  part 3

Logical SdaiInternal_or_reflected_shape_aspect::product_definitional_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((SdaiShape_aspect_ptr) _app_inst) ->product_definitional_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return (Logical) 0;
}


void SdaiInternal_or_reflected_shape_aspect::product_definitional_( const Logical x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    {  ((SdaiShape_aspect_ptr) _app_inst) ->product_definitional_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiProduct_definition_shape_ptr SdaiInternal_or_reflected_shape_aspect::of_shape_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((SdaiShape_aspect_ptr) _app_inst) ->of_shape_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


SdaiProduct_definition_shape_ptr_c SdaiInternal_or_reflected_shape_aspect::of_shape_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((const SdaiShape_aspect_ptr) _app_inst) ->of_shape_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiInternal_or_reflected_shape_aspect::of_shape_( const SdaiProduct_definition_shape_ptr x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    {  ((SdaiShape_aspect_ptr) _app_inst) ->of_shape_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiText SdaiInternal_or_reflected_shape_aspect::description_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((SdaiShape_aspect_ptr) _app_inst) ->description_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


const SdaiText SdaiInternal_or_reflected_shape_aspect::description_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((const SdaiShape_aspect_ptr) _app_inst) ->description_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiInternal_or_reflected_shape_aspect::description_( const SdaiText x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    {  ((SdaiShape_aspect_ptr) _app_inst) ->description_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

SdaiLabel SdaiInternal_or_reflected_shape_aspect::name_() {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((SdaiShape_aspect_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


const SdaiLabel SdaiInternal_or_reflected_shape_aspect::name_() const {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    return ((const SdaiShape_aspect_ptr) _app_inst) ->name_();
std::cerr << __FILE__ << ":" << __LINE__ <<  ":  ERROR in schema library:  \n" 
    << _POC_ << "\n\n";
   return 0;
}


void SdaiInternal_or_reflected_shape_aspect::name_( const SdaiLabel x ) {
  if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) 
    //  SHAPE_ASPECT
    {  ((SdaiShape_aspect_ptr) _app_inst) ->name_( x );
      return;
    }

   severity( SEVERITY_WARNING );
   std::cerr << __FILE__ << ":" << __LINE__ <<  ":  WARNING:  possible misuse of"
        << " SELECT TYPE from schema library.\n";
   Error( "Mismatch in underlying type." );
}

    //  part 4
SdaiInternal_or_reflected_shape_aspect& SdaiInternal_or_reflected_shape_aspect::operator =( const SdaiIdentifier& o )
{
   nullify ();
   _string = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::t_identifier );
   return *this;
}

SdaiInternal_or_reflected_shape_aspect& SdaiInternal_or_reflected_shape_aspect::operator =( const SdaiShape_aspect_ptr& o )
{
   nullify ();
   _app_inst = o;
   SetUnderlyingType( ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect );
   return *this;
}


#ifndef COMPILER_DEFINES_OPERATOR_EQ

SdaiInternal_or_reflected_shape_aspect& SdaiInternal_or_reflected_shape_aspect::operator =( const SdaiInternal_or_reflected_shape_aspect_ptr& o ) {
    SDAI_Select::operator=( *o );
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier ) {
        _string =  o -> _string;
        return *this;
    }
    if ( o -> CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) {
        _app_inst =  o -> _app_inst;
        return *this;
    }
    return *this;
}

SDAI_Select& SdaiInternal_or_reflected_shape_aspect::operator =( const SDAI_Select& o ) {
    SDAI_Select::operator=( o );
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier ) {
        _string = ( ( SdaiInternal_or_reflected_shape_aspect& ) o )._string;
        return *this;
    }
    if ( o.CurrentUnderlyingType() == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect ) {
        _app_inst = ( ( SdaiInternal_or_reflected_shape_aspect& ) o )._app_inst;
        return *this;
    }
   return *this;
}

#endif //ndef COMPILER_DEFINES_OPERATOR_EQ

    //  part 5
Logical SdaiInternal_or_reflected_shape_aspect::IsIdentifier() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::t_identifier )
      return LTrue;
   return LFalse;
}

Logical SdaiInternal_or_reflected_shape_aspect::IsShape_aspect() const
{
   if( !exists() )
      return LUnknown;
   if( CurrentUnderlyingType () == ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect )
      return LTrue;
   return LFalse;
}

//////////  END SELECT TYPE SdaiInternal_or_reflected_shape_aspect


void init_SdaiInternal_or_reflected_shape_aspect( Registry& reg ) {
    std::string str;
        ap242_managed_model_based_3d_engineering_mim_lf::t_internal_or_reflected_shape_aspect = new SelectTypeDescriptor (
                  ~(0),        //unique elements,
                  "Internal_Or_Reflected_Shape_Aspect",        // Name
                  sdaiSELECT,        // FundamentalType
                  ap242_managed_model_based_3d_engineering_mim_lf::schema,        // Originating Schema
                  "SELECT (Identifier, Shape_Aspect)",        // Description
                  (SelectCreator) create_SdaiInternal_or_reflected_shape_aspect);        // Creator function
        ap242_managed_model_based_3d_engineering_mim_lf::schema->AddType(ap242_managed_model_based_3d_engineering_mim_lf::t_internal_or_reflected_shape_aspect);
    ap242_managed_model_based_3d_engineering_mim_lf::t_internal_or_reflected_shape_aspect -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::t_identifier);
    ap242_managed_model_based_3d_engineering_mim_lf::t_internal_or_reflected_shape_aspect -> Elements ().AddNode (ap242_managed_model_based_3d_engineering_mim_lf::e_shape_aspect);
    reg.AddType (*ap242_managed_model_based_3d_engineering_mim_lf::t_internal_or_reflected_shape_aspect);
}

#endif
