# CMake generated Testfile for 
# Source directory: /home/runner/work/stepcode/stepcode/src/express/test
# Build directory: /home/runner/work/stepcode/stepcode/build_test/src/express/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(exp_resolve_select_enum_member "/home/runner/work/stepcode/stepcode/build_test/bin/test_expr" "resolve_select_enum_member")
set_tests_properties(exp_resolve_select_enum_member PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;29;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(exp_resolve_entity_attribute "/home/runner/work/stepcode/stepcode/build_test/bin/test_expr" "resolve_entity_attribute")
set_tests_properties(exp_resolve_entity_attribute PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;30;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(express_rename_resolve "/home/runner/work/stepcode/stepcode/build_test/bin/test_express" "express_rename_resolve")
set_tests_properties(express_rename_resolve PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;33;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(exp_resolve_bad_func_call "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "exp_resolve_bad_func_call")
set_tests_properties(exp_resolve_bad_func_call PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;37;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(exp_resolve_func_call "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "exp_resolve_func_call")
set_tests_properties(exp_resolve_func_call PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;38;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(exp_resolve_local_identifier "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "exp_resolve_local_identifier")
set_tests_properties(exp_resolve_local_identifier PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;39;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(entity_resolve_subtype_expr_entity "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "entity_resolve_subtype_expr_entity")
set_tests_properties(entity_resolve_subtype_expr_entity PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;40;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(type_resolve_entity "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "type_resolve_entity")
set_tests_properties(type_resolve_entity PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;41;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(stmt_resolve_pcall_proc "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "stmt_resolve_pcall_proc")
set_tests_properties(stmt_resolve_pcall_proc PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;42;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(scope_resolve_named_types "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "scope_resolve_named_types")
set_tests_properties(scope_resolve_named_types PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;43;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(entity_resolve_supertypes_entity "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve" "entity_resolve_supertypes_entity")
set_tests_properties(entity_resolve_supertypes_entity PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;44;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(scope_resolve_expr_stmt "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve2" "scope_resolve_expr_stmt")
set_tests_properties(scope_resolve_expr_stmt PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;47;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(scope_resolve_subsupers "/home/runner/work/stepcode/stepcode/build_test/bin/test_resolve2" "scope_resolve_subsupers")
set_tests_properties(scope_resolve_subsupers PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;48;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(schema_define_ref "/home/runner/work/stepcode/stepcode/build_test/bin/test_schema" "schema_define_ref")
set_tests_properties(schema_define_ref PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;51;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(schema_define_use "/home/runner/work/stepcode/stepcode/build_test/bin/test_schema" "schema_define_use")
set_tests_properties(schema_define_use PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;52;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(schema_get_entities_ref "/home/runner/work/stepcode/stepcode/build_test/bin/test_schema" "schema_get_entities_ref")
set_tests_properties(schema_get_entities_ref PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;53;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(var_find "/home/runner/work/stepcode/stepcode/build_test/bin/test_schema" "var_find")
set_tests_properties(var_find PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;54;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(scope_find "/home/runner/work/stepcode/stepcode/build_test/bin/test_scope" "scope_find")
set_tests_properties(scope_find PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;57;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(type_create_user_defined_tag "/home/runner/work/stepcode/stepcode/build_test/bin/test_type" "type_create_user_defined_tag")
set_tests_properties(type_create_user_defined_tag PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(build_check_express "/usr/local/bin/cmake" "--build" "." "--target" "check-express" "--config" "")
set_tests_properties(build_check_express PROPERTIES  LABELS "parser" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;62;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
add_test(test_plib_parse_err "/home/runner/work/stepcode/stepcode/build_test/bin/check-express" "/home/runner/work/stepcode/stepcode/src/express/test/plib_parse_err.exp")
set_tests_properties(test_plib_parse_err PROPERTIES  DEPENDS "build_check_express;check-express" LABELS "parser" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;69;add_test;/home/runner/work/stepcode/stepcode/src/express/test/CMakeLists.txt;0;")
