#ifndef  ENTITY_SDAIAPPLICATION_PROTOCOL_DEFINITION_H
#define  ENTITY_SDAIAPPLICATION_PROTOCOL_DEFINITION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiApplication_protocol_definition : public SDAI_Application_instance {
    protected:
        SDAI_String _status;
        SDAI_String _application_interpreted_model_schema_name;
        SDAI_Integer _application_protocol_year = 0;
        SDAI_Application_instance_ptr _application = NULL;
    public: 
        SdaiApplication_protocol_definition();
        SdaiApplication_protocol_definition( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiApplication_protocol_definition( SdaiApplication_protocol_definition & e );
        ~SdaiApplication_protocol_definition();
        int opcode() {
            return 114;
        }
  const SdaiLabel   status_() const;
        SdaiLabel   status_();
        void status_( const SdaiLabel x );

  const SdaiLabel   application_interpreted_model_schema_name_() const;
        SdaiLabel   application_interpreted_model_schema_name_();
        void application_interpreted_model_schema_name_( const SdaiLabel x );

        SdaiYear_number   application_protocol_year_() const;
        void application_protocol_year_( const SdaiYear_number x );

        SdaiApplication_context_ptr_c application_() const;
        SdaiApplication_context_ptr   application_();
        void application_( const SdaiApplication_context_ptr x );

};

inline SdaiApplication_protocol_definition * create_SdaiApplication_protocol_definition() {
    return new SdaiApplication_protocol_definition;
}

void init_SdaiApplication_protocol_definition(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_application_protocol_definition;
    extern AttrDescriptor *a_217status;
    extern AttrDescriptor *a_218application_interpreted_model_schema_name;
    extern AttrDescriptor *a_219application_protocol_year;
    extern AttrDescriptor *a_220application;
}

#endif
