#ifndef  ENTITY_SDAISURFACE_OF_LINEAR_EXTRUSION_H
#define  ENTITY_SDAISURFACE_OF_LINEAR_EXTRUSION_H

// This file was generated by exp2cxx,
// 0.9.1.
// You probably don't want to edit it since your modifications
// will be lost if exp2cxx is used to regenerate it.

class SC_SCHEMA_EXPORT SdaiSurface_of_linear_extrusion : public SdaiSwept_surface {
     protected:
        SDAI_Application_instance_ptr _extrusion_axis = NULL;
    public: 
        SdaiSurface_of_linear_extrusion();
        SdaiSurface_of_linear_extrusion( SDAI_Application_instance *se, bool addAttrs = true );
        SdaiSurface_of_linear_extrusion( SdaiSurface_of_linear_extrusion & e );
        ~SdaiSurface_of_linear_extrusion();
        int opcode() {
            return 234;
        }
        SdaiVector_ptr_c extrusion_axis_() const;
        SdaiVector_ptr   extrusion_axis_();
        void extrusion_axis_( const SdaiVector_ptr x );

};

inline SdaiSurface_of_linear_extrusion * create_SdaiSurface_of_linear_extrusion() {
    return new SdaiSurface_of_linear_extrusion;
}

void init_SdaiSurface_of_linear_extrusion(Registry& reg);

namespace config_control_design {
    extern EntityDescriptor *e_surface_of_linear_extrusion;
    extern AttrDescriptor *a_408extrusion_axis;
}

#endif
