# CMake generated Testfile for 
# Source directory: /home/runner/work/stepcode/stepcode/test/cpp/schema_specific
# Build directory: /home/runner/work/stepcode/stepcode/build_test/test/cpp/schema_specific
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(build_cpp_aggregate_bound_runtime "/usr/local/bin/cmake" "--build" "." "--target" "tst_aggregate_bound_runtime" "--config" "")
set_tests_properties(build_cpp_aggregate_bound_runtime PROPERTIES  DEPENDS "build_cpp_sdai_array_bounds_expr" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;81;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_aggregate_bound_runtime "/home/runner/work/stepcode/stepcode/build_test/bin/tst_aggregate_bound_runtime" "/home/runner/work/stepcode/stepcode/test/p21/test_array_bounds.p21")
set_tests_properties(test_aggregate_bound_runtime PROPERTIES  DEPENDS "build_cpp_aggregate_bound_runtime" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;67;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;81;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_aggregate_bound_runtime_FAIL1 "/home/runner/work/stepcode/stepcode/build_test/bin/tst_aggregate_bound_runtime" "/home/runner/work/stepcode/stepcode/test/p21/test_array_bounds_FAIL1.p21")
set_tests_properties(test_aggregate_bound_runtime_FAIL1 PROPERTIES  DEPENDS "test_aggregate_bound_runtime" LABELS "cpp_schema_specific" WILL_FAIL "true" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;85;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(build_cpp_inverse_attr1 "/usr/local/bin/cmake" "--build" "." "--target" "tst_inverse_attr1" "--config" "")
set_tests_properties(build_cpp_inverse_attr1 PROPERTIES  DEPENDS "build_cpp_sdai_inverse_attr" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;92;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_inverse_attr1 "/home/runner/work/stepcode/stepcode/build_test/bin/tst_inverse_attr1" "/home/runner/work/stepcode/stepcode/test/p21/test_inverse_attr.p21")
set_tests_properties(test_inverse_attr1 PROPERTIES  DEPENDS "build_cpp_inverse_attr1" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;67;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;92;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(build_cpp_inverse_attr2 "/usr/local/bin/cmake" "--build" "." "--target" "tst_inverse_attr2" "--config" "")
set_tests_properties(build_cpp_inverse_attr2 PROPERTIES  DEPENDS "build_cpp_sdai_inverse_attr" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;93;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_inverse_attr2 "/home/runner/work/stepcode/stepcode/build_test/bin/tst_inverse_attr2" "/home/runner/work/stepcode/stepcode/test/p21/test_inverse_attr.p21")
set_tests_properties(test_inverse_attr2 PROPERTIES  DEPENDS "build_cpp_inverse_attr2" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;67;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;93;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(build_cpp_inverse_attr3 "/usr/local/bin/cmake" "--build" "." "--target" "tst_inverse_attr3" "--config" "")
set_tests_properties(build_cpp_inverse_attr3 PROPERTIES  DEPENDS "build_cpp_sdai_inverse_attr" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;94;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_inverse_attr3 "/home/runner/work/stepcode/stepcode/build_test/bin/tst_inverse_attr3" "/home/runner/work/stepcode/stepcode/test/p21/test_inverse_attr.p21")
set_tests_properties(test_inverse_attr3 PROPERTIES  DEPENDS "build_cpp_inverse_attr3" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;67;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;94;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(build_cpp_attribute "/usr/local/bin/cmake" "--build" "." "--target" "tst_attribute" "--config" "")
set_tests_properties(build_cpp_attribute PROPERTIES  DEPENDS "build_cpp_sdai_inverse_attr" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;60;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;96;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
add_test(test_attribute "/home/runner/work/stepcode/stepcode/build_test/bin/tst_attribute" "/home/runner/work/stepcode/stepcode/test/p21/test_inverse_attr.p21")
set_tests_properties(test_attribute PROPERTIES  DEPENDS "build_cpp_attribute" LABELS "cpp_schema_specific" WORKING_DIRECTORY "/home/runner/work/stepcode/stepcode/build_test" _BACKTRACE_TRIPLES "/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;67;add_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;96;add_schema_dependent_test;/home/runner/work/stepcode/stepcode/test/cpp/schema_specific/CMakeLists.txt;0;")
subdirs("../../../schemas/sdai_array_bounds_expr")
subdirs("../../../schemas/sdai_inverse_attr")
