ExternalProject_Add(STEPCODE
  URL ${CMAKE_CURRENT_SOURCE_DIR}/../../..
  CMAKE_ARGS
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
    -DSC_BUILD_SCHEMAS=ap203/ap203.exp
    -DBUILD_STATIC_LIBS=ON
    -DBUILD_SHARED_LIBS=OFF
    -DSC_PYTHON_GENERATOR=OFF
    -DSC_ENABLE_TESTING=OFF
)

ExternalProject_Get_Property(STEPCODE INSTALL_DIR)
set(STEPCODE_INSTALL_DIR "${INSTALL_DIR}")

